// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by golden/src/cables.rs from muir's data/cables.txt.
// Do not edit; run `make cables`.
//
// The processor's ports: the 92 wires on the five flat cables to the
// bus interface, from the processor's point of view.  A wire only the
// far end drives is an `input`; one only this end drives, an `output`;
// one both drive is carried as a value and an enable out, with the
// resolved wire back in, because fabric has no bus to fight over.
//
// Names are MIT's, mangled: a leading `-` is `n_`, and `.`, ` `, `/`
// and `>` are `_`.  cadr_cables.map has every one against its original.

    output var logic MEM31_o,
    output var logic MEM31_oe,
    input  var logic MEM31_i,     // MEM31
    output var logic MEM30_o,
    output var logic MEM30_oe,
    input  var logic MEM30_i,     // MEM30
    output var logic MEM29_o,
    output var logic MEM29_oe,
    input  var logic MEM29_i,     // MEM29
    output var logic MEM28_o,
    output var logic MEM28_oe,
    input  var logic MEM28_i,     // MEM28
    output var logic MEM27_o,
    output var logic MEM27_oe,
    input  var logic MEM27_i,     // MEM27
    output var logic MEM26_o,
    output var logic MEM26_oe,
    input  var logic MEM26_i,     // MEM26
    output var logic MEM25_o,
    output var logic MEM25_oe,
    input  var logic MEM25_i,     // MEM25
    output var logic MEM24_o,
    output var logic MEM24_oe,
    input  var logic MEM24_i,     // MEM24
    output var logic MEM23_o,
    output var logic MEM23_oe,
    input  var logic MEM23_i,     // MEM23
    output var logic MEM22_o,
    output var logic MEM22_oe,
    input  var logic MEM22_i,     // MEM22
    output var logic MEM21_o,
    output var logic MEM21_oe,
    input  var logic MEM21_i,     // MEM21
    output var logic MEM20_o,
    output var logic MEM20_oe,
    input  var logic MEM20_i,     // MEM20
    output var logic MEM19_o,
    output var logic MEM19_oe,
    input  var logic MEM19_i,     // MEM19
    output var logic MEM18_o,
    output var logic MEM18_oe,
    input  var logic MEM18_i,     // MEM18
    output var logic MEM17_o,
    output var logic MEM17_oe,
    input  var logic MEM17_i,     // MEM17
    output var logic MEM16_o,
    output var logic MEM16_oe,
    input  var logic MEM16_i,     // MEM16
    output var logic MEM15_o,
    output var logic MEM15_oe,
    input  var logic MEM15_i,     // MEM15
    output var logic MEM14_o,
    output var logic MEM14_oe,
    input  var logic MEM14_i,     // MEM14
    output var logic MEM13_o,
    output var logic MEM13_oe,
    input  var logic MEM13_i,     // MEM13
    output var logic MEM12_o,
    output var logic MEM12_oe,
    input  var logic MEM12_i,     // MEM12
    output var logic MEM11_o,
    output var logic MEM11_oe,
    input  var logic MEM11_i,     // MEM11
    output var logic MEM10_o,
    output var logic MEM10_oe,
    input  var logic MEM10_i,     // MEM10
    output var logic MEM9_o,
    output var logic MEM9_oe,
    input  var logic MEM9_i,      // MEM9
    output var logic MEM8_o,
    output var logic MEM8_oe,
    input  var logic MEM8_i,      // MEM8
    output var logic MEM7_o,
    output var logic MEM7_oe,
    input  var logic MEM7_i,      // MEM7
    output var logic MEM6_o,
    output var logic MEM6_oe,
    input  var logic MEM6_i,      // MEM6
    output var logic MEM5_o,
    output var logic MEM5_oe,
    input  var logic MEM5_i,      // MEM5
    output var logic MEM4_o,
    output var logic MEM4_oe,
    input  var logic MEM4_i,      // MEM4
    output var logic MEM3_o,
    output var logic MEM3_oe,
    input  var logic MEM3_i,      // MEM3
    output var logic MEM2_o,
    output var logic MEM2_oe,
    input  var logic MEM2_i,      // MEM2
    output var logic MEM1_o,
    output var logic MEM1_oe,
    input  var logic MEM1_i,      // MEM1
    output var logic MEM0_o,
    output var logic MEM0_oe,
    input  var logic MEM0_i,      // MEM0
    input  var logic MEMPAR_IN,   // MEMPAR IN
    output var logic n_ADRPAR,    // -ADRPAR
    output var logic n_PMA21,     // -PMA21
    output var logic n_PMA20,     // -PMA20
    output var logic n_PMA19,     // -PMA19
    output var logic n_PMA18,     // -PMA18
    output var logic n_PMA17,     // -PMA17
    output var logic n_PMA16,     // -PMA16
    output var logic n_PMA15,     // -PMA15
    output var logic n_PMA14,     // -PMA14
    output var logic n_PMA13,     // -PMA13
    output var logic n_PMA12,     // -PMA12
    output var logic n_PMA11,     // -PMA11
    output var logic n_PMA10,     // -PMA10
    output var logic n_PMA9,      // -PMA9
    output var logic n_PMA8,      // -PMA8
    output var logic n_VMA7,      // -VMA7
    output var logic n_VMA6,      // -VMA6
    output var logic n_VMA5,      // -VMA5
    output var logic n_VMA4,      // -VMA4
    output var logic n_VMA3,      // -VMA3
    output var logic n_VMA2,      // -VMA2
    output var logic n_VMA1,      // -VMA1
    output var logic n_VMA0,      // -VMA0
    output var logic n_MEMRQ,     // -MEMRQ
    input  var logic n_MEMACK,    // -MEMACK
    input  var logic n_LOADMD,    // -LOADMD
    input  var logic n_IGNPAR,    // -IGNPAR
    output var logic SPY0_o,
    output var logic SPY0_oe,
    input  var logic SPY0_i,      // SPY0
    output var logic SPY1_o,
    output var logic SPY1_oe,
    input  var logic SPY1_i,      // SPY1
    output var logic SPY2_o,
    output var logic SPY2_oe,
    input  var logic SPY2_i,      // SPY2
    output var logic SPY3_o,
    output var logic SPY3_oe,
    input  var logic SPY3_i,      // SPY3
    output var logic SPY4_o,
    output var logic SPY4_oe,
    input  var logic SPY4_i,      // SPY4
    output var logic SPY5_o,
    output var logic SPY5_oe,
    input  var logic SPY5_i,      // SPY5
    output var logic SPY6_o,
    output var logic SPY6_oe,
    input  var logic SPY6_i,      // SPY6
    output var logic SPY7_o,
    output var logic SPY7_oe,
    input  var logic SPY7_i,      // SPY7
    output var logic SPY8_o,
    output var logic SPY8_oe,
    input  var logic SPY8_i,      // SPY8
    output var logic SPY9_o,
    output var logic SPY9_oe,
    input  var logic SPY9_i,      // SPY9
    output var logic SPY10_o,
    output var logic SPY10_oe,
    input  var logic SPY10_i,     // SPY10
    output var logic SPY11_o,
    output var logic SPY11_oe,
    input  var logic SPY11_i,     // SPY11
    output var logic SPY12_o,
    output var logic SPY12_oe,
    input  var logic SPY12_i,     // SPY12
    output var logic SPY13_o,
    output var logic SPY13_oe,
    input  var logic SPY13_i,     // SPY13
    output var logic SPY14_o,
    output var logic SPY14_oe,
    input  var logic SPY14_i,     // SPY14
    output var logic SPY15_o,
    output var logic SPY15_oe,
    input  var logic SPY15_i,     // SPY15
    input  var logic n_MEMGRANT,  // -MEMGRANT
    output var logic WRCYC,       // WRCYC
    input  var logic INT,         // INT
    output var logic MEMPAR_OUT,  // MEMPAR OUT
    output var logic MCLK7,       // MCLK7
    input  var logic EADR0,       // EADR0
    input  var logic EADR1,       // EADR1
    input  var logic EADR2,       // EADR2
    input  var logic EADR3,       // EADR3
    input  var logic n_DBREAD,    // -DBREAD
    input  var logic n_DBWRITE,   // -DBWRITE
    input  var logic n_BUSINT_LM_RESET,// -BUSINT.LM.RESET
    input  var logic n_BOOT1,     // -BOOT1 (neither board drives it)
    output var logic n_BUS_RESET, // -BUS.RESET
    input  var logic LM_DRIVE_ENB,// LM DRIVE ENB
    output var logic n_BUS_POWER_RESET// -BUS.POWER.RESET
