# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Write `boards/cora-z7-07s/cadr_ps7.sv`, the Cora Z7-07S's processing-system
# wrapper, out of the same parse of the same `PS7.v` the Arty Z7-20's wrapper
# comes from.
#
#     python3 boards/cora-z7-07s/vivado/gen_ps7.py            # write the file
#     python3 boards/cora-z7-07s/vivado/gen_ps7.py --check    # is it current?
#
# THIS IS A FRONT END AND NOT A SECOND GENERATOR. It loads
# `boards/arty-z7-20/vivado/gen_ps7.py` as a module and calls that file's own
# `parse_ps7` and `wrapper`. The parse of the 620-pin port list, the table of
# inputs tied to a stated value, and the reasons written beside each of them
# are hard-won and there is one copy of them. A copy in this directory would
# be a second description of the same hard block, and the two would drift.
#
# WHAT DIFFERS ON THIS BOARD IS ONE PORT. The Cora Z7-07S has no HDMI
# connector, so there is no display output on it and nothing masters
# `S_AXI_HP3`. The pins of that port are therefore dropped from the exposed
# set and fall through to the wrapper's "every other input, tied low" arm.
# Leaving them exposed would be worse than untidy: an exposed PS7 pin the top
# level does not connect is a Verilator PINMISSING that stops the board's own
# lint, so the exposed set and the top level are one change.
#
# The other four ports are the Arty's: `S_AXI_HP0` for the machine's main
# memory, `S_AXI_HP2` for the disk's pack, `M_AXI_GP0` for the disk's,
# Chaosnet's, the serial line's and the input face's registers, `M_AXI_GP1`
# for the console and the debug cable, the EMIO GPIO the memory tally is read
# on, and `IRQ_F2P`.
#
# THERE IS NO STUB TO WRITE. `tb/cadr_ps7_stub.sv` is the Arty's generator's
# other output and it names every one of the 620 pins, so it stands in for
# this wrapper as well as for that one.
#
# WITHOUT VIVADO IT SKIPS AND SAYS SO, exactly as the Arty's does: the
# committed file is what `make current` compares against, and a check that
# cannot run must say it did not run rather than fail.

import argparse
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))

ARTY = os.path.join(REPO, "boards", "arty-z7-20", "vivado", "gen_ps7.py")
RTL = os.path.join(REPO, "boards", "cora-z7-07s", "cadr_ps7.sv")

# The two lines the Arty's `wrapper()` writes into its header, and what they
# have to say in a file this script wrote. Replaced by exact text and asserted
# to occur once, so a reworded header upstream stops this rather than leaving
# a generated file pointing at the wrong script and the wrong `make` target.
FROM = ("// GENERATED by boards/arty-z7-20/vivado/gen_ps7.py from"
        " $XILINX_VIVADO's own PS7.v.\n"
        "// Do not edit; run `make ps7`.")
TO = ("// GENERATED by boards/cora-z7-07s/vivado/gen_ps7.py from"
      " $XILINX_VIVADO's own PS7.v,\n"
      "// which calls boards/arty-z7-20/vivado/gen_ps7.py to do the parse.\n"
      "// Do not edit; run `make ps7-cora`.\n"
      "//\n"
      "// This is the Cora Z7-07S's wrapper and it differs from the Arty\n"
      "// Z7-20's in one thing: `S_AXI_HP3` is not brought out, because this\n"
      "// board has no HDMI connector and so no display output to master it.")


def die(msg):
    sys.stderr.write("ps7-cora: %s\n" % msg)
    sys.exit(1)


def load_arty():
    spec = importlib.util.spec_from_file_location("cadr_gen_ps7_arty", ARTY)
    if spec is None or spec.loader is None:
        die("%s cannot be loaded" % os.path.relpath(ARTY, REPO))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def cora_wrapper(mod, ports):
    """The Arty's wrapper with `S_AXI_HP3` demoted to a tied-low input."""
    dropped = [p for p in mod.EXPOSED if p.startswith("SAXIHP3")]
    if not dropped:
        die("%s exposes no S_AXI_HP3 pins --- this front end has nothing to "
            "drop and is describing a wrapper that no longer exists"
            % os.path.relpath(ARTY, REPO))
    mod.EXPOSED = [p for p in mod.EXPOSED if not p.startswith("SAXIHP3")]
    # And the same for the two tables of reasons: a port with no master is
    # not a port whose cache bits mean anything, so those inputs take the
    # wrapper's plain tie-low arm with every other unused input.
    mod.TIED = dict((k, v) for k, v in mod.TIED.items()
                    if not k.startswith("SAXIHP3"))
    mod.WHY_ZERO = dict((k, v) for k, v in mod.WHY_ZERO.items()
                        if not k.startswith("SAXIHP3"))

    text = mod.wrapper(ports)
    if text.count(FROM) != 1:
        die("the generated header is not the one this front end knows how to "
            "relabel; read %s's `wrapper()` and settle it there"
            % os.path.relpath(ARTY, REPO))
    return text.replace(FROM, TO)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare the committed file with what this writes")
    args = ap.parse_args()

    root = os.environ.get("XILINX_VIVADO")
    src = (os.path.join(root, "data", "verilog", "src", "unisims", "PS7.v")
           if root else None)
    if not src or not os.path.exists(src):
        print("ps7-cora: skipped --- $XILINX_VIVADO/data/verilog/src/unisims/"
              "PS7.v is not here")
        return 0

    mod = load_arty()
    ports = mod.parse_ps7(src)
    counts = {}
    for _, direction, _ in ports:
        counts[direction] = counts.get(direction, 0) + 1
    if counts != mod.WANT:
        die("%s has %s, wanting %s --- this is not the port list the wrapper "
            "was written against" % (src, counts, mod.WANT))

    text = cora_wrapper(mod, ports)

    if args.check:
        try:
            with open(RTL) as f:
                have = f.read()
        except IOError:
            die("%s is missing: run `make ps7-cora` and commit it"
                % os.path.relpath(RTL, REPO))
        if have != text:
            die("%s is not what the generator writes today: run `make ps7-cora`"
                % os.path.relpath(RTL, REPO))
        print("ok: boards/cora-z7-07s/cadr_ps7.sv is current (%d PS7 pins)"
              % len(ports))
        return 0

    with open(RTL, "w") as f:
        f.write(text)
    print("ps7-cora: wrote %s" % os.path.relpath(RTL, REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
