// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by `keymap_from_muir.py`.  DO NOT EDIT: edit muir's own
// `src/terminal/keyboard.rs` or `src/terminal/default.keys` and run the
// generator again, which is the point of it --- the two machines must not
// disagree about what a key means, and a table typed out by hand is a
// table that drifts.
//
// muir ff5de42dafed65c1b39a33a1834802c47079d197
//
// `KEY_TABLE` is MIT's own key table by position in octal,
// `keyboard.rs`'s `TABLE`, itself transcribed there from
// `KBD-MAKE-NEW-TABLE` in `lmio/kbd.123`.  `KEY_BOUND` and `KEY_PREFIX`
// are `default.keys` resolved: every `key` and `prefix` line with its
// name looked up exactly as `key_of` looks it up, so a binding is a
// position and a plane and no name survives into C.
//
// THE OTHER THREE ARE FOR `--keyboard-mapping`, which resolves names at
// RUN time and so needs in C what the four above threw away.
// `KEY_SYM_NAMES` is `keyboard.rs`'s `KEYSYM_NAMES` in its own order,
// `KEY_SHIFT_NAMES` is `shift_name` as a table, and
// `KEY_DEFAULT_MAPPING` is `default.keys` itself, the text muir's
// `include_str!` compiles in.
//
// **`KEY_DEFAULT_MAPPING` IS THE CHECK'S REFERENCE AND NOT THE
// PROGRAM'S BUILT-IN MAP.**  muir builds its own map by parsing that
// text; this program's built-in map is `KEY_BOUND` and `KEY_PREFIX`
// above, resolved here in Python.  Keeping them apart is what makes
// the comparison worth making: the check parses the text with the C
// parser and requires the result to equal the tables, so two
// independent resolutions of one reference file are held to each
// other.  A program that parsed the text to build its own map would
// be compared against itself.

#ifndef INPUT_KEYMAP_H
#define INPUT_KEYMAP_H

#include <stdint.h>

enum key_kind { KEY_NONE = 0, KEY_CHAR = 1, KEY_NAMED = 2, KEY_SHIFT = 3 };

// `keyboard.rs`'s `Shift`, in `KBD-SHIFTS`' own order, which is also the
// bit order of the all-keys-up word.
#define SH_SHIFT       0   /* Shift */
#define SH_GREEK       1   /* Greek */
#define SH_TOP         2   /* Top */
#define SH_CAPSLOCK    3   /* Caps Lock */
#define SH_CONTROL     4   /* Control */
#define SH_META        5   /* Meta */
#define SH_SUPER       6   /* Super */
#define SH_HYPER       7   /* Hyper */
#define SH_ALTLOCK     8   /* Alt Lock */
#define SH_MODELOCK    9   /* Mode Lock */
#define SH_REPEAT     10   /* Repeat */

struct key_entry {
	uint8_t kind;        /* enum key_kind */
	uint8_t plain;       /* KEY_CHAR: plane 0 */
	uint8_t shifted;     /* KEY_CHAR: plane 1 */
	uint8_t shift;       /* KEY_SHIFT: which shifting key */
	const char *name;    /* KEY_NAMED: MIT's own name */
};

static const struct key_entry KEY_TABLE[128] = {
	[0000] = { KEY_NONE,   0,   0,  0, 0 },
	[0001] = { KEY_NAMED,   0,   0,  0, "Roman II" },  /* 0o001  Roman II */
	[0002] = { KEY_NAMED,   0,   0,  0, "Roman IV" },  /* 0o002  Roman IV */
	[0003] = { KEY_SHIFT,   0,   0,  9, 0 },  /* 0o003  Mode Lock */
	[0004] = { KEY_NONE,   0,   0,  0, 0 },
	[0005] = { KEY_SHIFT,   0,   0,  6, 0 },  /* 0o005  Super */
	[0006] = { KEY_NONE,   0,   0,  0, 0 },
	[0007] = { KEY_NONE,   0,   0,  0, 0 },
	[0010] = { KEY_NONE,   0,   0,  0, 0 },
	[0011] = { KEY_CHAR,  52,  36,  0, 0 },  /* 0o011  '4' '$' */
	[0012] = { KEY_CHAR, 114,  82,  0, 0 },  /* 0o012  'r' 'R' */
	[0013] = { KEY_CHAR, 102,  70,  0, 0 },  /* 0o013  'f' 'F' */
	[0014] = { KEY_CHAR, 118,  86,  0, 0 },  /* 0o014  'v' 'V' */
	[0015] = { KEY_SHIFT,   0,   0,  8, 0 },  /* 0o015  Alt Lock */
	[0016] = { KEY_NONE,   0,   0,  0, 0 },
	[0017] = { KEY_NAMED,   0,   0,  0, "Hand Right" },  /* 0o017  Hand Right */
	[0020] = { KEY_SHIFT,   0,   0,  4, 0 },  /* 0o020  Control */
	[0021] = { KEY_NONE,   0,   0,  0, 0 },
	[0022] = { KEY_NAMED,   0,   0,  0, "Tab" },  /* 0o022  Tab */
	[0023] = { KEY_NAMED,   0,   0,  0, "Rubout" },  /* 0o023  Rubout */
	[0024] = { KEY_SHIFT,   0,   0,  0, 0 },  /* 0o024  Shift */
	[0025] = { KEY_SHIFT,   0,   0,  0, 0 },  /* 0o025  Shift */
	[0026] = { KEY_SHIFT,   0,   0,  4, 0 },  /* 0o026  Control */
	[0027] = { KEY_NONE,   0,   0,  0, 0 },
	[0030] = { KEY_NAMED,   0,   0,  0, "Hold Output" },  /* 0o030  Hold Output */
	[0031] = { KEY_CHAR,  56,  42,  0, 0 },  /* 0o031  '8' '*' */
	[0032] = { KEY_CHAR, 105,  73,  0, 0 },  /* 0o032  'i' 'I' */
	[0033] = { KEY_CHAR, 107,  75,  0, 0 },  /* 0o033  'k' 'K' */
	[0034] = { KEY_CHAR,  44,  60,  0, 0 },  /* 0o034  ',' '<' */
	[0035] = { KEY_SHIFT,   0,   0,  1, 0 },  /* 0o035  Greek */
	[0036] = { KEY_NAMED,   0,   0,  0, "Line" },  /* 0o036  Line */
	[0037] = { KEY_CHAR,  92, 124,  0, 0 },  /* 0o037  '\\' '|' */
	[0040] = { KEY_NAMED,   0,   0,  0, "Terminal" },  /* 0o040  Terminal */
	[0041] = { KEY_NONE,   0,   0,  0, 0 },
	[0042] = { KEY_NAMED,   0,   0,  0, "Network" },  /* 0o042  Network */
	[0043] = { KEY_NONE,   0,   0,  0, 0 },
	[0044] = { KEY_SHIFT,   0,   0,  1, 0 },  /* 0o044  Greek */
	[0045] = { KEY_SHIFT,   0,   0,  5, 0 },  /* 0o045  Meta */
	[0046] = { KEY_NAMED,   0,   0,  0, "Status" },  /* 0o046  Status */
	[0047] = { KEY_NAMED,   0,   0,  0, "Resume" },  /* 0o047  Resume */
	[0050] = { KEY_NAMED,   0,   0,  0, "Clear Screen" },  /* 0o050  Clear Screen */
	[0051] = { KEY_CHAR,  54,  94,  0, 0 },  /* 0o051  '6' '^' */
	[0052] = { KEY_CHAR, 121,  89,  0, 0 },  /* 0o052  'y' 'Y' */
	[0053] = { KEY_CHAR, 104,  72,  0, 0 },  /* 0o053  'h' 'H' */
	[0054] = { KEY_CHAR, 110,  78,  0, 0 },  /* 0o054  'n' 'N' */
	[0055] = { KEY_NONE,   0,   0,  0, 0 },
	[0056] = { KEY_NONE,   0,   0,  0, 0 },
	[0057] = { KEY_NONE,   0,   0,  0, 0 },
	[0060] = { KEY_NONE,   0,   0,  0, 0 },
	[0061] = { KEY_CHAR,  50,  64,  0, 0 },  /* 0o061  '2' '@' */
	[0062] = { KEY_CHAR, 119,  87,  0, 0 },  /* 0o062  'w' 'W' */
	[0063] = { KEY_CHAR, 115,  83,  0, 0 },  /* 0o063  's' 'S' */
	[0064] = { KEY_CHAR, 120,  88,  0, 0 },  /* 0o064  'x' 'X' */
	[0065] = { KEY_SHIFT,   0,   0,  6, 0 },  /* 0o065  Super */
	[0066] = { KEY_NONE,   0,   0,  0, 0 },
	[0067] = { KEY_NAMED,   0,   0,  0, "Abort" },  /* 0o067  Abort */
	[0070] = { KEY_NONE,   0,   0,  0, 0 },
	[0071] = { KEY_CHAR,  57,  40,  0, 0 },  /* 0o071  '9' '(' */
	[0072] = { KEY_CHAR, 111,  79,  0, 0 },  /* 0o072  'o' 'O' */
	[0073] = { KEY_CHAR, 108,  76,  0, 0 },  /* 0o073  'l' 'L' */
	[0074] = { KEY_CHAR,  46,  62,  0, 0 },  /* 0o074  '.' '>' */
	[0075] = { KEY_NONE,   0,   0,  0, 0 },
	[0076] = { KEY_NONE,   0,   0,  0, 0 },
	[0077] = { KEY_CHAR,  96, 126,  0, 0 },  /* 0o077  '`' '~' */
	[0100] = { KEY_NAMED,   0,   0,  0, "Macro" },  /* 0o100  Macro */
	[0101] = { KEY_NAMED,   0,   0,  0, "Roman I" },  /* 0o101  Roman I */
	[0102] = { KEY_NAMED,   0,   0,  0, "Roman III" },  /* 0o102  Roman III */
	[0103] = { KEY_NONE,   0,   0,  0, 0 },
	[0104] = { KEY_SHIFT,   0,   0,  2, 0 },  /* 0o104  Top */
	[0105] = { KEY_NONE,   0,   0,  0, 0 },
	[0106] = { KEY_NAMED,   0,   0,  0, "Up Thumb" },  /* 0o106  Up Thumb */
	[0107] = { KEY_NAMED,   0,   0,  0, "Call" },  /* 0o107  Call */
	[0110] = { KEY_NAMED,   0,   0,  0, "Clear Input" },  /* 0o110  Clear Input */
	[0111] = { KEY_CHAR,  53,  37,  0, 0 },  /* 0o111  '5' '%' */
	[0112] = { KEY_CHAR, 116,  84,  0, 0 },  /* 0o112  't' 'T' */
	[0113] = { KEY_CHAR, 103,  71,  0, 0 },  /* 0o113  'g' 'G' */
	[0114] = { KEY_CHAR,  98,  66,  0, 0 },  /* 0o114  'b' 'B' */
	[0115] = { KEY_SHIFT,   0,   0, 10, 0 },  /* 0o115  Repeat */
	[0116] = { KEY_NAMED,   0,   0,  0, "Help" },  /* 0o116  Help */
	[0117] = { KEY_NAMED,   0,   0,  0, "Hand Left" },  /* 0o117  Hand Left */
	[0120] = { KEY_NAMED,   0,   0,  0, "Quote" },  /* 0o120  Quote */
	[0121] = { KEY_CHAR,  49,  33,  0, 0 },  /* 0o121  '1' '!' */
	[0122] = { KEY_CHAR, 113,  81,  0, 0 },  /* 0o122  'q' 'Q' */
	[0123] = { KEY_CHAR,  97,  65,  0, 0 },  /* 0o123  'a' 'A' */
	[0124] = { KEY_CHAR, 122,  90,  0, 0 },  /* 0o124  'z' 'Z' */
	[0125] = { KEY_SHIFT,   0,   0,  3, 0 },  /* 0o125  Caps Lock */
	[0126] = { KEY_CHAR,  61,  43,  0, 0 },  /* 0o126  '=' '+' */
	[0127] = { KEY_NONE,   0,   0,  0, 0 },
	[0130] = { KEY_NONE,   0,   0,  0, 0 },
	[0131] = { KEY_CHAR,  45,  95,  0, 0 },  /* 0o131  '-' '_' */
	[0132] = { KEY_CHAR,  40,  91,  0, 0 },  /* 0o132  '(' '[' */
	[0133] = { KEY_CHAR,  39,  34,  0, 0 },  /* 0o133  "'" '"' */
	[0134] = { KEY_CHAR,  32,  32,  0, 0 },  /* 0o134  ' ' ' ' */
	[0135] = { KEY_NONE,   0,   0,  0, 0 },
	[0136] = { KEY_NAMED,   0,   0,  0, "Return" },  /* 0o136  Return */
	[0137] = { KEY_CHAR,  41,  93,  0, 0 },  /* 0o137  ')' ']' */
	[0140] = { KEY_NONE,   0,   0,  0, 0 },
	[0141] = { KEY_NAMED,   0,   0,  0, "System" },  /* 0o141  System */
	[0142] = { KEY_NONE,   0,   0,  0, 0 },
	[0143] = { KEY_NAMED,   0,   0,  0, "Alt Mode" },  /* 0o143  Alt Mode */
	[0144] = { KEY_NONE,   0,   0,  0, 0 },
	[0145] = { KEY_SHIFT,   0,   0,  7, 0 },  /* 0o145  Hyper */
	[0146] = { KEY_CHAR, 125, 125,  0, 0 },  /* 0o146  '}' '}' */
	[0147] = { KEY_NONE,   0,   0,  0, 0 },
	[0150] = { KEY_NONE,   0,   0,  0, 0 },
	[0151] = { KEY_CHAR,  55,  38,  0, 0 },  /* 0o151  '7' '&' */
	[0152] = { KEY_CHAR, 117,  85,  0, 0 },  /* 0o152  'u' 'U' */
	[0153] = { KEY_CHAR, 106,  74,  0, 0 },  /* 0o153  'j' 'J' */
	[0154] = { KEY_CHAR, 109,  77,  0, 0 },  /* 0o154  'm' 'M' */
	[0155] = { KEY_SHIFT,   0,   0,  2, 0 },  /* 0o155  Top */
	[0156] = { KEY_NAMED,   0,   0,  0, "End" },  /* 0o156  End */
	[0157] = { KEY_NAMED,   0,   0,  0, "Delete" },  /* 0o157  Delete */
	[0160] = { KEY_NAMED,   0,   0,  0, "Overstrike" },  /* 0o160  Overstrike */
	[0161] = { KEY_CHAR,  51,  35,  0, 0 },  /* 0o161  '3' '#' */
	[0162] = { KEY_CHAR, 101,  69,  0, 0 },  /* 0o162  'e' 'E' */
	[0163] = { KEY_CHAR, 100,  68,  0, 0 },  /* 0o163  'd' 'D' */
	[0164] = { KEY_CHAR,  99,  67,  0, 0 },  /* 0o164  'c' 'C' */
	[0165] = { KEY_SHIFT,   0,   0,  5, 0 },  /* 0o165  Meta */
	[0166] = { KEY_CHAR, 123, 123,  0, 0 },  /* 0o166  '{' '{' */
	[0167] = { KEY_NAMED,   0,   0,  0, "Break" },  /* 0o167  Break */
	[0170] = { KEY_NAMED,   0,   0,  0, "Stop Output" },  /* 0o170  Stop Output */
	[0171] = { KEY_CHAR,  48,  41,  0, 0 },  /* 0o171  '0' ')' */
	[0172] = { KEY_CHAR, 112,  80,  0, 0 },  /* 0o172  'p' 'P' */
	[0173] = { KEY_CHAR,  59,  58,  0, 0 },  /* 0o173  ';' ':' */
	[0174] = { KEY_CHAR,  47,  63,  0, 0 },  /* 0o174  '/' '?' */
	[0175] = { KEY_SHIFT,   0,   0,  7, 0 },  /* 0o175  Hyper */
	[0176] = { KEY_NAMED,   0,   0,  0, "Down Thumb" },  /* 0o176  Down Thumb */
	[0177] = { KEY_NONE,   0,   0,  0, 0 },
};

struct key_binding { uint32_t keysym; uint8_t position; uint8_t shifted; };

// `default.keys`' `key` lines, by keysym.
static const struct key_binding KEY_BOUND[] = {
	{ 0x0000fe03u, 0035, 0 },   /* Greek */
	{ 0x0000ff08u, 0023, 0 },   /* Rubout */
	{ 0x0000ff09u, 0022, 0 },   /* Tab */
	{ 0x0000ff0au, 0036, 0 },   /* Line */
	{ 0x0000ff0du, 0136, 0 },   /* Return */
	{ 0x0000ff13u, 0030, 0 },   /* Hold Output */
	{ 0x0000ff1bu, 0143, 0 },   /* Alt Mode */
	{ 0x0000ff57u, 0156, 0 },   /* End */
	{ 0x0000ff67u, 0104, 0 },   /* Top */
	{ 0x0000ff69u, 0067, 0 },   /* Abort */
	{ 0x0000ff6au, 0116, 0 },   /* Help */
	{ 0x0000ff6bu, 0167, 0 },   /* Break */
	{ 0x0000ff8du, 0136, 0 },   /* Return */
	{ 0x0000ffbeu, 0040, 0 },   /* Terminal */
	{ 0x0000ffbfu, 0141, 0 },   /* System */
	{ 0x0000ffc0u, 0042, 0 },   /* Network */
	{ 0x0000ffc1u, 0046, 0 },   /* Status */
	{ 0x0000ffc2u, 0047, 0 },   /* Resume */
	{ 0x0000ffc3u, 0067, 0 },   /* Abort */
	{ 0x0000ffc4u, 0107, 0 },   /* Call */
	{ 0x0000ffc5u, 0116, 0 },   /* Help */
	{ 0x0000ffc6u, 0110, 0 },   /* Clear Input */
	{ 0x0000ffc7u, 0050, 0 },   /* Clear Screen */
	{ 0x0000ffc8u, 0167, 0 },   /* Break */
	{ 0x0000ffc9u, 0120, 0 },   /* Quote */
	{ 0x0000ffe1u, 0024, 0 },   /* Shift */
	{ 0x0000ffe2u, 0025, 0 },   /* Shift */
	{ 0x0000ffe3u, 0020, 0 },   /* Control */
	{ 0x0000ffe4u, 0026, 0 },   /* Control */
	{ 0x0000ffe5u, 0125, 0 },   /* Caps Lock */
	{ 0x0000ffe7u, 0045, 0 },   /* Meta */
	{ 0x0000ffe8u, 0165, 0 },   /* Meta */
	{ 0x0000ffe9u, 0045, 0 },   /* Meta */
	{ 0x0000ffeau, 0165, 0 },   /* Meta */
	{ 0x0000ffebu, 0005, 0 },   /* Super */
	{ 0x0000ffecu, 0065, 0 },   /* Super */
	{ 0x0000ffedu, 0145, 0 },   /* Hyper */
	{ 0x0000ffeeu, 0175, 0 },   /* Hyper */
	{ 0x0000ffffu, 0023, 0 },   /* Rubout */
};
#define KEY_BOUND_COUNT 39

struct key_prefix { uint32_t first, second; uint8_t position; uint8_t shifted; };

// ...and its `prefix` lines: press the first, then the second.
static const struct key_prefix KEY_PREFIX[] = {
	{ 0x0000ff14u, 0x00000031u, 0101, 0 },   /* Roman I */
	{ 0x0000ff14u, 0x00000032u, 0001, 0 },   /* Roman II */
	{ 0x0000ff14u, 0x00000033u, 0102, 0 },   /* Roman III */
	{ 0x0000ff14u, 0x00000034u, 0002, 0 },   /* Roman IV */
	{ 0x0000ff14u, 0x00000061u, 0015, 0 },   /* Alt Lock */
	{ 0x0000ff14u, 0x00000063u, 0125, 0 },   /* Caps Lock */
	{ 0x0000ff14u, 0x00000064u, 0157, 0 },   /* Delete */
	{ 0x0000ff14u, 0x00000065u, 0045, 0 },   /* Meta */
	{ 0x0000ff14u, 0x00000067u, 0035, 0 },   /* Greek */
	{ 0x0000ff14u, 0x00000068u, 0145, 0 },   /* Hyper */
	{ 0x0000ff14u, 0x0000006cu, 0020, 0 },   /* Control */
	{ 0x0000ff14u, 0x0000006du, 0003, 0 },   /* Mode Lock */
	{ 0x0000ff14u, 0x0000006fu, 0160, 0 },   /* Overstrike */
	{ 0x0000ff14u, 0x00000070u, 0170, 0 },   /* Stop Output */
	{ 0x0000ff14u, 0x00000072u, 0115, 0 },   /* Repeat */
	{ 0x0000ff14u, 0x00000073u, 0005, 0 },   /* Super */
	{ 0x0000ff14u, 0x00000074u, 0104, 0 },   /* Top */
	{ 0x0000ff14u, 0x00000078u, 0100, 0 },   /* Macro */
	{ 0x0000ff14u, 0x0000ff51u, 0117, 0 },   /* Hand Left */
	{ 0x0000ff14u, 0x0000ff52u, 0106, 0 },   /* Up Thumb */
	{ 0x0000ff14u, 0x0000ff53u, 0017, 0 },   /* Hand Right */
	{ 0x0000ff14u, 0x0000ff54u, 0176, 0 },   /* Down Thumb */
};
#define KEY_PREFIX_COUNT 22

struct key_sym_name { const char *name; uint32_t keysym; };

// `keyboard.rs`'s `KEYSYM_NAMES`, in its own order: the X11 names a
// mapping file may write a keysym by.  A keysym with no name here is
// still written as a number.
static const struct key_sym_name KEY_SYM_NAMES[] = {
	{ "space", 0x00000020u },
	{ "BackSpace", 0x0000ff08u },
	{ "Tab", 0x0000ff09u },
	{ "Linefeed", 0x0000ff0au },
	{ "Return", 0x0000ff0du },
	{ "Pause", 0x0000ff13u },
	{ "Scroll_Lock", 0x0000ff14u },
	{ "Escape", 0x0000ff1bu },
	{ "Home", 0x0000ff50u },
	{ "Left", 0x0000ff51u },
	{ "Up", 0x0000ff52u },
	{ "Right", 0x0000ff53u },
	{ "Down", 0x0000ff54u },
	{ "Prior", 0x0000ff55u },
	{ "Next", 0x0000ff56u },
	{ "End", 0x0000ff57u },
	{ "Begin", 0x0000ff58u },
	{ "Print", 0x0000ff61u },
	{ "Insert", 0x0000ff63u },
	{ "Menu", 0x0000ff67u },
	{ "Cancel", 0x0000ff69u },
	{ "Help", 0x0000ff6au },
	{ "Break", 0x0000ff6bu },
	{ "Mode_switch", 0x0000ff7eu },
	{ "Num_Lock", 0x0000ff7fu },
	{ "KP_Enter", 0x0000ff8du },
	{ "F1", 0x0000ffbeu },
	{ "F2", 0x0000ffbfu },
	{ "F3", 0x0000ffc0u },
	{ "F4", 0x0000ffc1u },
	{ "F5", 0x0000ffc2u },
	{ "F6", 0x0000ffc3u },
	{ "F7", 0x0000ffc4u },
	{ "F8", 0x0000ffc5u },
	{ "F9", 0x0000ffc6u },
	{ "F10", 0x0000ffc7u },
	{ "F11", 0x0000ffc8u },
	{ "F12", 0x0000ffc9u },
	{ "F13", 0x0000ffcau },
	{ "F14", 0x0000ffcbu },
	{ "F15", 0x0000ffccu },
	{ "Shift_L", 0x0000ffe1u },
	{ "Shift_R", 0x0000ffe2u },
	{ "Control_L", 0x0000ffe3u },
	{ "Control_R", 0x0000ffe4u },
	{ "Caps_Lock", 0x0000ffe5u },
	{ "Meta_L", 0x0000ffe7u },
	{ "Meta_R", 0x0000ffe8u },
	{ "Alt_L", 0x0000ffe9u },
	{ "Alt_R", 0x0000ffeau },
	{ "Super_L", 0x0000ffebu },
	{ "Super_R", 0x0000ffecu },
	{ "Hyper_L", 0x0000ffedu },
	{ "Hyper_R", 0x0000ffeeu },
	{ "ISO_Level3_Shift", 0x0000fe03u },
	{ "Delete", 0x0000ffffu },
};
#define KEY_SYM_NAME_COUNT 56

// `shift_name`, by the Shift number above: what a mapping file calls a
// shifting key, with `Left` or `Right` before it where there are two.
static const char *const KEY_SHIFT_NAMES[] = {
	"Shift",
	"Greek",
	"Top",
	"Caps Lock",
	"Control",
	"Meta",
	"Super",
	"Hyper",
	"Alt Lock",
	"Mode Lock",
	"Repeat",
};
#define KEY_SHIFT_NAME_COUNT 11

// muir's `default.keys` verbatim --- the text its `include_str!`
// compiles in and its built-in mapping is parsed from.  Here it is the
// CHECK's reference and nothing reads it at run time: see the header.
static const char KEY_DEFAULT_MAPPING[] =
	"# muir's built-in keyboard mapping: what a viewer's X11 keysym means on\n"
	"# the Lisp Machine keyboard.  This file is compiled into muir and is the\n"
	"# whole of the default; a file of the same form replaces any line of it.\n"
	"#\n"
	"#   muir --keyboard-mapping <file>\n"
	"#   .muirkeys in the directory muir was run from, or in the home one\n"
	"#\n"
	"# `keys` at muir's prompt prints the mapping a run is using, and\n"
	"# `muir --keyboard-mapping-dump` writes it in this form, to edit.\n"
	"#\n"
	"# Two kinds of line:\n"
	"#\n"
	"#   key    <keysym> <key>            one host key\n"
	"#   prefix <keysym> <keysym> <key>   press the first, then the second\n"
	"#\n"
	"# A keysym is an X11 name from keysymdef.h, a single printable character,\n"
	"# or a number in decimal or 0x hexadecimal.  A key is one of MIT's own\n"
	"# names for a key on the CADR keyboard --- a named key such as `Alt Mode`,\n"
	"# a shifting key such as `Greek`, either of a pair as `Left Control` or\n"
	"# `Right Control` --- or the character a character key gives.\n"
	"#\n"
	"# Nothing binds the letters, digits and punctuation: a printable keysym\n"
	"# no line names is looked for on MIT's own key table by the character it\n"
	"# is, on the unshifted plane and the shifted one both.\n"
	"\n"
	"# The keys a host keyboard has a key for.\n"
	"key Return              Return\n"
	"key KP_Enter            Return\n"
	"key Tab                 Tab\n"
	"key BackSpace           Rubout\n"
	"key Delete              Rubout\n"
	"key Linefeed            Line\n"
	"key Escape              Alt Mode\n"
	"key Help                Help\n"
	"key Break               Break\n"
	"key Cancel              Abort\n"
	"key End                 End\n"
	"key Pause               Hold Output\n"
	"\n"
	"# The CADR has no function keys.  These are twelve of the keys on its top\n"
	"# row that a host keyboard has no name for, and the order is muir's own:\n"
	"# nothing in MIT's sources says it.\n"
	"key F1                  Terminal\n"
	"key F2                  System\n"
	"key F3                  Network\n"
	"key F4                  Status\n"
	"key F5                  Resume\n"
	"key F6                  Abort\n"
	"key F7                  Call\n"
	"key F8                  Help\n"
	"key F9                  Clear Input\n"
	"key F10                 Clear Screen\n"
	"key F11                 Break\n"
	"key F12                 Quote\n"
	"\n"
	"# The shifting keys a viewer sends as modifiers.  A host keyboard's Alt is\n"
	"# where a Lisp Machine's Meta is, and every viewer sends that key as Alt.\n"
	"key Shift_L             Left Shift\n"
	"key Shift_R             Right Shift\n"
	"key Control_L           Left Control\n"
	"key Control_R           Right Control\n"
	"key Meta_L              Left Meta\n"
	"key Alt_L               Left Meta\n"
	"key Meta_R              Right Meta\n"
	"key Alt_R               Right Meta\n"
	"key Super_L             Left Super\n"
	"key Super_R             Right Super\n"
	"key Hyper_L             Left Hyper\n"
	"key Hyper_R             Right Hyper\n"
	"key Caps_Lock           Caps Lock\n"
	"\n"
	"# Greek and Top are how the Lisp Machine character set is entered --- the\n"
	"# Greek letters, the arrows and the mathematical symbols --- and no host\n"
	"# keyboard has a key with either name.  AltGr is the nearest thing a host\n"
	"# has to Greek, being the key that gives the other character set, and the\n"
	"# Menu key, which nothing else wants, is Top.\n"
	"key ISO_Level3_Shift    Left Greek\n"
	"key Menu                Left Top\n"
	"\n"
	"# Everything else, behind a prefix.  There are more keys on this keyboard\n"
	"# than a host has spare, so Scroll Lock sends nothing of its own and the\n"
	"# key after it says which key is meant.  A shifting key reached this way\n"
	"# is held for the one key that follows it, which is what holding Greek and\n"
	"# typing a letter does on the real keyboard; any other key is tapped.\n"
	"#\n"
	"# A Mac keyboard has no Scroll Lock, and a desktop that takes Scroll Lock\n"
	"# for itself leaves none of this reachable.  That is what this file is\n"
	"# for: one line changes the prefix.\n"
	"prefix Scroll_Lock g    Greek\n"
	"prefix Scroll_Lock t    Top\n"
	"prefix Scroll_Lock a    Alt Lock\n"
	"prefix Scroll_Lock m    Mode Lock\n"
	"prefix Scroll_Lock r    Repeat\n"
	"prefix Scroll_Lock c    Caps Lock\n"
	"prefix Scroll_Lock h    Hyper\n"
	"prefix Scroll_Lock e    Meta\n"
	"prefix Scroll_Lock l    Control\n"
	"\n"
	"# Super with them, because booting to a usable listener starts with\n"
	"# Super-B and a desktop environment usually takes the Windows or Command\n"
	"# key before a viewer ever sees it.\n"
	"prefix Scroll_Lock s    Super\n"
	"\n"
	"# The named keys no host key is spare for.  The letters are muir's own\n"
	"# and arbitrary; the four hands and thumbs are on the four arrows, which\n"
	"# is roughly where they sit on the real keyboard.\n"
	"prefix Scroll_Lock d    Delete\n"
	"prefix Scroll_Lock x    Macro\n"
	"prefix Scroll_Lock o    Overstrike\n"
	"prefix Scroll_Lock p    Stop Output\n"
	"prefix Scroll_Lock 1    Roman I\n"
	"prefix Scroll_Lock 2    Roman II\n"
	"prefix Scroll_Lock 3    Roman III\n"
	"prefix Scroll_Lock 4    Roman IV\n"
	"prefix Scroll_Lock Left  Hand Left\n"
	"prefix Scroll_Lock Right Hand Right\n"
	"prefix Scroll_Lock Up    Up Thumb\n"
	"prefix Scroll_Lock Down  Down Thumb\n";

#endif
