// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by `usbkeymap_from_xkb.py`.  DO NOT EDIT: run the generator
// again, which is the point of it --- a table of this size typed out by
// hand has a wrong key in it somewhere, and a wrong key types the wrong
// character on one key in a hundred.
//
// From the X keyboard database on the build host:
//
//     /usr/share/X11/xkb/keycodes/evdev
//     /usr/share/X11/xkb/symbols/pc, /usr/share/X11/xkb/symbols/us and what they include
//     /usr/include/X11/keysymdef.h and /usr/include/X11/XF86keysym.h
//
// The layout is `pc+us`, which is what an X server loads for a plain US
// keyboard --- so this is what a viewer connected to such a keyboard
// would send, and the two sources of keys cannot disagree about what a
// key means.
//
// The six keys symbols/pc calls fake are left out; the generator says why.
//
// `plain` is the keysym with no shift and `shifted` the one with Shift
// held.  A key with one keysym has the same in both.  Which of them a
// key event uses is `usb_keys.c`'s decision and is written there.

#ifndef USB_KEYMAP_H
#define USB_KEYMAP_H

#include <stdint.h>

struct usb_key {
	uint16_t code;		/* the evdev key code */
	uint32_t plain;		/* the keysym with no shift */
	uint32_t shifted;	/* ...and with Shift held */
	uint8_t keypad;		/* on the numeric keypad: Num Lock chooses */
	const char *name;	/* the xkb name of the key, for a message */
};

static const struct usb_key USB_KEYS[] = {
	{   1, 0x0000ff1bu, 0x0000ff1bu, 0, "ESC" },	/* Escape */
	{   2, 0x00000031u, 0x00000021u, 0, "AE01" },	/* 1 exclam */
	{   3, 0x00000032u, 0x00000040u, 0, "AE02" },	/* 2 at */
	{   4, 0x00000033u, 0x00000023u, 0, "AE03" },	/* 3 numbersign */
	{   5, 0x00000034u, 0x00000024u, 0, "AE04" },	/* 4 dollar */
	{   6, 0x00000035u, 0x00000025u, 0, "AE05" },	/* 5 percent */
	{   7, 0x00000036u, 0x0000005eu, 0, "AE06" },	/* 6 asciicircum */
	{   8, 0x00000037u, 0x00000026u, 0, "AE07" },	/* 7 ampersand */
	{   9, 0x00000038u, 0x0000002au, 0, "AE08" },	/* 8 asterisk */
	{  10, 0x00000039u, 0x00000028u, 0, "AE09" },	/* 9 parenleft */
	{  11, 0x00000030u, 0x00000029u, 0, "AE10" },	/* 0 parenright */
	{  12, 0x0000002du, 0x0000005fu, 0, "AE11" },	/* minus underscore */
	{  13, 0x0000003du, 0x0000002bu, 0, "AE12" },	/* equal plus */
	{  14, 0x0000ff08u, 0x0000ff08u, 0, "BKSP" },	/* BackSpace */
	{  15, 0x0000ff09u, 0x0000fe20u, 0, "TAB" },	/* Tab ISO_Left_Tab */
	{  16, 0x00000071u, 0x00000051u, 0, "AD01" },	/* q Q */
	{  17, 0x00000077u, 0x00000057u, 0, "AD02" },	/* w W */
	{  18, 0x00000065u, 0x00000045u, 0, "AD03" },	/* e E */
	{  19, 0x00000072u, 0x00000052u, 0, "AD04" },	/* r R */
	{  20, 0x00000074u, 0x00000054u, 0, "AD05" },	/* t T */
	{  21, 0x00000079u, 0x00000059u, 0, "AD06" },	/* y Y */
	{  22, 0x00000075u, 0x00000055u, 0, "AD07" },	/* u U */
	{  23, 0x00000069u, 0x00000049u, 0, "AD08" },	/* i I */
	{  24, 0x0000006fu, 0x0000004fu, 0, "AD09" },	/* o O */
	{  25, 0x00000070u, 0x00000050u, 0, "AD10" },	/* p P */
	{  26, 0x0000005bu, 0x0000007bu, 0, "AD11" },	/* bracketleft braceleft */
	{  27, 0x0000005du, 0x0000007du, 0, "AD12" },	/* bracketright braceright */
	{  28, 0x0000ff0du, 0x0000ff0du, 0, "RTRN" },	/* Return */
	{  29, 0x0000ffe3u, 0x0000ffe3u, 0, "LCTL" },	/* Control_L */
	{  30, 0x00000061u, 0x00000041u, 0, "AC01" },	/* a A */
	{  31, 0x00000073u, 0x00000053u, 0, "AC02" },	/* s S */
	{  32, 0x00000064u, 0x00000044u, 0, "AC03" },	/* d D */
	{  33, 0x00000066u, 0x00000046u, 0, "AC04" },	/* f F */
	{  34, 0x00000067u, 0x00000047u, 0, "AC05" },	/* g G */
	{  35, 0x00000068u, 0x00000048u, 0, "AC06" },	/* h H */
	{  36, 0x0000006au, 0x0000004au, 0, "AC07" },	/* j J */
	{  37, 0x0000006bu, 0x0000004bu, 0, "AC08" },	/* k K */
	{  38, 0x0000006cu, 0x0000004cu, 0, "AC09" },	/* l L */
	{  39, 0x0000003bu, 0x0000003au, 0, "AC10" },	/* semicolon colon */
	{  40, 0x00000027u, 0x00000022u, 0, "AC11" },	/* apostrophe quotedbl */
	{  41, 0x00000060u, 0x0000007eu, 0, "TLDE" },	/* grave asciitilde */
	{  42, 0x0000ffe1u, 0x0000ffe1u, 0, "LFSH" },	/* Shift_L */
	{  43, 0x0000005cu, 0x0000007cu, 0, "BKSL" },	/* backslash bar */
	{  44, 0x0000007au, 0x0000005au, 0, "AB01" },	/* z Z */
	{  45, 0x00000078u, 0x00000058u, 0, "AB02" },	/* x X */
	{  46, 0x00000063u, 0x00000043u, 0, "AB03" },	/* c C */
	{  47, 0x00000076u, 0x00000056u, 0, "AB04" },	/* v V */
	{  48, 0x00000062u, 0x00000042u, 0, "AB05" },	/* b B */
	{  49, 0x0000006eu, 0x0000004eu, 0, "AB06" },	/* n N */
	{  50, 0x0000006du, 0x0000004du, 0, "AB07" },	/* m M */
	{  51, 0x0000002cu, 0x0000003cu, 0, "AB08" },	/* comma less */
	{  52, 0x0000002eu, 0x0000003eu, 0, "AB09" },	/* period greater */
	{  53, 0x0000002fu, 0x0000003fu, 0, "AB10" },	/* slash question */
	{  54, 0x0000ffe2u, 0x0000ffe2u, 0, "RTSH" },	/* Shift_R */
	{  55, 0x0000ffaau, 0x0000ffaau, 1, "KPMU" },	/* KP_Multiply */
	{  56, 0x0000ffe9u, 0x0000ffe9u, 0, "LALT" },	/* Alt_L */
	{  57, 0x00000020u, 0x00000020u, 0, "SPCE" },	/* space */
	{  58, 0x0000ffe5u, 0x0000ffe5u, 0, "CAPS" },	/* Caps_Lock */
	{  59, 0x0000ffbeu, 0x0000ffbeu, 0, "FK01" },	/* F1 */
	{  60, 0x0000ffbfu, 0x0000ffbfu, 0, "FK02" },	/* F2 */
	{  61, 0x0000ffc0u, 0x0000ffc0u, 0, "FK03" },	/* F3 */
	{  62, 0x0000ffc1u, 0x0000ffc1u, 0, "FK04" },	/* F4 */
	{  63, 0x0000ffc2u, 0x0000ffc2u, 0, "FK05" },	/* F5 */
	{  64, 0x0000ffc3u, 0x0000ffc3u, 0, "FK06" },	/* F6 */
	{  65, 0x0000ffc4u, 0x0000ffc4u, 0, "FK07" },	/* F7 */
	{  66, 0x0000ffc5u, 0x0000ffc5u, 0, "FK08" },	/* F8 */
	{  67, 0x0000ffc6u, 0x0000ffc6u, 0, "FK09" },	/* F9 */
	{  68, 0x0000ffc7u, 0x0000ffc7u, 0, "FK10" },	/* F10 */
	{  69, 0x0000ff7fu, 0x0000ff7fu, 0, "NMLK" },	/* Num_Lock */
	{  70, 0x0000ff14u, 0x0000ff14u, 0, "SCLK" },	/* Scroll_Lock */
	{  71, 0x0000ff95u, 0x0000ffb7u, 1, "KP7" },	/* KP_Home KP_7 */
	{  72, 0x0000ff97u, 0x0000ffb8u, 1, "KP8" },	/* KP_Up KP_8 */
	{  73, 0x0000ff9au, 0x0000ffb9u, 1, "KP9" },	/* KP_Prior KP_9 */
	{  74, 0x0000ffadu, 0x0000ffadu, 1, "KPSU" },	/* KP_Subtract */
	{  75, 0x0000ff96u, 0x0000ffb4u, 1, "KP4" },	/* KP_Left KP_4 */
	{  76, 0x0000ff9du, 0x0000ffb5u, 1, "KP5" },	/* KP_Begin KP_5 */
	{  77, 0x0000ff98u, 0x0000ffb6u, 1, "KP6" },	/* KP_Right KP_6 */
	{  78, 0x0000ffabu, 0x0000ffabu, 1, "KPAD" },	/* KP_Add */
	{  79, 0x0000ff9cu, 0x0000ffb1u, 1, "KP1" },	/* KP_End KP_1 */
	{  80, 0x0000ff99u, 0x0000ffb2u, 1, "KP2" },	/* KP_Down KP_2 */
	{  81, 0x0000ff9bu, 0x0000ffb3u, 1, "KP3" },	/* KP_Next KP_3 */
	{  82, 0x0000ff9eu, 0x0000ffb0u, 1, "KP0" },	/* KP_Insert KP_0 */
	{  83, 0x0000ff9fu, 0x0000ffaeu, 1, "KPDL" },	/* KP_Delete KP_Decimal */
	{  86, 0x0000003cu, 0x0000003eu, 0, "LSGT" },	/* less greater */
	{  87, 0x0000ffc8u, 0x0000ffc8u, 0, "FK11" },	/* F11 */
	{  88, 0x0000ffc9u, 0x0000ffc9u, 0, "FK12" },	/* F12 */
	{  90, 0x0000ff26u, 0x0000ff26u, 0, "KATA" },	/* Katakana */
	{  91, 0x0000ff25u, 0x0000ff25u, 0, "HIRA" },	/* Hiragana */
	{  92, 0x0000ff23u, 0x0000ff23u, 0, "HENK" },	/* Henkan */
	{  93, 0x0000ff27u, 0x0000ff27u, 0, "HKTG" },	/* Hiragana_Katakana */
	{  94, 0x0000ff22u, 0x0000ff22u, 0, "MUHE" },	/* Muhenkan */
	{  96, 0x0000ff8du, 0x0000ff8du, 1, "KPEN" },	/* KP_Enter */
	{  97, 0x0000ffe4u, 0x0000ffe4u, 0, "RCTL" },	/* Control_R */
	{  98, 0x0000ffafu, 0x0000ffafu, 1, "KPDV" },	/* KP_Divide */
	{  99, 0x0000ff61u, 0x0000ff15u, 0, "PRSC" },	/* Print Sys_Req */
	{ 100, 0x0000ffeau, 0x0000ffeau, 0, "RALT" },	/* Alt_R */
	{ 102, 0x0000ff50u, 0x0000ff50u, 0, "HOME" },	/* Home */
	{ 103, 0x0000ff52u, 0x0000ff52u, 0, "UP" },	/* Up */
	{ 104, 0x0000ff55u, 0x0000ff55u, 0, "PGUP" },	/* Prior */
	{ 105, 0x0000ff51u, 0x0000ff51u, 0, "LEFT" },	/* Left */
	{ 106, 0x0000ff53u, 0x0000ff53u, 0, "RGHT" },	/* Right */
	{ 107, 0x0000ff57u, 0x0000ff57u, 0, "END" },	/* End */
	{ 108, 0x0000ff54u, 0x0000ff54u, 0, "DOWN" },	/* Down */
	{ 109, 0x0000ff56u, 0x0000ff56u, 0, "PGDN" },	/* Next */
	{ 110, 0x0000ff63u, 0x0000ff63u, 0, "INS" },	/* Insert */
	{ 111, 0x0000ffffu, 0x0000ffffu, 0, "DELE" },	/* Delete */
	{ 117, 0x0000ffbdu, 0x0000ffbdu, 1, "KPEQ" },	/* KP_Equal */
	{ 119, 0x0000ff13u, 0x0000ff6bu, 0, "PAUS" },	/* Pause Break */
	{ 121, 0x0000ffaeu, 0x0000ffaeu, 1, "KPPT" },	/* KP_Decimal */
	{ 122, 0x0000ff31u, 0x0000ff31u, 0, "HNGL" },	/* Hangul */
	{ 123, 0x0000ff34u, 0x0000ff34u, 0, "HJCV" },	/* Hangul_Hanja */
	{ 125, 0x0000ffebu, 0x0000ffebu, 0, "LWIN" },	/* Super_L */
	{ 126, 0x0000ffecu, 0x0000ffecu, 0, "RWIN" },	/* Super_R */
	{ 127, 0x0000ff67u, 0x0000ff67u, 0, "MENU" },	/* Menu */
	{ 227, 0x1008ff59u, 0x1008ff59u, 0, "OUTP" },	/* XF86Display */
	{ 228, 0x1008ff04u, 0x1008ff04u, 0, "KITG" },	/* XF86KbdLightOnOff */
	{ 229, 0x1008ff06u, 0x1008ff06u, 0, "KIDN" },	/* XF86KbdBrightnessDown */
	{ 230, 0x1008ff05u, 0x1008ff05u, 0, "KIUP" },	/* XF86KbdBrightnessUp */
};

#define USB_KEYS_COUNT (sizeof USB_KEYS / sizeof USB_KEYS[0])

#endif
