# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# GENERATED by boards/arty-a7-100/vivado/mig_check.py from the memory
# controller's own generated constraints.  Do not edit; `make current`
# fails if this is not what that script writes today.
#
# The DDR3L pins on a board with NO memory controller behind them.
#
# **WHY A SECOND FILE AND NOT THE GENERATED ONE.**  The ports are in
# `cadr_arty_a7.sv`'s list whatever `DDR` says --- a port that exists
# in only one configuration is a port list that differs between two
# builds of one file --- so a memory-off board still has to say where
# each one goes and what standard it drives.  What it must NOT say is
# the rest of what the controller's file says: a slew rate, an input
# termination and, for the two clock pins, no buffer at all.  Those
# belong to the physical layer that drives them, and `IO_BUFFER_TYPE
# NONE` on a port driven by ordinary logic is an error rather than a
# warning.
#
# **AND THE DIFFERENTIAL PAIRS BECOME SINGLE-ENDED HERE**, which is
# the one substantive difference.  `DIFF_SSTL135` requires a
# differential buffer, and with no controller there is none: the four
# pins are driven low or let go, and the memory part is held in reset
# by `ddr3_reset_n` regardless.
#
# Read only when the controller is absent; the generated file is read
# in its place when it is present, and it sets these same pins to the
# same places.

set_property -dict { PACKAGE_PIN K5   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[0] }]
set_property -dict { PACKAGE_PIN L3   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[1] }]
set_property -dict { PACKAGE_PIN K3   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[2] }]
set_property -dict { PACKAGE_PIN L6   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[3] }]
set_property -dict { PACKAGE_PIN M3   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[4] }]
set_property -dict { PACKAGE_PIN M1   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[5] }]
set_property -dict { PACKAGE_PIN L4   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[6] }]
set_property -dict { PACKAGE_PIN M2   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[7] }]
set_property -dict { PACKAGE_PIN V4   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[8] }]
set_property -dict { PACKAGE_PIN T5   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[9] }]
set_property -dict { PACKAGE_PIN U4   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[10] }]
set_property -dict { PACKAGE_PIN V5   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[11] }]
set_property -dict { PACKAGE_PIN V1   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[12] }]
set_property -dict { PACKAGE_PIN T3   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[13] }]
set_property -dict { PACKAGE_PIN U3   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[14] }]
set_property -dict { PACKAGE_PIN R3   IOSTANDARD SSTL135 } [get_ports { ddr3_dq[15] }]
set_property -dict { PACKAGE_PIN T8   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[13] }]
set_property -dict { PACKAGE_PIN T6   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[12] }]
set_property -dict { PACKAGE_PIN U6   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[11] }]
set_property -dict { PACKAGE_PIN R6   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[10] }]
set_property -dict { PACKAGE_PIN V7   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[9] }]
set_property -dict { PACKAGE_PIN R8   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[8] }]
set_property -dict { PACKAGE_PIN U7   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[7] }]
set_property -dict { PACKAGE_PIN V6   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[6] }]
set_property -dict { PACKAGE_PIN R7   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[5] }]
set_property -dict { PACKAGE_PIN N6   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[4] }]
set_property -dict { PACKAGE_PIN T1   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[3] }]
set_property -dict { PACKAGE_PIN N4   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[2] }]
set_property -dict { PACKAGE_PIN M6   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[1] }]
set_property -dict { PACKAGE_PIN R2   IOSTANDARD SSTL135 } [get_ports { ddr3_addr[0] }]
set_property -dict { PACKAGE_PIN P2   IOSTANDARD SSTL135 } [get_ports { ddr3_ba[2] }]
set_property -dict { PACKAGE_PIN P4   IOSTANDARD SSTL135 } [get_ports { ddr3_ba[1] }]
set_property -dict { PACKAGE_PIN R1   IOSTANDARD SSTL135 } [get_ports { ddr3_ba[0] }]
set_property -dict { PACKAGE_PIN P3   IOSTANDARD SSTL135 } [get_ports { ddr3_ras_n }]
set_property -dict { PACKAGE_PIN M4   IOSTANDARD SSTL135 } [get_ports { ddr3_cas_n }]
set_property -dict { PACKAGE_PIN P5   IOSTANDARD SSTL135 } [get_ports { ddr3_we_n }]
set_property -dict { PACKAGE_PIN K6   IOSTANDARD SSTL135 } [get_ports { ddr3_reset_n }]
set_property -dict { PACKAGE_PIN N5   IOSTANDARD SSTL135 } [get_ports { ddr3_cke[0] }]
set_property -dict { PACKAGE_PIN R5   IOSTANDARD SSTL135 } [get_ports { ddr3_odt[0] }]
set_property -dict { PACKAGE_PIN U8   IOSTANDARD SSTL135 } [get_ports { ddr3_cs_n[0] }]
set_property -dict { PACKAGE_PIN L1   IOSTANDARD SSTL135 } [get_ports { ddr3_dm[0] }]
set_property -dict { PACKAGE_PIN U1   IOSTANDARD SSTL135 } [get_ports { ddr3_dm[1] }]
set_property -dict { PACKAGE_PIN N2   IOSTANDARD SSTL135 } [get_ports { ddr3_dqs_p[0] }]
set_property -dict { PACKAGE_PIN N1   IOSTANDARD SSTL135 } [get_ports { ddr3_dqs_n[0] }]
set_property -dict { PACKAGE_PIN U2   IOSTANDARD SSTL135 } [get_ports { ddr3_dqs_p[1] }]
set_property -dict { PACKAGE_PIN V2   IOSTANDARD SSTL135 } [get_ports { ddr3_dqs_n[1] }]
set_property -dict { PACKAGE_PIN U9   IOSTANDARD SSTL135 } [get_ports { ddr3_ck_p[0] }]
set_property -dict { PACKAGE_PIN V9   IOSTANDARD SSTL135 } [get_ports { ddr3_ck_n[0] }]

# The bank's reference, which the inputs on it need whatever
# is driving them.
set_property INTERNAL_VREF 0.675 [get_iobanks 34]
