// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The fault bitstream for the DE25-Nano: no machine, every lamp blinking.
//
// **WHAT IT IS FOR.**  U-Boot loads it when the CADR's own core image could
// not be fetched or loaded (`cadr_fault` in the board's U-Boot environment),
// so that a board whose card is wrong says so at a glance rather than on a
// serial console nobody is watching.  `docs/board.md` says when it is loaded
// and what to check.
//
// **WHAT IT DOES.**  All eight lamps, LEDR0 to LEDR7, blink together, two
// flashes a second.  They are single green LEDs lit when their pin is driven
// LOW, so the one lamp register (`rtl/plumbing/cadr_fault_lamp.sv`) is
// inverted at the pins, all eight from the same bit.
//
// **AND WHAT IT KEEPS, WHICH IS THE PROCESSOR'S SIDE OF THE BOARD.**  The
// processor system is the CADR build's own, `cadr_de25_hps`, generated by
// `boards/de25-nano/quartus/hps.tcl` with the same LPDDR4, the same pins and
// the same three bridges, so that Linux boots and runs under this fabric
// exactly as it does under the CADR's.  Every address of both
// processor-to-fabric bridges is answered by the default slave
// (`rtl/plumbing/cadr_gp0_default.sv`), whole: a read returns "FALT" in every
// beat and a write is taken and dropped, because a read nothing answers may
// hang the processor as it does on the Zynq boards.  The FPGA-to-SDRAM bridge
// is never used: its master drives no valid and takes every response.
//
// **THE WARM-RESET HANDSHAKE IS ANSWERED AS THE CADR's BUILD ANSWERS IT**, by
// `rtl/plumbing/cadr_f2sdram_gate.sv` itself, with its share reported idle
// because there is no share.  U-Boot's `bridge enable` raises the request
// and waits for the acknowledgment, so a fabric that never gave it would
// leave the bridges in reset.  `h2f_gp_out` is read by the gate and nowhere
// else: the memory gate has nothing behind it here, and U-Boot leaves it shut.
//
// **IT SAYS WHAT IT IS.**  `h2f_gp_in`, the tally every program reads first
// through the system manager's GPI, reads "FALT" whichever half
// `h2f_gp_out[1]` selects.  That fails the tally's marker test, so every
// program refuses the fabric, and it is a value the init scripts recognize as
// this bitstream.  The build stamp in USERCODE marks it too
// (`tools/build_stamp.tcl`).
//
// `tb/cadr_fault_tb.cpp` simulates this file with the processor of
// `tb/cadr_de25_hps_sim.sv`, and holds all of the above.

`default_nettype none

module cadr_de25_fault #(
    // The lamps' half period in ticks: 250 ms at the fabric's 100 MHz.
    parameter int unsigned HALF_T = 25_000_000
) (
    input  var logic       clock50_0,
    // `KEY[1:0]`, low while pressed; KEY1 resets the fabric's lamp and gate.
    input  var logic [1:0] btn,
    // `SW[3:0]`, which this design does not read.
    input  var logic [3:0] sw,
    // `LEDR[7:0]`, lit when driven low.
    output var logic [7:0] led,
    // The debug cable's eight pads on JP1, left to their pull-downs.
    inout  wire  logic     jp1_pin31,
    inout  wire  logic     jp1_pin32,
    inout  wire  logic     jp1_pin33,
    inout  wire  logic     jp1_pin34,
    inout  wire  logic     jp1_pin35,
    inout  wire  logic     jp1_pin36,
    inout  wire  logic     jp1_pin37,
    inout  wire  logic     jp1_pin38,
    // The processor's LPDDR4 bank, LPDDR4A, which its memory controller
    // drives.  The names are the pin file's, which are the manual's; the
    // controller's own names for each are beside the connection below.
    output var logic [5:0]  lpddr4a_ca,
    output var logic        lpddr4a_cs_n,
    output var logic        lpddr4a_cke,
    output var logic        lpddr4a_ck,
    output var logic        lpddr4a_ck_n,
    inout  wire  logic [31:0] lpddr4a_dq,
    inout  wire  logic [3:0]  lpddr4a_dqs,
    inout  wire  logic [3:0]  lpddr4a_dqs_n,
    inout  wire  logic [3:0]  lpddr4a_dm,
    output var logic        lpddr4a_reset_n,
    input  var logic        lpddr4a_rzq,
    input  var logic        lpddr4a_refclk_p,
    // The processor's own pins: its 25 MHz clock and the peripherals of the
    // manual's section 3.8, as `boards/de25-nano/quartus/hps.tcl` muxes them.
    input  var logic        hps_clk_25,
    inout  wire  logic      hps_key,
    inout  wire  logic      hps_led,
    output var logic        hps_enet_tx_clk,
    output var logic        hps_enet_tx_ctl,
    output var logic [3:0]  hps_enet_tx_data,
    input  var logic        hps_enet_rx_clk,
    input  var logic        hps_enet_rx_ctl,
    input  var logic [3:0]  hps_enet_rx_data,
    inout  wire  logic      hps_enet_mdio,
    output var logic        hps_enet_mdc,
    output var logic        hps_uart_tx,
    input  var logic        hps_uart_rx,
    output var logic        hps_sd_clk,
    inout  wire  logic      hps_sd_cmd,
    inout  wire  logic [3:0] hps_sd_data,
    input  var logic        hps_usb_clk,
    output var logic        hps_usb_stp,
    input  var logic        hps_usb_dir,
    input  var logic        hps_usb_nxt,
    inout  wire  logic [7:0] hps_usb_data,
    inout  wire  logic      hps_gsensor_int,
    inout  wire  logic      hps_i2c_scl,
    inout  wire  logic      hps_i2c_sda
);

  // "FALT": the tally and every answer of both bridges.
  localparam logic [31:0] FAULT_WORD = 32'h4641_4C54;

  // ------------------------------------------------------------ the clock
  //
  // The CADR build's own: the Reset Release holds the PLL until the device
  // is in user mode, and the PLL makes 100 MHz from 50.
  logic ninit_done;
  cadr_de25_reset_release u_reset_release (
      .ninit_done(ninit_done)
  );

  logic clk, pll_locked;
  cadr_de25_pll u_pll (
      .refclk  (clock50_0),
      .rst     (ninit_done),
      .outclk_0(clk),
      .locked  (pll_locked)
  );

  // The fabric's reset, for the gate alone: the PLL unlocked or KEY1.
  logic [3:0] rst_sync;
  logic       rst;
  always_ff @(posedge clk) rst_sync <= {rst_sync[2:0], !pll_locked || !btn[1]};
  assign rst = rst_sync[3];

  // ------------------------------------------------------------ the lamps
  logic lit;
  cadr_fault_lamp #(.HALF_T(HALF_T)) u_lamp (.clk(clk), .lit(lit));

  // Lit low, all eight from the one bit.
  assign led = ~{8{lit}};

  // ------------------------------------------------ the processor system
  logic        h2f_reset;
  logic [31:0] gp_out, gp_in;
  logic        warm_req_n, warm_ack_n;

  // `hps2fpga` and `lwhps2fpga`: AXI4, 32 bits, four bits of ID.
  logic [3:0]  h2f_awid, h2f_arid, h2f_bid, h2f_rid;
  logic [29:0] h2f_awaddr, h2f_araddr;
  logic [7:0]  h2f_awlen, h2f_arlen;
  logic [2:0]  h2f_awsize, h2f_arsize, h2f_awprot, h2f_arprot;
  logic [1:0]  h2f_awburst, h2f_arburst, h2f_bresp, h2f_rresp;
  logic        h2f_awlock, h2f_arlock;
  logic [3:0]  h2f_awcache, h2f_arcache, h2f_wstrb;
  logic [31:0] h2f_wdata, h2f_rdata;
  logic        h2f_awvalid, h2f_awready, h2f_wlast, h2f_wvalid, h2f_wready;
  logic        h2f_bvalid, h2f_bready, h2f_arvalid, h2f_arready;
  logic        h2f_rlast, h2f_rvalid, h2f_rready;
  logic [3:0]  lw_awid, lw_arid, lw_bid, lw_rid;
  logic [28:0] lw_awaddr, lw_araddr;
  logic [7:0]  lw_awlen, lw_arlen;
  logic [2:0]  lw_awsize, lw_arsize, lw_awprot, lw_arprot;
  logic [1:0]  lw_awburst, lw_arburst, lw_bresp, lw_rresp;
  logic        lw_awlock, lw_arlock;
  logic [3:0]  lw_awcache, lw_arcache, lw_wstrb;
  logic [31:0] lw_wdata, lw_rdata;
  logic        lw_awvalid, lw_awready, lw_wlast, lw_wvalid, lw_wready;
  logic        lw_bvalid, lw_bready, lw_arvalid, lw_arready;
  logic        lw_rlast, lw_rvalid, lw_rready;

  // `f2sdram`: AXI4, 64 bits, five bits of ID, and nothing uses it.
  logic [4:0]  f2s_awid, f2s_arid, f2s_bid, f2s_rid;
  logic [31:0] f2s_awaddr, f2s_araddr;
  logic [7:0]  f2s_awlen, f2s_arlen, f2s_awuser, f2s_aruser, f2s_wuser;
  logic [7:0]  f2s_buser, f2s_ruser, f2s_wstrb;
  logic [2:0]  f2s_awsize, f2s_arsize, f2s_awprot, f2s_arprot;
  logic [1:0]  f2s_awburst, f2s_arburst, f2s_bresp, f2s_rresp;
  logic        f2s_awlock, f2s_arlock;
  logic [3:0]  f2s_awcache, f2s_arcache, f2s_awqos, f2s_arqos;
  logic [3:0]  f2s_awregion, f2s_arregion;
  logic [63:0] f2s_wdata, f2s_rdata;
  logic        f2s_awvalid, f2s_awready, f2s_wlast, f2s_wvalid, f2s_wready;
  logic        f2s_bvalid, f2s_bready, f2s_arvalid, f2s_arready;
  logic        f2s_rlast, f2s_rvalid, f2s_rready;

  cadr_de25_hps u_hps (
      // LPDDR4A, by the controller's names.
      .emif_mem_0_mem_cs(lpddr4a_cs_n), .emif_mem_0_mem_ca(lpddr4a_ca),
      .emif_mem_0_mem_cke(lpddr4a_cke), .emif_mem_0_mem_dq(lpddr4a_dq),
      .emif_mem_0_mem_dqs_t(lpddr4a_dqs), .emif_mem_0_mem_dqs_c(lpddr4a_dqs_n),
      .emif_mem_0_mem_dmi(lpddr4a_dm),
      .emif_mem_ck_0_mem_ck_t(lpddr4a_ck), .emif_mem_ck_0_mem_ck_c(lpddr4a_ck_n),
      .emif_mem_reset_n_mem_reset_n(lpddr4a_reset_n),
      .emif_oct_0_oct_rzqin(lpddr4a_rzq), .emif_ref_clk_clk(lpddr4a_refclk_p),
      // The processor's pins.
      .hps_hps_io_hps_osc_clk(hps_clk_25),
      .hps_hps_io_sdmmc_data0(hps_sd_data[0]), .hps_hps_io_sdmmc_data1(hps_sd_data[1]),
      .hps_hps_io_sdmmc_cclk(hps_sd_clk),
      .hps_hps_io_sdmmc_data2(hps_sd_data[2]), .hps_hps_io_sdmmc_data3(hps_sd_data[3]),
      .hps_hps_io_sdmmc_cmd(hps_sd_cmd),
      .hps_hps_io_usb0_clk(hps_usb_clk), .hps_hps_io_usb0_stp(hps_usb_stp),
      .hps_hps_io_usb0_dir(hps_usb_dir),
      .hps_hps_io_usb0_data0(hps_usb_data[0]), .hps_hps_io_usb0_data1(hps_usb_data[1]),
      .hps_hps_io_usb0_nxt(hps_usb_nxt),
      .hps_hps_io_usb0_data2(hps_usb_data[2]), .hps_hps_io_usb0_data3(hps_usb_data[3]),
      .hps_hps_io_usb0_data4(hps_usb_data[4]), .hps_hps_io_usb0_data5(hps_usb_data[5]),
      .hps_hps_io_usb0_data6(hps_usb_data[6]), .hps_hps_io_usb0_data7(hps_usb_data[7]),
      .hps_hps_io_emac0_tx_clk(hps_enet_tx_clk), .hps_hps_io_emac0_tx_ctl(hps_enet_tx_ctl),
      .hps_hps_io_emac0_rx_clk(hps_enet_rx_clk), .hps_hps_io_emac0_rx_ctl(hps_enet_rx_ctl),
      .hps_hps_io_emac0_txd0(hps_enet_tx_data[0]), .hps_hps_io_emac0_txd1(hps_enet_tx_data[1]),
      .hps_hps_io_emac0_rxd0(hps_enet_rx_data[0]), .hps_hps_io_emac0_rxd1(hps_enet_rx_data[1]),
      .hps_hps_io_emac0_txd2(hps_enet_tx_data[2]), .hps_hps_io_emac0_txd3(hps_enet_tx_data[3]),
      .hps_hps_io_emac0_rxd2(hps_enet_rx_data[2]), .hps_hps_io_emac0_rxd3(hps_enet_rx_data[3]),
      .hps_hps_io_mdio0_mdio(hps_enet_mdio), .hps_hps_io_mdio0_mdc(hps_enet_mdc),
      .hps_hps_io_uart1_tx(hps_uart_tx), .hps_hps_io_uart1_rx(hps_uart_rx),
      .hps_hps_io_i2c1_sda(hps_i2c_sda), .hps_hps_io_i2c1_scl(hps_i2c_scl),
      .hps_hps_io_gpio28(hps_gsensor_int), .hps_hps_io_gpio40(hps_key),
      .hps_hps_io_gpio41(hps_led),
      // Resets and the two general-purpose words.
      .hps_h2f_reset_reset(h2f_reset),
      .hps_hps_gp_gp_in(gp_in), .hps_hps_gp_gp_out(gp_out),
      .hps_h2f_warm_reset_handshake_reset_req(warm_req_n),
      .hps_h2f_warm_reset_handshake_reset_ack(warm_ack_n),
      // The processor-to-fabric bridge.
      .hps_hps2fpga_axi_clock_clk(clk), .hps_hps2fpga_axi_reset_reset(h2f_reset),
      .hps_hps2fpga_awid(h2f_awid), .hps_hps2fpga_awaddr(h2f_awaddr),
      .hps_hps2fpga_awlen(h2f_awlen), .hps_hps2fpga_awsize(h2f_awsize),
      .hps_hps2fpga_awburst(h2f_awburst), .hps_hps2fpga_awlock(h2f_awlock),
      .hps_hps2fpga_awcache(h2f_awcache), .hps_hps2fpga_awprot(h2f_awprot),
      .hps_hps2fpga_awvalid(h2f_awvalid), .hps_hps2fpga_awready(h2f_awready),
      .hps_hps2fpga_wdata(h2f_wdata), .hps_hps2fpga_wstrb(h2f_wstrb),
      .hps_hps2fpga_wlast(h2f_wlast), .hps_hps2fpga_wvalid(h2f_wvalid),
      .hps_hps2fpga_wready(h2f_wready),
      .hps_hps2fpga_bid(h2f_bid), .hps_hps2fpga_bresp(h2f_bresp),
      .hps_hps2fpga_bvalid(h2f_bvalid), .hps_hps2fpga_bready(h2f_bready),
      .hps_hps2fpga_arid(h2f_arid), .hps_hps2fpga_araddr(h2f_araddr),
      .hps_hps2fpga_arlen(h2f_arlen), .hps_hps2fpga_arsize(h2f_arsize),
      .hps_hps2fpga_arburst(h2f_arburst), .hps_hps2fpga_arlock(h2f_arlock),
      .hps_hps2fpga_arcache(h2f_arcache), .hps_hps2fpga_arprot(h2f_arprot),
      .hps_hps2fpga_arvalid(h2f_arvalid), .hps_hps2fpga_arready(h2f_arready),
      .hps_hps2fpga_rid(h2f_rid), .hps_hps2fpga_rdata(h2f_rdata),
      .hps_hps2fpga_rresp(h2f_rresp), .hps_hps2fpga_rlast(h2f_rlast),
      .hps_hps2fpga_rvalid(h2f_rvalid), .hps_hps2fpga_rready(h2f_rready),
      // The lightweight bridge.
      .hps_lwhps2fpga_axi_clock_clk(clk), .hps_lwhps2fpga_axi_reset_reset(h2f_reset),
      .hps_lwhps2fpga_awid(lw_awid), .hps_lwhps2fpga_awaddr(lw_awaddr),
      .hps_lwhps2fpga_awlen(lw_awlen), .hps_lwhps2fpga_awsize(lw_awsize),
      .hps_lwhps2fpga_awburst(lw_awburst), .hps_lwhps2fpga_awlock(lw_awlock),
      .hps_lwhps2fpga_awcache(lw_awcache), .hps_lwhps2fpga_awprot(lw_awprot),
      .hps_lwhps2fpga_awvalid(lw_awvalid), .hps_lwhps2fpga_awready(lw_awready),
      .hps_lwhps2fpga_wdata(lw_wdata), .hps_lwhps2fpga_wstrb(lw_wstrb),
      .hps_lwhps2fpga_wlast(lw_wlast), .hps_lwhps2fpga_wvalid(lw_wvalid),
      .hps_lwhps2fpga_wready(lw_wready),
      .hps_lwhps2fpga_bid(lw_bid), .hps_lwhps2fpga_bresp(lw_bresp),
      .hps_lwhps2fpga_bvalid(lw_bvalid), .hps_lwhps2fpga_bready(lw_bready),
      .hps_lwhps2fpga_arid(lw_arid), .hps_lwhps2fpga_araddr(lw_araddr),
      .hps_lwhps2fpga_arlen(lw_arlen), .hps_lwhps2fpga_arsize(lw_arsize),
      .hps_lwhps2fpga_arburst(lw_arburst), .hps_lwhps2fpga_arlock(lw_arlock),
      .hps_lwhps2fpga_arcache(lw_arcache), .hps_lwhps2fpga_arprot(lw_arprot),
      .hps_lwhps2fpga_arvalid(lw_arvalid), .hps_lwhps2fpga_arready(lw_arready),
      .hps_lwhps2fpga_rid(lw_rid), .hps_lwhps2fpga_rdata(lw_rdata),
      .hps_lwhps2fpga_rresp(lw_rresp), .hps_lwhps2fpga_rlast(lw_rlast),
      .hps_lwhps2fpga_rvalid(lw_rvalid), .hps_lwhps2fpga_rready(lw_rready),
      // The fabric-to-SDRAM bridge.
      .hps_f2sdram_axi_clock_clk(clk), .hps_f2sdram_axi_reset_reset(h2f_reset),
      .hps_f2sdram_awid(f2s_awid), .hps_f2sdram_awaddr(f2s_awaddr),
      .hps_f2sdram_awlen(f2s_awlen), .hps_f2sdram_awsize(f2s_awsize),
      .hps_f2sdram_awburst(f2s_awburst), .hps_f2sdram_awlock(f2s_awlock),
      .hps_f2sdram_awcache(f2s_awcache), .hps_f2sdram_awprot(f2s_awprot),
      .hps_f2sdram_awqos(f2s_awqos), .hps_f2sdram_awregion(f2s_awregion),
      .hps_f2sdram_awuser(f2s_awuser),
      .hps_f2sdram_awvalid(f2s_awvalid), .hps_f2sdram_awready(f2s_awready),
      .hps_f2sdram_wdata(f2s_wdata), .hps_f2sdram_wstrb(f2s_wstrb),
      .hps_f2sdram_wlast(f2s_wlast), .hps_f2sdram_wuser(f2s_wuser),
      .hps_f2sdram_wvalid(f2s_wvalid), .hps_f2sdram_wready(f2s_wready),
      .hps_f2sdram_bid(f2s_bid), .hps_f2sdram_bresp(f2s_bresp),
      .hps_f2sdram_buser(f2s_buser),
      .hps_f2sdram_bvalid(f2s_bvalid), .hps_f2sdram_bready(f2s_bready),
      .hps_f2sdram_arid(f2s_arid), .hps_f2sdram_araddr(f2s_araddr),
      .hps_f2sdram_arlen(f2s_arlen), .hps_f2sdram_arsize(f2s_arsize),
      .hps_f2sdram_arburst(f2s_arburst), .hps_f2sdram_arlock(f2s_arlock),
      .hps_f2sdram_arcache(f2s_arcache), .hps_f2sdram_arprot(f2s_arprot),
      .hps_f2sdram_arqos(f2s_arqos), .hps_f2sdram_arregion(f2s_arregion),
      .hps_f2sdram_aruser(f2s_aruser),
      .hps_f2sdram_arvalid(f2s_arvalid), .hps_f2sdram_arready(f2s_arready),
      .hps_f2sdram_rid(f2s_rid), .hps_f2sdram_rdata(f2s_rdata),
      .hps_f2sdram_rresp(f2s_rresp), .hps_f2sdram_rlast(f2s_rlast),
      .hps_f2sdram_ruser(f2s_ruser),
      .hps_f2sdram_rvalid(f2s_rvalid), .hps_f2sdram_rready(f2s_rready)
  );

  // ---------------------------------------------- the two bridges, answered
  //
  // Each default slave takes the bridges' own reset and nothing else,
  // synchronized, as under the CADR: a reset of it with a transaction in
  // flight would take the address and never answer it.
  logic [2:0] h2f_rst_s;
  logic       h2f_rst;
  always_ff @(posedge clk) begin
    h2f_rst_s <= {h2f_rst_s[1:0], h2f_reset};
    h2f_rst   <= h2f_rst_s[2];
  end

  cadr_gp0_default #(.WORD(FAULT_WORD), .ID_W(4), .LEN_W(8)) u_h2f (
      .clk(clk), .rst(h2f_rst),
      .s_awvalid(h2f_awvalid), .s_awid(h2f_awid), .s_awready(h2f_awready),
      .s_wlast(h2f_wlast), .s_wvalid(h2f_wvalid), .s_wready(h2f_wready),
      .s_bresp(h2f_bresp), .s_bid(h2f_bid), .s_bvalid(h2f_bvalid),
      .s_bready(h2f_bready),
      .s_arlen(h2f_arlen), .s_arid(h2f_arid), .s_arvalid(h2f_arvalid),
      .s_arready(h2f_arready), .s_rdata(h2f_rdata), .s_rresp(h2f_rresp),
      .s_rid(h2f_rid), .s_rlast(h2f_rlast), .s_rvalid(h2f_rvalid),
      .s_rready(h2f_rready)
  );
  cadr_gp0_default #(.WORD(FAULT_WORD), .ID_W(4), .LEN_W(8)) u_lw (
      .clk(clk), .rst(h2f_rst),
      .s_awvalid(lw_awvalid), .s_awid(lw_awid), .s_awready(lw_awready),
      .s_wlast(lw_wlast), .s_wvalid(lw_wvalid), .s_wready(lw_wready),
      .s_bresp(lw_bresp), .s_bid(lw_bid), .s_bvalid(lw_bvalid),
      .s_bready(lw_bready),
      .s_arlen(lw_arlen), .s_arid(lw_arid), .s_arvalid(lw_arvalid),
      .s_arready(lw_arready), .s_rdata(lw_rdata), .s_rresp(lw_rresp),
      .s_rid(lw_rid), .s_rlast(lw_rlast), .s_rvalid(lw_rvalid),
      .s_rready(lw_rready)
  );

  // ------------------------------------ the FPGA-to-SDRAM bridge, unused
  assign f2s_awid     = 5'd0;
  assign f2s_awaddr   = 32'd0;
  assign f2s_awlen    = 8'd0;
  assign f2s_awsize   = 3'd3;
  assign f2s_awburst  = 2'b01;
  assign f2s_awlock   = 1'b0;
  assign f2s_awcache  = 4'd0;
  assign f2s_awprot   = 3'd0;
  assign f2s_awqos    = 4'd0;
  assign f2s_awregion = 4'd0;
  assign f2s_awuser   = 8'd0;
  assign f2s_awvalid  = 1'b0;
  assign f2s_wdata    = 64'd0;
  assign f2s_wstrb    = 8'd0;
  assign f2s_wlast    = 1'b0;
  assign f2s_wuser    = 8'd0;
  assign f2s_wvalid   = 1'b0;
  assign f2s_bready   = 1'b1;
  assign f2s_arid     = 5'd0;
  assign f2s_araddr   = 32'd0;
  assign f2s_arlen    = 8'd0;
  assign f2s_arsize   = 3'd3;
  assign f2s_arburst  = 2'b01;
  assign f2s_arlock   = 1'b0;
  assign f2s_arcache  = 4'd0;
  assign f2s_arprot   = 3'd0;
  assign f2s_arqos    = 4'd0;
  assign f2s_arregion = 4'd0;
  assign f2s_aruser   = 8'd0;
  assign f2s_arvalid  = 1'b0;
  assign f2s_rready   = 1'b1;

  // **AND EVERY ONE OF ITS ANSWERS IS KEPT.**  Quartus refuses a processor
  // system whose FPGA-to-SDRAM outputs reach nothing: synthesis stops at
  // error 129015, "Output port F2SDRAM_RDATA ... is not legally connected",
  // and 24265, "the interface f2sdram is not connected" (measured on the
  // first fit of this file).  So the bridge's answers are folded into one
  // register that `noprune` keeps, which is the CADR build's `witness`
  // arrangement for its own reason, and nothing reads it.
  /* verilator lint_off UNUSEDSIGNAL */
  (* noprune *) logic f2s_witness;
  /* verilator lint_on UNUSEDSIGNAL */
  always_ff @(posedge clk)
    f2s_witness <= ^{f2s_awready, f2s_wready, f2s_bid, f2s_bresp, f2s_bvalid,
                     f2s_buser, f2s_arready, f2s_rid, f2s_rdata, f2s_rresp,
                     f2s_rlast, f2s_ruser, f2s_rvalid};

  // The warm-reset handshake, by the CADR build's own gate.  Nothing is ever
  // in flight on the bridge, so the share it would wait for is always idle.
  /* verilator lint_off PINCONNECTEMPTY */
  cadr_f2sdram_gate u_gate (
      .clk(clk), .rst(rst),
      .h2f_reset(h2f_reset), .gp_open(gp_out[0]), .req_n(warm_req_n),
      .idle(1'b1),
      .hold(), .port_rst(), .ack_n(warm_ack_n), .live(), .may_start()
  );
  /* verilator lint_on PINCONNECTEMPTY */

  // The tally: "FALT" whichever half `h2f_gp_out[1]` asks for.
  assign gp_in = FAULT_WORD;

  // ------------------------------------------------------- the connectors
  assign jp1_pin31 = 1'bz;
  assign jp1_pin32 = 1'bz;
  assign jp1_pin33 = 1'bz;
  assign jp1_pin34 = 1'bz;
  assign jp1_pin35 = 1'bz;
  assign jp1_pin36 = 1'bz;
  assign jp1_pin37 = 1'bz;
  assign jp1_pin38 = 1'bz;

  // What this design reads of nothing: KEY0, the switches, the addresses,
  // data and attributes of both bridges, and the rest of `h2f_gp_out`.
  /* verilator lint_off UNUSEDSIGNAL */
  logic unused;
  assign unused = ^{btn[0], sw, gp_out[31:1],
                    h2f_awaddr, h2f_araddr, h2f_wdata, h2f_wstrb, h2f_awlen,
                    h2f_awsize, h2f_arsize, h2f_awprot, h2f_arprot,
                    h2f_awburst, h2f_arburst, h2f_awlock, h2f_arlock,
                    h2f_awcache, h2f_arcache,
                    lw_awaddr, lw_araddr, lw_wdata, lw_wstrb, lw_awlen,
                    lw_awsize, lw_arsize, lw_awprot, lw_arprot,
                    lw_awburst, lw_arburst, lw_awlock, lw_arlock,
                    lw_awcache, lw_arcache};
  /* verilator lint_on UNUSEDSIGNAL */

endmodule

`default_nettype wire
