# SPDX-FileCopyrightText: 2026 Mete Balci
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# The DE25-Nano's Quartus project, written from nothing at every build.
#
# Run by `boards/de25-nano/quartus/build.sh` as
#
#     quartus_sh -t boards/de25-nano/quartus/project.tcl <build dir> <userid> <source>...
#
# from the repository's root.  The sources are the Makefile's `$(MACHINE)` and
# `$(DE25_TOP)`, in that order, and `$(DE25_PROBE)` after them when the probe
# is built, so that the list of what the board is built from is written once,
# beside the lint that reads the same list.  `PROBE_DEPTH` in the environment
# is the probe's depth, and zero or none is the plain board.
#
# **NOTHING HERE IS TAKEN FROM A GUI-SAVED PROJECT.**  A `.qsf` saved by the
# tool carries dates, versions and every default it happened to write, and
# none of that is a decision.  Each assignment below is here for a reason
# given beside it.

package require ::quartus::project

set argv $quartus(args)
if {[llength $argv] < 3} {
    puts "project: usage: project.tcl <build dir> <userid> <source>..."
    exit 1
}
set build   [file normalize [lindex $argv 0]]
set probe_depth [expr {[info exists ::env(PROBE_DEPTH)] ? $::env(PROBE_DEPTH) : 0}]
if {![string is integer -strict $probe_depth] || $probe_depth < 0} {
    puts "project: PROBE_DEPTH is '$probe_depth', which is not a depth"
    exit 1
}
set userid  [lindex $argv 1]
set sources [lrange $argv 2 end]
set root    [pwd]

if {![regexp {^[0-9a-f]{8}$} $userid]} {
    puts "project: the build stamp must be eight hex digits, not '$userid'"
    exit 1
}

cd $build
project_new -overwrite cadr_de25

# ------------------------------------------------------------------ the part
#
# The part and its family are the resource package's and the user manual's;
# `boards/de25-nano/README.md` says where each is read.
set_global_assignment -name FAMILY "Agilex 5"
set_global_assignment -name DEVICE A5EB013BB23BE4SCS
set_global_assignment -name TOP_LEVEL_ENTITY cadr_de25
set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files
# Two other build flows can share this machine, and the fitter takes every
# core it is offered.
set_global_assignment -name NUM_PARALLEL_PROCESSORS 8
# **THE CONTROL STORE COMES UP ALL ONES**, written by a loop over its 16,384
# words in `rtl/machine/cadr_microcycle.sv`'s `initial` block, and Quartus
# refuses a constant loop longer than 5,000 iterations by default (error
# 13356).  The limit is raised to exactly that loop's length, so a longer one
# is still refused rather than waved through.
set_global_assignment -name VERILOG_CONSTANT_LOOP_LIMIT 16384
# **NO REGISTER IS GIVEN A POWER-UP LEVEL THE DESIGN DID NOT ASK FOR.**  With
# this on, which is Quartus's default, a register that has no power-up level
# may be given either one to save area.  The machine is checked in Verilator,
# and built for the Zynq boards by Vivado, with every register it does not
# reset starting at zero, so the compiler is not allowed to choose here.
set_global_assignment -name ALLOW_POWER_UP_DONT_CARE OFF
# **NO RETIMING.**  Quartus moves registers across logic by default, and the
# first fit here had moved 233 of them, `md[14]~RTM` among them.  The
# machine's timing exceptions in `cadr_de25.sdc` name registers by what they
# are in the design, as `cadr_machine.xdc` does for Vivado, which does not
# retime, and a register moved across the logic between two of them is no
# longer the register the exception's argument is about.  So registers, RAM
# blocks and DSP blocks all stay where the design puts them.
set_global_assignment -name ALLOW_REGISTER_RETIMING OFF
set_global_assignment -name ALLOW_RAM_RETIMING OFF
set_global_assignment -name ALLOW_DSP_RETIMING OFF

# ------------------------------------------------------------- the sources
foreach f $sources {
    set_global_assignment -name SYSTEMVERILOG_FILE [file join $root $f]
}
# The I/O PLL and the Reset Release, deployed into this directory by
# `build.sh`, and generated by `quartus_ipgenerate`.
set_global_assignment -name IP_FILE [file join $build ip cadr_de25_pll.ip]
set_global_assignment -name IP_FILE [file join $build ip cadr_de25_reset_release.ip]
set_global_assignment -name SDC_FILE [file join $root boards de25-nano quartus cadr_de25.sdc]

# **THE PROBE, AND ITS OWN CONSTRAINTS, ONLY WHEN IT IS BUILT.**  The Virtual
# JTAG IP deployed by `build.sh`, the depth as the top level's parameter, and
# `cadr_probe.sdc`, which declares the JTAG clock and relaxes one register of
# the probe.  That file is read only here for the reason the Zynq flows read
# theirs only behind `PROBE_DEPTH`: a constraint on something that is not in
# the design is a warning that reads like a constraint that applied.
if {$probe_depth > 0} {
    set_global_assignment -name IP_FILE [file join $build ip cadr_de25_vjtag.ip]
    set_global_assignment -name SDC_FILE [file join $root boards de25-nano quartus cadr_probe.sdc]
    set_parameter -name PROBE_DEPTH $probe_depth
}

# ------------------------------------------- the three asynchronous memories
#
# **THE DISPATCH MEMORY AND BOTH LEVELS OF THE MAP ARE MLABS, AND NOTHING IN
# `rtl/` SAYS SO.**  `rtl/machine/cadr_microcycle.sv` reads the three
# asynchronously, as MIT's board does, and by default Quartus builds an
# asynchronously read array out of registers (info 276007): about 70,000 of
# them and three quarters of the part, measured.  Altera's Agilex 5 embedded
# memory guide (document 813901, the features table) gives the MLAB, and only
# the MLAB, "asynchronous memory ... for flow-through read memory operations",
# with same-port read-during-write "Don't Care".  So synthesis is asked for an
# MLAB with read-during-write checking off, from here and not from the HDL,
# which the Zynq flows and every Verilator check read unchanged.  Asking for
# the MLAB alone is refused (info 276009, the read-during-write behavior).
#
# **WHAT "CHECKING OFF" GIVES AWAY IS ONE TICK, AND A CHECK HOLDS IT.**  The
# word read at an address in the tick after the edge that wrote it is then
# not specified.  `build/rdw_poison.pass`, `build/rdw_poison_sys.pass` and
# `build/rdw_poison_map.pass` return a poisoned word in exactly that tick and
# still agree with muir on every program, and the last section of
# `cadr_microcycle.sv` says why.  `build.sh` refuses a synthesis in which the
# three are anything but MLABs.
foreach memory {dmem l1_map l2_map} {
    set_instance_assignment -name RAMSTYLE_ATTRIBUTE MLAB -to "u_machine|processor|$memory"
    set_instance_assignment -name RAMSTYLE_ATTRIBUTE_RDW no_rw_check -to "u_machine|processor|$memory"
}

# The two images `cadr_machine` reads at elaboration, by absolute path:
# `$readmemh` resolves a relative one against wherever the tool is running,
# which is this directory and not the repository.  `build.sh` refuses to
# start without them, and the synthesis report's parameter table is where the
# two paths can be read back.
set_parameter -name PROM_HEX      [file join $root build boot_prom.hex]
set_parameter -name SYNC_PROM_HEX [file join $root build sync_prom.hex]

# ------------------------------------------------------ the configuration
#
# **HOW THE PART IS CONFIGURED IS A FACT OF THE BOARD**, not a choice of this
# design: which of the SDM's pins the board wires to `CONF_DONE` and to the
# processor's cold reset, what the configuration clock is, and how the power
# regulator is told the core voltage.  The user manual gives some of it ---
# the 125 MHz `OSC_CLK1` in section 3.5, and Active Serial from the 128 Mbit
# QSPI flash as the default scheme in section 3.1 --- and not the rest.  So
# the values are read from the one source for this board that grants reuse:
# Altera's `agilex5-demo-hps2fpga-interfaces`, under MIT-0, whose
# `brd_terasic_de25nano_revb/hw_base/create_quartus_project.tcl` at commit
# `064c0cf2f7e749b72add75d3ac3845f20af63dc8` sets exactly these seven.
# Terasic's own `golden_top.qsf` sets the same seven to the same values.
#
# The scheme is the flash's, as the board's DIP switch leaves it by default.
# This flow writes an SRAM Object File, which is loaded over JTAG and lost at
# power-off; nothing here writes the flash, and the scheme matters only to a
# flash image, which a later slice may build.
set_global_assignment -name STRATIXV_CONFIGURATION_SCHEME "ACTIVE SERIAL X4"
set_global_assignment -name ACTIVE_SERIAL_CLOCK AS_FREQ_125MHZ
set_global_assignment -name DEVICE_INITIALIZATION_CLOCK OSC_CLK_1_125MHZ
set_global_assignment -name USE_CONF_DONE SDM_IO16
set_global_assignment -name USE_HPS_COLD_RESET SDM_IO11
set_global_assignment -name PWRMGT_VOLTAGE_OUTPUT_FORMAT "LINEAR FORMAT"
set_global_assignment -name PWRMGT_LINEAR_FORMAT_N "-12"

# **THE BITSTREAM NAMES THE TREE IT WAS BUILT FROM**, in the JTAG USERCODE
# register, in the format `tools/build_stamp.tcl` gives the Zynq boards: the
# commit's first seven hex digits and a nibble saying how the tree stood.
# Quartus describes this assignment as the value the USERCODE instruction
# reads, and Altera's DE25-Nano project sets it too.
set_global_assignment -name STRATIX_JTAG_USER_CODE $userid
set_global_assignment -name USE_CHECKSUM_AS_USERCODE OFF

# ----------------------------------------------------------------- the pins
#
# **FROM `boards/de25-nano/de25_nano_pins.tcl`, AND ONLY FOR THE PORTS THE TOP
# LEVEL HAS.**  That file assigns every pin it knows, and Quartus warns about
# each assignment to a port the design does not have: well over a hundred
# warnings on this board, among which a real one would be lost.  So the file
# is sourced in a child interpreter whose two assignment commands are
# recorded rather than applied, and only the top level's ports are applied
# here.  The pin file stays the one place a pin is written.
set wanted {^(clock50_0|btn\[[01]\]|sw\[[0-3]\]|led\[[0-7]\])$}
set locations {}
set standards {}
proc record_location {pin -to port} {
    lappend ::locations $port $pin
}
proc record_standard {-name name standard -to port} {
    if {$name ne "IO_STANDARD"} {
        puts "project: the pin file makes a $name assignment, which this flow does not know"
        exit 1
    }
    lappend ::standards $port $standard
}
set pins [interp create]
interp alias $pins set_location_assignment {} record_location
interp alias $pins set_instance_assignment {} record_standard
$pins eval [list source [file join $root boards de25-nano de25_nano_pins.tcl]]
interp delete $pins

set placed 0
foreach {port pin} $locations {
    if {[regexp $wanted $port]} {
        set_location_assignment $pin -to $port
        incr placed
    }
}
set standardized 0
foreach {port standard} $standards {
    if {[regexp $wanted $port]} {
        set_instance_assignment -name IO_STANDARD $standard -to $port
        incr standardized
    }
}
# One clock, two buttons, four switches and eight LEDs.  A count that is not
# fifteen is a pin file or a port list that has moved under this flow.
if {$placed != 15 || $standardized != 15} {
    puts "project: placed $placed ports and gave $standardized a standard, wanting 15 and 15"
    exit 1
}
puts "project: 15 of the pin file's [expr {[llength $locations] / 2}] ports are this top level's"

project_close
if {$probe_depth > 0} {
    puts "project: written to $build/cadr_de25.qsf with USERCODE $userid and a probe of $probe_depth samples"
} else {
    puts "project: written to $build/cadr_de25.qsf with USERCODE $userid"
}
