// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by boards/kria-kr260/vivado/gen_ps8.py from $XILINX_VIVADO's own PS8.v.
// Do not edit; run `make ps8`.
//
// `PS8` as an empty shell, so that Verilator can elaborate
// `boards/kria-kr260/cadr_ps8.sv` and lint the top level that instantiates it.
//
// **THIS FILE MUST NEVER MOVE TO `rtl/` OR `boards/`**: the Vivado flows glob
// those, and a stub there would be handed to synthesis in place of the real
// primitive.  Nothing globs `tb/`.
//
// **AND IT MODELS NOTHING.**  Every output is zero, so `pl_resetn0` is low
// and the fabric's ports are held in reset for ever.  What it carries is the
// PORT LIST, all 1015 of them, off the same parse as the wrapper.

`default_nettype none

/* verilator lint_off DECLFILENAME */

module PS8 (
    output var logic [7:0]    ADMA2PLCACK,
    output var logic [7:0]    ADMA2PLTVLD,
    output var logic          DPAUDIOREFCLK,
    output var logic          DPAUXDATAOEN,
    output var logic          DPAUXDATAOUT,
    output var logic          DPLIVEVIDEODEOUT,
    output var logic [31:0]   DPMAXISMIXEDAUDIOTDATA,
    output var logic          DPMAXISMIXEDAUDIOTID,
    output var logic          DPMAXISMIXEDAUDIOTVALID,
    output var logic          DPSAXISAUDIOTREADY,
    output var logic          DPVIDEOOUTHSYNC,
    output var logic [35:0]   DPVIDEOOUTPIXEL1,
    output var logic          DPVIDEOOUTVSYNC,
    output var logic          DPVIDEOREFCLK,
    output var logic          EMIOCAN0PHYTX,
    output var logic          EMIOCAN1PHYTX,
    output var logic [1:0]    EMIOENET0DMABUSWIDTH,
    output var logic          EMIOENET0DMATXENDTOG,
    output var logic [93:0]   EMIOENET0GEMTSUTIMERCNT,
    output var logic [7:0]    EMIOENET0GMIITXD,
    output var logic          EMIOENET0GMIITXEN,
    output var logic          EMIOENET0GMIITXER,
    output var logic          EMIOENET0MDIOMDC,
    output var logic          EMIOENET0MDIOO,
    output var logic          EMIOENET0MDIOTN,
    output var logic [7:0]    EMIOENET0RXWDATA,
    output var logic          EMIOENET0RXWEOP,
    output var logic          EMIOENET0RXWERR,
    output var logic          EMIOENET0RXWFLUSH,
    output var logic          EMIOENET0RXWSOP,
    output var logic [44:0]   EMIOENET0RXWSTATUS,
    output var logic          EMIOENET0RXWWR,
    output var logic [2:0]    EMIOENET0SPEEDMODE,
    output var logic          EMIOENET0TXRRD,
    output var logic [3:0]    EMIOENET0TXRSTATUS,
    output var logic [1:0]    EMIOENET1DMABUSWIDTH,
    output var logic          EMIOENET1DMATXENDTOG,
    output var logic [7:0]    EMIOENET1GMIITXD,
    output var logic          EMIOENET1GMIITXEN,
    output var logic          EMIOENET1GMIITXER,
    output var logic          EMIOENET1MDIOMDC,
    output var logic          EMIOENET1MDIOO,
    output var logic          EMIOENET1MDIOTN,
    output var logic [7:0]    EMIOENET1RXWDATA,
    output var logic          EMIOENET1RXWEOP,
    output var logic          EMIOENET1RXWERR,
    output var logic          EMIOENET1RXWFLUSH,
    output var logic          EMIOENET1RXWSOP,
    output var logic [44:0]   EMIOENET1RXWSTATUS,
    output var logic          EMIOENET1RXWWR,
    output var logic [2:0]    EMIOENET1SPEEDMODE,
    output var logic          EMIOENET1TXRRD,
    output var logic [3:0]    EMIOENET1TXRSTATUS,
    output var logic [1:0]    EMIOENET2DMABUSWIDTH,
    output var logic          EMIOENET2DMATXENDTOG,
    output var logic [7:0]    EMIOENET2GMIITXD,
    output var logic          EMIOENET2GMIITXEN,
    output var logic          EMIOENET2GMIITXER,
    output var logic          EMIOENET2MDIOMDC,
    output var logic          EMIOENET2MDIOO,
    output var logic          EMIOENET2MDIOTN,
    output var logic [7:0]    EMIOENET2RXWDATA,
    output var logic          EMIOENET2RXWEOP,
    output var logic          EMIOENET2RXWERR,
    output var logic          EMIOENET2RXWFLUSH,
    output var logic          EMIOENET2RXWSOP,
    output var logic [44:0]   EMIOENET2RXWSTATUS,
    output var logic          EMIOENET2RXWWR,
    output var logic [2:0]    EMIOENET2SPEEDMODE,
    output var logic          EMIOENET2TXRRD,
    output var logic [3:0]    EMIOENET2TXRSTATUS,
    output var logic [1:0]    EMIOENET3DMABUSWIDTH,
    output var logic          EMIOENET3DMATXENDTOG,
    output var logic [7:0]    EMIOENET3GMIITXD,
    output var logic          EMIOENET3GMIITXEN,
    output var logic          EMIOENET3GMIITXER,
    output var logic          EMIOENET3MDIOMDC,
    output var logic          EMIOENET3MDIOO,
    output var logic          EMIOENET3MDIOTN,
    output var logic [7:0]    EMIOENET3RXWDATA,
    output var logic          EMIOENET3RXWEOP,
    output var logic          EMIOENET3RXWERR,
    output var logic          EMIOENET3RXWFLUSH,
    output var logic          EMIOENET3RXWSOP,
    output var logic [44:0]   EMIOENET3RXWSTATUS,
    output var logic          EMIOENET3RXWWR,
    output var logic [2:0]    EMIOENET3SPEEDMODE,
    output var logic          EMIOENET3TXRRD,
    output var logic [3:0]    EMIOENET3TXRSTATUS,
    output var logic          EMIOGEM0DELAYREQRX,
    output var logic          EMIOGEM0DELAYREQTX,
    output var logic          EMIOGEM0PDELAYREQRX,
    output var logic          EMIOGEM0PDELAYREQTX,
    output var logic          EMIOGEM0PDELAYRESPRX,
    output var logic          EMIOGEM0PDELAYRESPTX,
    output var logic          EMIOGEM0RXSOF,
    output var logic          EMIOGEM0SYNCFRAMERX,
    output var logic          EMIOGEM0SYNCFRAMETX,
    output var logic          EMIOGEM0TSUTIMERCMPVAL,
    output var logic          EMIOGEM0TXRFIXEDLAT,
    output var logic          EMIOGEM0TXSOF,
    output var logic          EMIOGEM1DELAYREQRX,
    output var logic          EMIOGEM1DELAYREQTX,
    output var logic          EMIOGEM1PDELAYREQRX,
    output var logic          EMIOGEM1PDELAYREQTX,
    output var logic          EMIOGEM1PDELAYRESPRX,
    output var logic          EMIOGEM1PDELAYRESPTX,
    output var logic          EMIOGEM1RXSOF,
    output var logic          EMIOGEM1SYNCFRAMERX,
    output var logic          EMIOGEM1SYNCFRAMETX,
    output var logic          EMIOGEM1TSUTIMERCMPVAL,
    output var logic          EMIOGEM1TXRFIXEDLAT,
    output var logic          EMIOGEM1TXSOF,
    output var logic          EMIOGEM2DELAYREQRX,
    output var logic          EMIOGEM2DELAYREQTX,
    output var logic          EMIOGEM2PDELAYREQRX,
    output var logic          EMIOGEM2PDELAYREQTX,
    output var logic          EMIOGEM2PDELAYRESPRX,
    output var logic          EMIOGEM2PDELAYRESPTX,
    output var logic          EMIOGEM2RXSOF,
    output var logic          EMIOGEM2SYNCFRAMERX,
    output var logic          EMIOGEM2SYNCFRAMETX,
    output var logic          EMIOGEM2TSUTIMERCMPVAL,
    output var logic          EMIOGEM2TXRFIXEDLAT,
    output var logic          EMIOGEM2TXSOF,
    output var logic          EMIOGEM3DELAYREQRX,
    output var logic          EMIOGEM3DELAYREQTX,
    output var logic          EMIOGEM3PDELAYREQRX,
    output var logic          EMIOGEM3PDELAYREQTX,
    output var logic          EMIOGEM3PDELAYRESPRX,
    output var logic          EMIOGEM3PDELAYRESPTX,
    output var logic          EMIOGEM3RXSOF,
    output var logic          EMIOGEM3SYNCFRAMERX,
    output var logic          EMIOGEM3SYNCFRAMETX,
    output var logic          EMIOGEM3TSUTIMERCMPVAL,
    output var logic          EMIOGEM3TXRFIXEDLAT,
    output var logic          EMIOGEM3TXSOF,
    output var logic [95:0]   EMIOGPIOO,
    output var logic [95:0]   EMIOGPIOTN,
    output var logic          EMIOI2C0SCLO,
    output var logic          EMIOI2C0SCLTN,
    output var logic          EMIOI2C0SDAO,
    output var logic          EMIOI2C0SDATN,
    output var logic          EMIOI2C1SCLO,
    output var logic          EMIOI2C1SCLTN,
    output var logic          EMIOI2C1SDAO,
    output var logic          EMIOI2C1SDATN,
    output var logic          EMIOSDIO0BUSPOWER,
    output var logic [2:0]    EMIOSDIO0BUSVOLT,
    output var logic          EMIOSDIO0CLKOUT,
    output var logic          EMIOSDIO0CMDENA,
    output var logic          EMIOSDIO0CMDOUT,
    output var logic [7:0]    EMIOSDIO0DATAENA,
    output var logic [7:0]    EMIOSDIO0DATAOUT,
    output var logic          EMIOSDIO0LEDCONTROL,
    output var logic          EMIOSDIO1BUSPOWER,
    output var logic [2:0]    EMIOSDIO1BUSVOLT,
    output var logic          EMIOSDIO1CLKOUT,
    output var logic          EMIOSDIO1CMDENA,
    output var logic          EMIOSDIO1CMDOUT,
    output var logic [7:0]    EMIOSDIO1DATAENA,
    output var logic [7:0]    EMIOSDIO1DATAOUT,
    output var logic          EMIOSDIO1LEDCONTROL,
    output var logic          EMIOSPI0MO,
    output var logic          EMIOSPI0MOTN,
    output var logic          EMIOSPI0SCLKO,
    output var logic          EMIOSPI0SCLKTN,
    output var logic          EMIOSPI0SO,
    output var logic          EMIOSPI0SSNTN,
    output var logic [2:0]    EMIOSPI0SSON,
    output var logic          EMIOSPI0STN,
    output var logic          EMIOSPI1MO,
    output var logic          EMIOSPI1MOTN,
    output var logic          EMIOSPI1SCLKO,
    output var logic          EMIOSPI1SCLKTN,
    output var logic          EMIOSPI1SO,
    output var logic          EMIOSPI1SSNTN,
    output var logic [2:0]    EMIOSPI1SSON,
    output var logic          EMIOSPI1STN,
    output var logic [2:0]    EMIOTTC0WAVEO,
    output var logic [2:0]    EMIOTTC1WAVEO,
    output var logic [2:0]    EMIOTTC2WAVEO,
    output var logic [2:0]    EMIOTTC3WAVEO,
    output var logic          EMIOU2DSPORTVBUSCTRLUSB30,
    output var logic          EMIOU2DSPORTVBUSCTRLUSB31,
    output var logic          EMIOU3DSPORTVBUSCTRLUSB30,
    output var logic          EMIOU3DSPORTVBUSCTRLUSB31,
    output var logic          EMIOUART0DTRN,
    output var logic          EMIOUART0RTSN,
    output var logic          EMIOUART0TX,
    output var logic          EMIOUART1DTRN,
    output var logic          EMIOUART1RTSN,
    output var logic          EMIOUART1TX,
    output var logic          EMIOWDT0RSTO,
    output var logic          EMIOWDT1RSTO,
    output var logic          FMIOGEM0FIFORXCLKTOPLBUFG,
    output var logic          FMIOGEM0FIFOTXCLKTOPLBUFG,
    output var logic          FMIOGEM1FIFORXCLKTOPLBUFG,
    output var logic          FMIOGEM1FIFOTXCLKTOPLBUFG,
    output var logic          FMIOGEM2FIFORXCLKTOPLBUFG,
    output var logic          FMIOGEM2FIFOTXCLKTOPLBUFG,
    output var logic          FMIOGEM3FIFORXCLKTOPLBUFG,
    output var logic          FMIOGEM3FIFOTXCLKTOPLBUFG,
    output var logic          FMIOGEMTSUCLKTOPLBUFG,
    output var logic [31:0]   FTMGPO,
    output var logic [7:0]    GDMA2PLCACK,
    output var logic [7:0]    GDMA2PLTVLD,
    output var logic [39:0]   MAXIGP0ARADDR,
    output var logic [1:0]    MAXIGP0ARBURST,
    output var logic [3:0]    MAXIGP0ARCACHE,
    output var logic [15:0]   MAXIGP0ARID,
    output var logic [7:0]    MAXIGP0ARLEN,
    output var logic          MAXIGP0ARLOCK,
    output var logic [2:0]    MAXIGP0ARPROT,
    output var logic [3:0]    MAXIGP0ARQOS,
    output var logic [2:0]    MAXIGP0ARSIZE,
    output var logic [15:0]   MAXIGP0ARUSER,
    output var logic          MAXIGP0ARVALID,
    output var logic [39:0]   MAXIGP0AWADDR,
    output var logic [1:0]    MAXIGP0AWBURST,
    output var logic [3:0]    MAXIGP0AWCACHE,
    output var logic [15:0]   MAXIGP0AWID,
    output var logic [7:0]    MAXIGP0AWLEN,
    output var logic          MAXIGP0AWLOCK,
    output var logic [2:0]    MAXIGP0AWPROT,
    output var logic [3:0]    MAXIGP0AWQOS,
    output var logic [2:0]    MAXIGP0AWSIZE,
    output var logic [15:0]   MAXIGP0AWUSER,
    output var logic          MAXIGP0AWVALID,
    output var logic          MAXIGP0BREADY,
    output var logic          MAXIGP0RREADY,
    output var logic [127:0]  MAXIGP0WDATA,
    output var logic          MAXIGP0WLAST,
    output var logic [15:0]   MAXIGP0WSTRB,
    output var logic          MAXIGP0WVALID,
    output var logic [39:0]   MAXIGP1ARADDR,
    output var logic [1:0]    MAXIGP1ARBURST,
    output var logic [3:0]    MAXIGP1ARCACHE,
    output var logic [15:0]   MAXIGP1ARID,
    output var logic [7:0]    MAXIGP1ARLEN,
    output var logic          MAXIGP1ARLOCK,
    output var logic [2:0]    MAXIGP1ARPROT,
    output var logic [3:0]    MAXIGP1ARQOS,
    output var logic [2:0]    MAXIGP1ARSIZE,
    output var logic [15:0]   MAXIGP1ARUSER,
    output var logic          MAXIGP1ARVALID,
    output var logic [39:0]   MAXIGP1AWADDR,
    output var logic [1:0]    MAXIGP1AWBURST,
    output var logic [3:0]    MAXIGP1AWCACHE,
    output var logic [15:0]   MAXIGP1AWID,
    output var logic [7:0]    MAXIGP1AWLEN,
    output var logic          MAXIGP1AWLOCK,
    output var logic [2:0]    MAXIGP1AWPROT,
    output var logic [3:0]    MAXIGP1AWQOS,
    output var logic [2:0]    MAXIGP1AWSIZE,
    output var logic [15:0]   MAXIGP1AWUSER,
    output var logic          MAXIGP1AWVALID,
    output var logic          MAXIGP1BREADY,
    output var logic          MAXIGP1RREADY,
    output var logic [127:0]  MAXIGP1WDATA,
    output var logic          MAXIGP1WLAST,
    output var logic [15:0]   MAXIGP1WSTRB,
    output var logic          MAXIGP1WVALID,
    output var logic [39:0]   MAXIGP2ARADDR,
    output var logic [1:0]    MAXIGP2ARBURST,
    output var logic [3:0]    MAXIGP2ARCACHE,
    output var logic [15:0]   MAXIGP2ARID,
    output var logic [7:0]    MAXIGP2ARLEN,
    output var logic          MAXIGP2ARLOCK,
    output var logic [2:0]    MAXIGP2ARPROT,
    output var logic [3:0]    MAXIGP2ARQOS,
    output var logic [2:0]    MAXIGP2ARSIZE,
    output var logic [15:0]   MAXIGP2ARUSER,
    output var logic          MAXIGP2ARVALID,
    output var logic [39:0]   MAXIGP2AWADDR,
    output var logic [1:0]    MAXIGP2AWBURST,
    output var logic [3:0]    MAXIGP2AWCACHE,
    output var logic [15:0]   MAXIGP2AWID,
    output var logic [7:0]    MAXIGP2AWLEN,
    output var logic          MAXIGP2AWLOCK,
    output var logic [2:0]    MAXIGP2AWPROT,
    output var logic [3:0]    MAXIGP2AWQOS,
    output var logic [2:0]    MAXIGP2AWSIZE,
    output var logic [15:0]   MAXIGP2AWUSER,
    output var logic          MAXIGP2AWVALID,
    output var logic          MAXIGP2BREADY,
    output var logic          MAXIGP2RREADY,
    output var logic [127:0]  MAXIGP2WDATA,
    output var logic          MAXIGP2WLAST,
    output var logic [15:0]   MAXIGP2WSTRB,
    output var logic          MAXIGP2WVALID,
    output var logic          OSCRTCCLK,
    output var logic [3:0]    PLCLK,
    output var logic          PMUAIBAFIFMFPDREQ,
    output var logic          PMUAIBAFIFMLPDREQ,
    output var logic [46:0]   PMUERRORTOPL,
    output var logic [31:0]   PMUPLGPO,
    output var logic          PSPLEVENTO,
    output var logic [63:0]   PSPLIRQFPD,
    output var logic [99:0]   PSPLIRQLPD,
    output var logic [3:0]    PSPLSTANDBYWFE,
    output var logic [3:0]    PSPLSTANDBYWFI,
    output var logic          PSPLTRACECTL,
    output var logic [31:0]   PSPLTRACEDATA,
    output var logic [3:0]    PSPLTRIGACK,
    output var logic [3:0]    PSPLTRIGGER,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXN0OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXN1OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXN2OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXN3OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXP0OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXP1OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXP2OUT,
    output var logic          PSS_ALTO_CORE_PAD_MGTTXP3OUT,
    output var logic          PSS_ALTO_CORE_PAD_PADO,
    output var logic          RPUEVENTO0,
    output var logic          RPUEVENTO1,
    output var logic [43:0]   SACEFPDACADDR,
    output var logic [2:0]    SACEFPDACPROT,
    output var logic [3:0]    SACEFPDACSNOOP,
    output var logic          SACEFPDACVALID,
    output var logic          SACEFPDARREADY,
    output var logic          SACEFPDAWREADY,
    output var logic [5:0]    SACEFPDBID,
    output var logic [1:0]    SACEFPDBRESP,
    output var logic          SACEFPDBUSER,
    output var logic          SACEFPDBVALID,
    output var logic          SACEFPDCDREADY,
    output var logic          SACEFPDCRREADY,
    output var logic [127:0]  SACEFPDRDATA,
    output var logic [5:0]    SACEFPDRID,
    output var logic          SACEFPDRLAST,
    output var logic [3:0]    SACEFPDRRESP,
    output var logic          SACEFPDRUSER,
    output var logic          SACEFPDRVALID,
    output var logic          SACEFPDWREADY,
    output var logic          SAXIACPARREADY,
    output var logic          SAXIACPAWREADY,
    output var logic [4:0]    SAXIACPBID,
    output var logic [1:0]    SAXIACPBRESP,
    output var logic          SAXIACPBVALID,
    output var logic [127:0]  SAXIACPRDATA,
    output var logic [4:0]    SAXIACPRID,
    output var logic          SAXIACPRLAST,
    output var logic [1:0]    SAXIACPRRESP,
    output var logic          SAXIACPRVALID,
    output var logic          SAXIACPWREADY,
    output var logic          SAXIGP0ARREADY,
    output var logic          SAXIGP0AWREADY,
    output var logic [5:0]    SAXIGP0BID,
    output var logic [1:0]    SAXIGP0BRESP,
    output var logic          SAXIGP0BVALID,
    output var logic [3:0]    SAXIGP0RACOUNT,
    output var logic [7:0]    SAXIGP0RCOUNT,
    output var logic [127:0]  SAXIGP0RDATA,
    output var logic [5:0]    SAXIGP0RID,
    output var logic          SAXIGP0RLAST,
    output var logic [1:0]    SAXIGP0RRESP,
    output var logic          SAXIGP0RVALID,
    output var logic [3:0]    SAXIGP0WACOUNT,
    output var logic [7:0]    SAXIGP0WCOUNT,
    output var logic          SAXIGP0WREADY,
    output var logic          SAXIGP1ARREADY,
    output var logic          SAXIGP1AWREADY,
    output var logic [5:0]    SAXIGP1BID,
    output var logic [1:0]    SAXIGP1BRESP,
    output var logic          SAXIGP1BVALID,
    output var logic [3:0]    SAXIGP1RACOUNT,
    output var logic [7:0]    SAXIGP1RCOUNT,
    output var logic [127:0]  SAXIGP1RDATA,
    output var logic [5:0]    SAXIGP1RID,
    output var logic          SAXIGP1RLAST,
    output var logic [1:0]    SAXIGP1RRESP,
    output var logic          SAXIGP1RVALID,
    output var logic [3:0]    SAXIGP1WACOUNT,
    output var logic [7:0]    SAXIGP1WCOUNT,
    output var logic          SAXIGP1WREADY,
    output var logic          SAXIGP2ARREADY,
    output var logic          SAXIGP2AWREADY,
    output var logic [5:0]    SAXIGP2BID,
    output var logic [1:0]    SAXIGP2BRESP,
    output var logic          SAXIGP2BVALID,
    output var logic [3:0]    SAXIGP2RACOUNT,
    output var logic [7:0]    SAXIGP2RCOUNT,
    output var logic [127:0]  SAXIGP2RDATA,
    output var logic [5:0]    SAXIGP2RID,
    output var logic          SAXIGP2RLAST,
    output var logic [1:0]    SAXIGP2RRESP,
    output var logic          SAXIGP2RVALID,
    output var logic [3:0]    SAXIGP2WACOUNT,
    output var logic [7:0]    SAXIGP2WCOUNT,
    output var logic          SAXIGP2WREADY,
    output var logic          SAXIGP3ARREADY,
    output var logic          SAXIGP3AWREADY,
    output var logic [5:0]    SAXIGP3BID,
    output var logic [1:0]    SAXIGP3BRESP,
    output var logic          SAXIGP3BVALID,
    output var logic [3:0]    SAXIGP3RACOUNT,
    output var logic [7:0]    SAXIGP3RCOUNT,
    output var logic [127:0]  SAXIGP3RDATA,
    output var logic [5:0]    SAXIGP3RID,
    output var logic          SAXIGP3RLAST,
    output var logic [1:0]    SAXIGP3RRESP,
    output var logic          SAXIGP3RVALID,
    output var logic [3:0]    SAXIGP3WACOUNT,
    output var logic [7:0]    SAXIGP3WCOUNT,
    output var logic          SAXIGP3WREADY,
    output var logic          SAXIGP4ARREADY,
    output var logic          SAXIGP4AWREADY,
    output var logic [5:0]    SAXIGP4BID,
    output var logic [1:0]    SAXIGP4BRESP,
    output var logic          SAXIGP4BVALID,
    output var logic [3:0]    SAXIGP4RACOUNT,
    output var logic [7:0]    SAXIGP4RCOUNT,
    output var logic [127:0]  SAXIGP4RDATA,
    output var logic [5:0]    SAXIGP4RID,
    output var logic          SAXIGP4RLAST,
    output var logic [1:0]    SAXIGP4RRESP,
    output var logic          SAXIGP4RVALID,
    output var logic [3:0]    SAXIGP4WACOUNT,
    output var logic [7:0]    SAXIGP4WCOUNT,
    output var logic          SAXIGP4WREADY,
    output var logic          SAXIGP5ARREADY,
    output var logic          SAXIGP5AWREADY,
    output var logic [5:0]    SAXIGP5BID,
    output var logic [1:0]    SAXIGP5BRESP,
    output var logic          SAXIGP5BVALID,
    output var logic [3:0]    SAXIGP5RACOUNT,
    output var logic [7:0]    SAXIGP5RCOUNT,
    output var logic [127:0]  SAXIGP5RDATA,
    output var logic [5:0]    SAXIGP5RID,
    output var logic          SAXIGP5RLAST,
    output var logic [1:0]    SAXIGP5RRESP,
    output var logic          SAXIGP5RVALID,
    output var logic [3:0]    SAXIGP5WACOUNT,
    output var logic [7:0]    SAXIGP5WCOUNT,
    output var logic          SAXIGP5WREADY,
    output var logic          SAXIGP6ARREADY,
    output var logic          SAXIGP6AWREADY,
    output var logic [5:0]    SAXIGP6BID,
    output var logic [1:0]    SAXIGP6BRESP,
    output var logic          SAXIGP6BVALID,
    output var logic [3:0]    SAXIGP6RACOUNT,
    output var logic [7:0]    SAXIGP6RCOUNT,
    output var logic [127:0]  SAXIGP6RDATA,
    output var logic [5:0]    SAXIGP6RID,
    output var logic          SAXIGP6RLAST,
    output var logic [1:0]    SAXIGP6RRESP,
    output var logic          SAXIGP6RVALID,
    output var logic [3:0]    SAXIGP6WACOUNT,
    output var logic [7:0]    SAXIGP6WCOUNT,
    output var logic          SAXIGP6WREADY,
    inout  wire       [3:0]    PSS_ALTO_CORE_PAD_BOOTMODE,
    inout  wire                PSS_ALTO_CORE_PAD_CLK,
    inout  wire                PSS_ALTO_CORE_PAD_DONEB,
    inout  wire       [17:0]   PSS_ALTO_CORE_PAD_DRAMA,
    inout  wire                PSS_ALTO_CORE_PAD_DRAMACTN,
    inout  wire                PSS_ALTO_CORE_PAD_DRAMALERTN,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMBA,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMBG,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMCK,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMCKE,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMCKN,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMCSN,
    inout  wire       [8:0]    PSS_ALTO_CORE_PAD_DRAMDM,
    inout  wire       [71:0]   PSS_ALTO_CORE_PAD_DRAMDQ,
    inout  wire       [8:0]    PSS_ALTO_CORE_PAD_DRAMDQS,
    inout  wire       [8:0]    PSS_ALTO_CORE_PAD_DRAMDQSN,
    inout  wire       [1:0]    PSS_ALTO_CORE_PAD_DRAMODT,
    inout  wire                PSS_ALTO_CORE_PAD_DRAMPARITY,
    inout  wire                PSS_ALTO_CORE_PAD_DRAMRAMRSTN,
    inout  wire                PSS_ALTO_CORE_PAD_ERROROUT,
    inout  wire                PSS_ALTO_CORE_PAD_ERRORSTATUS,
    inout  wire                PSS_ALTO_CORE_PAD_INITB,
    inout  wire                PSS_ALTO_CORE_PAD_JTAGTCK,
    inout  wire                PSS_ALTO_CORE_PAD_JTAGTDI,
    inout  wire                PSS_ALTO_CORE_PAD_JTAGTDO,
    inout  wire                PSS_ALTO_CORE_PAD_JTAGTMS,
    inout  wire       [77:0]   PSS_ALTO_CORE_PAD_MIO,
    inout  wire                PSS_ALTO_CORE_PAD_PORB,
    inout  wire                PSS_ALTO_CORE_PAD_PROGB,
    inout  wire                PSS_ALTO_CORE_PAD_RCALIBINOUT,
    inout  wire                PSS_ALTO_CORE_PAD_SRSTB,
    inout  wire                PSS_ALTO_CORE_PAD_ZQ,
    input  var logic [7:0]    ADMAFCICLK,
    input  var logic          AIBPMUAFIFMFPDACK,
    input  var logic          AIBPMUAFIFMLPDACK,
    input  var logic          DDRCEXTREFRESHRANK0REQ,
    input  var logic          DDRCEXTREFRESHRANK1REQ,
    input  var logic          DDRCREFRESHPLCLK,
    input  var logic          DPAUXDATAIN,
    input  var logic          DPEXTERNALCUSTOMEVENT1,
    input  var logic          DPEXTERNALCUSTOMEVENT2,
    input  var logic          DPEXTERNALVSYNCEVENT,
    input  var logic          DPHOTPLUGDETECT,
    input  var logic [7:0]    DPLIVEGFXALPHAIN,
    input  var logic [35:0]   DPLIVEGFXPIXEL1IN,
    input  var logic          DPLIVEVIDEOINDE,
    input  var logic          DPLIVEVIDEOINHSYNC,
    input  var logic [35:0]   DPLIVEVIDEOINPIXEL1,
    input  var logic          DPLIVEVIDEOINVSYNC,
    input  var logic          DPMAXISMIXEDAUDIOTREADY,
    input  var logic          DPSAXISAUDIOCLK,
    input  var logic [31:0]   DPSAXISAUDIOTDATA,
    input  var logic          DPSAXISAUDIOTID,
    input  var logic          DPSAXISAUDIOTVALID,
    input  var logic          DPVIDEOINCLK,
    input  var logic          EMIOCAN0PHYRX,
    input  var logic          EMIOCAN1PHYRX,
    input  var logic          EMIOENET0DMATXSTATUSTOG,
    input  var logic          EMIOENET0EXTINTIN,
    input  var logic          EMIOENET0GMIICOL,
    input  var logic          EMIOENET0GMIICRS,
    input  var logic          EMIOENET0GMIIRXCLK,
    input  var logic [7:0]    EMIOENET0GMIIRXD,
    input  var logic          EMIOENET0GMIIRXDV,
    input  var logic          EMIOENET0GMIIRXER,
    input  var logic          EMIOENET0GMIITXCLK,
    input  var logic          EMIOENET0MDIOI,
    input  var logic          EMIOENET0RXWOVERFLOW,
    input  var logic          EMIOENET0TXRCONTROL,
    input  var logic [7:0]    EMIOENET0TXRDATA,
    input  var logic          EMIOENET0TXRDATARDY,
    input  var logic          EMIOENET0TXREOP,
    input  var logic          EMIOENET0TXRERR,
    input  var logic          EMIOENET0TXRFLUSHED,
    input  var logic          EMIOENET0TXRSOP,
    input  var logic          EMIOENET0TXRUNDERFLOW,
    input  var logic          EMIOENET0TXRVALID,
    input  var logic          EMIOENET1DMATXSTATUSTOG,
    input  var logic          EMIOENET1EXTINTIN,
    input  var logic          EMIOENET1GMIICOL,
    input  var logic          EMIOENET1GMIICRS,
    input  var logic          EMIOENET1GMIIRXCLK,
    input  var logic [7:0]    EMIOENET1GMIIRXD,
    input  var logic          EMIOENET1GMIIRXDV,
    input  var logic          EMIOENET1GMIIRXER,
    input  var logic          EMIOENET1GMIITXCLK,
    input  var logic          EMIOENET1MDIOI,
    input  var logic          EMIOENET1RXWOVERFLOW,
    input  var logic          EMIOENET1TXRCONTROL,
    input  var logic [7:0]    EMIOENET1TXRDATA,
    input  var logic          EMIOENET1TXRDATARDY,
    input  var logic          EMIOENET1TXREOP,
    input  var logic          EMIOENET1TXRERR,
    input  var logic          EMIOENET1TXRFLUSHED,
    input  var logic          EMIOENET1TXRSOP,
    input  var logic          EMIOENET1TXRUNDERFLOW,
    input  var logic          EMIOENET1TXRVALID,
    input  var logic          EMIOENET2DMATXSTATUSTOG,
    input  var logic          EMIOENET2EXTINTIN,
    input  var logic          EMIOENET2GMIICOL,
    input  var logic          EMIOENET2GMIICRS,
    input  var logic          EMIOENET2GMIIRXCLK,
    input  var logic [7:0]    EMIOENET2GMIIRXD,
    input  var logic          EMIOENET2GMIIRXDV,
    input  var logic          EMIOENET2GMIIRXER,
    input  var logic          EMIOENET2GMIITXCLK,
    input  var logic          EMIOENET2MDIOI,
    input  var logic          EMIOENET2RXWOVERFLOW,
    input  var logic          EMIOENET2TXRCONTROL,
    input  var logic [7:0]    EMIOENET2TXRDATA,
    input  var logic          EMIOENET2TXRDATARDY,
    input  var logic          EMIOENET2TXREOP,
    input  var logic          EMIOENET2TXRERR,
    input  var logic          EMIOENET2TXRFLUSHED,
    input  var logic          EMIOENET2TXRSOP,
    input  var logic          EMIOENET2TXRUNDERFLOW,
    input  var logic          EMIOENET2TXRVALID,
    input  var logic          EMIOENET3DMATXSTATUSTOG,
    input  var logic          EMIOENET3EXTINTIN,
    input  var logic          EMIOENET3GMIICOL,
    input  var logic          EMIOENET3GMIICRS,
    input  var logic          EMIOENET3GMIIRXCLK,
    input  var logic [7:0]    EMIOENET3GMIIRXD,
    input  var logic          EMIOENET3GMIIRXDV,
    input  var logic          EMIOENET3GMIIRXER,
    input  var logic          EMIOENET3GMIITXCLK,
    input  var logic          EMIOENET3MDIOI,
    input  var logic          EMIOENET3RXWOVERFLOW,
    input  var logic          EMIOENET3TXRCONTROL,
    input  var logic [7:0]    EMIOENET3TXRDATA,
    input  var logic          EMIOENET3TXRDATARDY,
    input  var logic          EMIOENET3TXREOP,
    input  var logic          EMIOENET3TXRERR,
    input  var logic          EMIOENET3TXRFLUSHED,
    input  var logic          EMIOENET3TXRSOP,
    input  var logic          EMIOENET3TXRUNDERFLOW,
    input  var logic          EMIOENET3TXRVALID,
    input  var logic          EMIOENETTSUCLK,
    input  var logic [1:0]    EMIOGEM0TSUINCCTRL,
    input  var logic [1:0]    EMIOGEM1TSUINCCTRL,
    input  var logic [1:0]    EMIOGEM2TSUINCCTRL,
    input  var logic [1:0]    EMIOGEM3TSUINCCTRL,
    input  var logic [95:0]   EMIOGPIOI,
    input  var logic          EMIOHUBPORTOVERCRNTUSB20,
    input  var logic          EMIOHUBPORTOVERCRNTUSB21,
    input  var logic          EMIOHUBPORTOVERCRNTUSB30,
    input  var logic          EMIOHUBPORTOVERCRNTUSB31,
    input  var logic          EMIOI2C0SCLI,
    input  var logic          EMIOI2C0SDAI,
    input  var logic          EMIOI2C1SCLI,
    input  var logic          EMIOI2C1SDAI,
    input  var logic          EMIOSDIO0CDN,
    input  var logic          EMIOSDIO0CMDIN,
    input  var logic [7:0]    EMIOSDIO0DATAIN,
    input  var logic          EMIOSDIO0FBCLKIN,
    input  var logic          EMIOSDIO0WP,
    input  var logic          EMIOSDIO1CDN,
    input  var logic          EMIOSDIO1CMDIN,
    input  var logic [7:0]    EMIOSDIO1DATAIN,
    input  var logic          EMIOSDIO1FBCLKIN,
    input  var logic          EMIOSDIO1WP,
    input  var logic          EMIOSPI0MI,
    input  var logic          EMIOSPI0SCLKI,
    input  var logic          EMIOSPI0SI,
    input  var logic          EMIOSPI0SSIN,
    input  var logic          EMIOSPI1MI,
    input  var logic          EMIOSPI1SCLKI,
    input  var logic          EMIOSPI1SI,
    input  var logic          EMIOSPI1SSIN,
    input  var logic [2:0]    EMIOTTC0CLKI,
    input  var logic [2:0]    EMIOTTC1CLKI,
    input  var logic [2:0]    EMIOTTC2CLKI,
    input  var logic [2:0]    EMIOTTC3CLKI,
    input  var logic          EMIOUART0CTSN,
    input  var logic          EMIOUART0DCDN,
    input  var logic          EMIOUART0DSRN,
    input  var logic          EMIOUART0RIN,
    input  var logic          EMIOUART0RX,
    input  var logic          EMIOUART1CTSN,
    input  var logic          EMIOUART1DCDN,
    input  var logic          EMIOUART1DSRN,
    input  var logic          EMIOUART1RIN,
    input  var logic          EMIOUART1RX,
    input  var logic          EMIOWDT0CLKI,
    input  var logic          EMIOWDT1CLKI,
    input  var logic          FMIOGEM0FIFORXCLKFROMPL,
    input  var logic          FMIOGEM0FIFOTXCLKFROMPL,
    input  var logic          FMIOGEM0SIGNALDETECT,
    input  var logic          FMIOGEM1FIFORXCLKFROMPL,
    input  var logic          FMIOGEM1FIFOTXCLKFROMPL,
    input  var logic          FMIOGEM1SIGNALDETECT,
    input  var logic          FMIOGEM2FIFORXCLKFROMPL,
    input  var logic          FMIOGEM2FIFOTXCLKFROMPL,
    input  var logic          FMIOGEM2SIGNALDETECT,
    input  var logic          FMIOGEM3FIFORXCLKFROMPL,
    input  var logic          FMIOGEM3FIFOTXCLKFROMPL,
    input  var logic          FMIOGEM3SIGNALDETECT,
    input  var logic          FMIOGEMTSUCLKFROMPL,
    input  var logic [31:0]   FTMGPI,
    input  var logic [7:0]    GDMAFCICLK,
    input  var logic          MAXIGP0ACLK,
    input  var logic          MAXIGP0ARREADY,
    input  var logic          MAXIGP0AWREADY,
    input  var logic [15:0]   MAXIGP0BID,
    input  var logic [1:0]    MAXIGP0BRESP,
    input  var logic          MAXIGP0BVALID,
    input  var logic [127:0]  MAXIGP0RDATA,
    input  var logic [15:0]   MAXIGP0RID,
    input  var logic          MAXIGP0RLAST,
    input  var logic [1:0]    MAXIGP0RRESP,
    input  var logic          MAXIGP0RVALID,
    input  var logic          MAXIGP0WREADY,
    input  var logic          MAXIGP1ACLK,
    input  var logic          MAXIGP1ARREADY,
    input  var logic          MAXIGP1AWREADY,
    input  var logic [15:0]   MAXIGP1BID,
    input  var logic [1:0]    MAXIGP1BRESP,
    input  var logic          MAXIGP1BVALID,
    input  var logic [127:0]  MAXIGP1RDATA,
    input  var logic [15:0]   MAXIGP1RID,
    input  var logic          MAXIGP1RLAST,
    input  var logic [1:0]    MAXIGP1RRESP,
    input  var logic          MAXIGP1RVALID,
    input  var logic          MAXIGP1WREADY,
    input  var logic          MAXIGP2ACLK,
    input  var logic          MAXIGP2ARREADY,
    input  var logic          MAXIGP2AWREADY,
    input  var logic [15:0]   MAXIGP2BID,
    input  var logic [1:0]    MAXIGP2BRESP,
    input  var logic          MAXIGP2BVALID,
    input  var logic [127:0]  MAXIGP2RDATA,
    input  var logic [15:0]   MAXIGP2RID,
    input  var logic          MAXIGP2RLAST,
    input  var logic [1:0]    MAXIGP2RRESP,
    input  var logic          MAXIGP2RVALID,
    input  var logic          MAXIGP2WREADY,
    input  var logic          NFIQ0LPDRPU,
    input  var logic          NFIQ1LPDRPU,
    input  var logic          NIRQ0LPDRPU,
    input  var logic          NIRQ1LPDRPU,
    input  var logic [7:0]    PL2ADMACVLD,
    input  var logic [7:0]    PL2ADMATACK,
    input  var logic [7:0]    PL2GDMACVLD,
    input  var logic [7:0]    PL2GDMATACK,
    input  var logic          PLACECLK,
    input  var logic          PLACPINACT,
    input  var logic [3:0]    PLFPGASTOP,
    input  var logic [2:0]    PLLAUXREFCLKFPD,
    input  var logic [1:0]    PLLAUXREFCLKLPD,
    input  var logic [31:0]   PLPMUGPI,
    input  var logic [3:0]    PLPSAPUGICFIQ,
    input  var logic [3:0]    PLPSAPUGICIRQ,
    input  var logic          PLPSEVENTI,
    input  var logic [7:0]    PLPSIRQ0,
    input  var logic [7:0]    PLPSIRQ1,
    input  var logic          PLPSTRACECLK,
    input  var logic [3:0]    PLPSTRIGACK,
    input  var logic [3:0]    PLPSTRIGGER,
    input  var logic [3:0]    PMUERRORFROMPL,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXN0IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXN1IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXN2IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXN3IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXP0IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXP1IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXP2IN,
    input  var logic          PSS_ALTO_CORE_PAD_MGTRXP3IN,
    input  var logic          PSS_ALTO_CORE_PAD_PADI,
    input  var logic          PSS_ALTO_CORE_PAD_REFN0IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFN1IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFN2IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFN3IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFP0IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFP1IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFP2IN,
    input  var logic          PSS_ALTO_CORE_PAD_REFP3IN,
    input  var logic          RPUEVENTI0,
    input  var logic          RPUEVENTI1,
    input  var logic          SACEFPDACREADY,
    input  var logic [43:0]   SACEFPDARADDR,
    input  var logic [1:0]    SACEFPDARBAR,
    input  var logic [1:0]    SACEFPDARBURST,
    input  var logic [3:0]    SACEFPDARCACHE,
    input  var logic [1:0]    SACEFPDARDOMAIN,
    input  var logic [5:0]    SACEFPDARID,
    input  var logic [7:0]    SACEFPDARLEN,
    input  var logic          SACEFPDARLOCK,
    input  var logic [2:0]    SACEFPDARPROT,
    input  var logic [3:0]    SACEFPDARQOS,
    input  var logic [3:0]    SACEFPDARREGION,
    input  var logic [2:0]    SACEFPDARSIZE,
    input  var logic [3:0]    SACEFPDARSNOOP,
    input  var logic [15:0]   SACEFPDARUSER,
    input  var logic          SACEFPDARVALID,
    input  var logic [43:0]   SACEFPDAWADDR,
    input  var logic [1:0]    SACEFPDAWBAR,
    input  var logic [1:0]    SACEFPDAWBURST,
    input  var logic [3:0]    SACEFPDAWCACHE,
    input  var logic [1:0]    SACEFPDAWDOMAIN,
    input  var logic [5:0]    SACEFPDAWID,
    input  var logic [7:0]    SACEFPDAWLEN,
    input  var logic          SACEFPDAWLOCK,
    input  var logic [2:0]    SACEFPDAWPROT,
    input  var logic [3:0]    SACEFPDAWQOS,
    input  var logic [3:0]    SACEFPDAWREGION,
    input  var logic [2:0]    SACEFPDAWSIZE,
    input  var logic [2:0]    SACEFPDAWSNOOP,
    input  var logic [15:0]   SACEFPDAWUSER,
    input  var logic          SACEFPDAWVALID,
    input  var logic          SACEFPDBREADY,
    input  var logic [127:0]  SACEFPDCDDATA,
    input  var logic          SACEFPDCDLAST,
    input  var logic          SACEFPDCDVALID,
    input  var logic [4:0]    SACEFPDCRRESP,
    input  var logic          SACEFPDCRVALID,
    input  var logic          SACEFPDRACK,
    input  var logic          SACEFPDRREADY,
    input  var logic          SACEFPDWACK,
    input  var logic [127:0]  SACEFPDWDATA,
    input  var logic          SACEFPDWLAST,
    input  var logic [15:0]   SACEFPDWSTRB,
    input  var logic          SACEFPDWUSER,
    input  var logic          SACEFPDWVALID,
    input  var logic          SAXIACPACLK,
    input  var logic [39:0]   SAXIACPARADDR,
    input  var logic [1:0]    SAXIACPARBURST,
    input  var logic [3:0]    SAXIACPARCACHE,
    input  var logic [4:0]    SAXIACPARID,
    input  var logic [7:0]    SAXIACPARLEN,
    input  var logic          SAXIACPARLOCK,
    input  var logic [2:0]    SAXIACPARPROT,
    input  var logic [3:0]    SAXIACPARQOS,
    input  var logic [2:0]    SAXIACPARSIZE,
    input  var logic [1:0]    SAXIACPARUSER,
    input  var logic          SAXIACPARVALID,
    input  var logic [39:0]   SAXIACPAWADDR,
    input  var logic [1:0]    SAXIACPAWBURST,
    input  var logic [3:0]    SAXIACPAWCACHE,
    input  var logic [4:0]    SAXIACPAWID,
    input  var logic [7:0]    SAXIACPAWLEN,
    input  var logic          SAXIACPAWLOCK,
    input  var logic [2:0]    SAXIACPAWPROT,
    input  var logic [3:0]    SAXIACPAWQOS,
    input  var logic [2:0]    SAXIACPAWSIZE,
    input  var logic [1:0]    SAXIACPAWUSER,
    input  var logic          SAXIACPAWVALID,
    input  var logic          SAXIACPBREADY,
    input  var logic          SAXIACPRREADY,
    input  var logic [127:0]  SAXIACPWDATA,
    input  var logic          SAXIACPWLAST,
    input  var logic [15:0]   SAXIACPWSTRB,
    input  var logic          SAXIACPWVALID,
    input  var logic [48:0]   SAXIGP0ARADDR,
    input  var logic [1:0]    SAXIGP0ARBURST,
    input  var logic [3:0]    SAXIGP0ARCACHE,
    input  var logic [5:0]    SAXIGP0ARID,
    input  var logic [7:0]    SAXIGP0ARLEN,
    input  var logic          SAXIGP0ARLOCK,
    input  var logic [2:0]    SAXIGP0ARPROT,
    input  var logic [3:0]    SAXIGP0ARQOS,
    input  var logic [2:0]    SAXIGP0ARSIZE,
    input  var logic          SAXIGP0ARUSER,
    input  var logic          SAXIGP0ARVALID,
    input  var logic [48:0]   SAXIGP0AWADDR,
    input  var logic [1:0]    SAXIGP0AWBURST,
    input  var logic [3:0]    SAXIGP0AWCACHE,
    input  var logic [5:0]    SAXIGP0AWID,
    input  var logic [7:0]    SAXIGP0AWLEN,
    input  var logic          SAXIGP0AWLOCK,
    input  var logic [2:0]    SAXIGP0AWPROT,
    input  var logic [3:0]    SAXIGP0AWQOS,
    input  var logic [2:0]    SAXIGP0AWSIZE,
    input  var logic          SAXIGP0AWUSER,
    input  var logic          SAXIGP0AWVALID,
    input  var logic          SAXIGP0BREADY,
    input  var logic          SAXIGP0RCLK,
    input  var logic          SAXIGP0RREADY,
    input  var logic          SAXIGP0WCLK,
    input  var logic [127:0]  SAXIGP0WDATA,
    input  var logic          SAXIGP0WLAST,
    input  var logic [15:0]   SAXIGP0WSTRB,
    input  var logic          SAXIGP0WVALID,
    input  var logic [48:0]   SAXIGP1ARADDR,
    input  var logic [1:0]    SAXIGP1ARBURST,
    input  var logic [3:0]    SAXIGP1ARCACHE,
    input  var logic [5:0]    SAXIGP1ARID,
    input  var logic [7:0]    SAXIGP1ARLEN,
    input  var logic          SAXIGP1ARLOCK,
    input  var logic [2:0]    SAXIGP1ARPROT,
    input  var logic [3:0]    SAXIGP1ARQOS,
    input  var logic [2:0]    SAXIGP1ARSIZE,
    input  var logic          SAXIGP1ARUSER,
    input  var logic          SAXIGP1ARVALID,
    input  var logic [48:0]   SAXIGP1AWADDR,
    input  var logic [1:0]    SAXIGP1AWBURST,
    input  var logic [3:0]    SAXIGP1AWCACHE,
    input  var logic [5:0]    SAXIGP1AWID,
    input  var logic [7:0]    SAXIGP1AWLEN,
    input  var logic          SAXIGP1AWLOCK,
    input  var logic [2:0]    SAXIGP1AWPROT,
    input  var logic [3:0]    SAXIGP1AWQOS,
    input  var logic [2:0]    SAXIGP1AWSIZE,
    input  var logic          SAXIGP1AWUSER,
    input  var logic          SAXIGP1AWVALID,
    input  var logic          SAXIGP1BREADY,
    input  var logic          SAXIGP1RCLK,
    input  var logic          SAXIGP1RREADY,
    input  var logic          SAXIGP1WCLK,
    input  var logic [127:0]  SAXIGP1WDATA,
    input  var logic          SAXIGP1WLAST,
    input  var logic [15:0]   SAXIGP1WSTRB,
    input  var logic          SAXIGP1WVALID,
    input  var logic [48:0]   SAXIGP2ARADDR,
    input  var logic [1:0]    SAXIGP2ARBURST,
    input  var logic [3:0]    SAXIGP2ARCACHE,
    input  var logic [5:0]    SAXIGP2ARID,
    input  var logic [7:0]    SAXIGP2ARLEN,
    input  var logic          SAXIGP2ARLOCK,
    input  var logic [2:0]    SAXIGP2ARPROT,
    input  var logic [3:0]    SAXIGP2ARQOS,
    input  var logic [2:0]    SAXIGP2ARSIZE,
    input  var logic          SAXIGP2ARUSER,
    input  var logic          SAXIGP2ARVALID,
    input  var logic [48:0]   SAXIGP2AWADDR,
    input  var logic [1:0]    SAXIGP2AWBURST,
    input  var logic [3:0]    SAXIGP2AWCACHE,
    input  var logic [5:0]    SAXIGP2AWID,
    input  var logic [7:0]    SAXIGP2AWLEN,
    input  var logic          SAXIGP2AWLOCK,
    input  var logic [2:0]    SAXIGP2AWPROT,
    input  var logic [3:0]    SAXIGP2AWQOS,
    input  var logic [2:0]    SAXIGP2AWSIZE,
    input  var logic          SAXIGP2AWUSER,
    input  var logic          SAXIGP2AWVALID,
    input  var logic          SAXIGP2BREADY,
    input  var logic          SAXIGP2RCLK,
    input  var logic          SAXIGP2RREADY,
    input  var logic          SAXIGP2WCLK,
    input  var logic [127:0]  SAXIGP2WDATA,
    input  var logic          SAXIGP2WLAST,
    input  var logic [15:0]   SAXIGP2WSTRB,
    input  var logic          SAXIGP2WVALID,
    input  var logic [48:0]   SAXIGP3ARADDR,
    input  var logic [1:0]    SAXIGP3ARBURST,
    input  var logic [3:0]    SAXIGP3ARCACHE,
    input  var logic [5:0]    SAXIGP3ARID,
    input  var logic [7:0]    SAXIGP3ARLEN,
    input  var logic          SAXIGP3ARLOCK,
    input  var logic [2:0]    SAXIGP3ARPROT,
    input  var logic [3:0]    SAXIGP3ARQOS,
    input  var logic [2:0]    SAXIGP3ARSIZE,
    input  var logic          SAXIGP3ARUSER,
    input  var logic          SAXIGP3ARVALID,
    input  var logic [48:0]   SAXIGP3AWADDR,
    input  var logic [1:0]    SAXIGP3AWBURST,
    input  var logic [3:0]    SAXIGP3AWCACHE,
    input  var logic [5:0]    SAXIGP3AWID,
    input  var logic [7:0]    SAXIGP3AWLEN,
    input  var logic          SAXIGP3AWLOCK,
    input  var logic [2:0]    SAXIGP3AWPROT,
    input  var logic [3:0]    SAXIGP3AWQOS,
    input  var logic [2:0]    SAXIGP3AWSIZE,
    input  var logic          SAXIGP3AWUSER,
    input  var logic          SAXIGP3AWVALID,
    input  var logic          SAXIGP3BREADY,
    input  var logic          SAXIGP3RCLK,
    input  var logic          SAXIGP3RREADY,
    input  var logic          SAXIGP3WCLK,
    input  var logic [127:0]  SAXIGP3WDATA,
    input  var logic          SAXIGP3WLAST,
    input  var logic [15:0]   SAXIGP3WSTRB,
    input  var logic          SAXIGP3WVALID,
    input  var logic [48:0]   SAXIGP4ARADDR,
    input  var logic [1:0]    SAXIGP4ARBURST,
    input  var logic [3:0]    SAXIGP4ARCACHE,
    input  var logic [5:0]    SAXIGP4ARID,
    input  var logic [7:0]    SAXIGP4ARLEN,
    input  var logic          SAXIGP4ARLOCK,
    input  var logic [2:0]    SAXIGP4ARPROT,
    input  var logic [3:0]    SAXIGP4ARQOS,
    input  var logic [2:0]    SAXIGP4ARSIZE,
    input  var logic          SAXIGP4ARUSER,
    input  var logic          SAXIGP4ARVALID,
    input  var logic [48:0]   SAXIGP4AWADDR,
    input  var logic [1:0]    SAXIGP4AWBURST,
    input  var logic [3:0]    SAXIGP4AWCACHE,
    input  var logic [5:0]    SAXIGP4AWID,
    input  var logic [7:0]    SAXIGP4AWLEN,
    input  var logic          SAXIGP4AWLOCK,
    input  var logic [2:0]    SAXIGP4AWPROT,
    input  var logic [3:0]    SAXIGP4AWQOS,
    input  var logic [2:0]    SAXIGP4AWSIZE,
    input  var logic          SAXIGP4AWUSER,
    input  var logic          SAXIGP4AWVALID,
    input  var logic          SAXIGP4BREADY,
    input  var logic          SAXIGP4RCLK,
    input  var logic          SAXIGP4RREADY,
    input  var logic          SAXIGP4WCLK,
    input  var logic [127:0]  SAXIGP4WDATA,
    input  var logic          SAXIGP4WLAST,
    input  var logic [15:0]   SAXIGP4WSTRB,
    input  var logic          SAXIGP4WVALID,
    input  var logic [48:0]   SAXIGP5ARADDR,
    input  var logic [1:0]    SAXIGP5ARBURST,
    input  var logic [3:0]    SAXIGP5ARCACHE,
    input  var logic [5:0]    SAXIGP5ARID,
    input  var logic [7:0]    SAXIGP5ARLEN,
    input  var logic          SAXIGP5ARLOCK,
    input  var logic [2:0]    SAXIGP5ARPROT,
    input  var logic [3:0]    SAXIGP5ARQOS,
    input  var logic [2:0]    SAXIGP5ARSIZE,
    input  var logic          SAXIGP5ARUSER,
    input  var logic          SAXIGP5ARVALID,
    input  var logic [48:0]   SAXIGP5AWADDR,
    input  var logic [1:0]    SAXIGP5AWBURST,
    input  var logic [3:0]    SAXIGP5AWCACHE,
    input  var logic [5:0]    SAXIGP5AWID,
    input  var logic [7:0]    SAXIGP5AWLEN,
    input  var logic          SAXIGP5AWLOCK,
    input  var logic [2:0]    SAXIGP5AWPROT,
    input  var logic [3:0]    SAXIGP5AWQOS,
    input  var logic [2:0]    SAXIGP5AWSIZE,
    input  var logic          SAXIGP5AWUSER,
    input  var logic          SAXIGP5AWVALID,
    input  var logic          SAXIGP5BREADY,
    input  var logic          SAXIGP5RCLK,
    input  var logic          SAXIGP5RREADY,
    input  var logic          SAXIGP5WCLK,
    input  var logic [127:0]  SAXIGP5WDATA,
    input  var logic          SAXIGP5WLAST,
    input  var logic [15:0]   SAXIGP5WSTRB,
    input  var logic          SAXIGP5WVALID,
    input  var logic [48:0]   SAXIGP6ARADDR,
    input  var logic [1:0]    SAXIGP6ARBURST,
    input  var logic [3:0]    SAXIGP6ARCACHE,
    input  var logic [5:0]    SAXIGP6ARID,
    input  var logic [7:0]    SAXIGP6ARLEN,
    input  var logic          SAXIGP6ARLOCK,
    input  var logic [2:0]    SAXIGP6ARPROT,
    input  var logic [3:0]    SAXIGP6ARQOS,
    input  var logic [2:0]    SAXIGP6ARSIZE,
    input  var logic          SAXIGP6ARUSER,
    input  var logic          SAXIGP6ARVALID,
    input  var logic [48:0]   SAXIGP6AWADDR,
    input  var logic [1:0]    SAXIGP6AWBURST,
    input  var logic [3:0]    SAXIGP6AWCACHE,
    input  var logic [5:0]    SAXIGP6AWID,
    input  var logic [7:0]    SAXIGP6AWLEN,
    input  var logic          SAXIGP6AWLOCK,
    input  var logic [2:0]    SAXIGP6AWPROT,
    input  var logic [3:0]    SAXIGP6AWQOS,
    input  var logic [2:0]    SAXIGP6AWSIZE,
    input  var logic          SAXIGP6AWUSER,
    input  var logic          SAXIGP6AWVALID,
    input  var logic          SAXIGP6BREADY,
    input  var logic          SAXIGP6RCLK,
    input  var logic          SAXIGP6RREADY,
    input  var logic          SAXIGP6WCLK,
    input  var logic [127:0]  SAXIGP6WDATA,
    input  var logic          SAXIGP6WLAST,
    input  var logic [15:0]   SAXIGP6WSTRB,
    input  var logic          SAXIGP6WVALID,
    input  var logic [59:0]   STMEVENT
);

  assign ADMA2PLCACK = 8'b0;
  assign ADMA2PLTVLD = 8'b0;
  assign DPAUDIOREFCLK = 1'b0;
  assign DPAUXDATAOEN = 1'b0;
  assign DPAUXDATAOUT = 1'b0;
  assign DPLIVEVIDEODEOUT = 1'b0;
  assign DPMAXISMIXEDAUDIOTDATA = 32'b0;
  assign DPMAXISMIXEDAUDIOTID = 1'b0;
  assign DPMAXISMIXEDAUDIOTVALID = 1'b0;
  assign DPSAXISAUDIOTREADY = 1'b0;
  assign DPVIDEOOUTHSYNC = 1'b0;
  assign DPVIDEOOUTPIXEL1 = 36'b0;
  assign DPVIDEOOUTVSYNC = 1'b0;
  assign DPVIDEOREFCLK = 1'b0;
  assign EMIOCAN0PHYTX = 1'b0;
  assign EMIOCAN1PHYTX = 1'b0;
  assign EMIOENET0DMABUSWIDTH = 2'b0;
  assign EMIOENET0DMATXENDTOG = 1'b0;
  assign EMIOENET0GEMTSUTIMERCNT = 94'b0;
  assign EMIOENET0GMIITXD = 8'b0;
  assign EMIOENET0GMIITXEN = 1'b0;
  assign EMIOENET0GMIITXER = 1'b0;
  assign EMIOENET0MDIOMDC = 1'b0;
  assign EMIOENET0MDIOO = 1'b0;
  assign EMIOENET0MDIOTN = 1'b0;
  assign EMIOENET0RXWDATA = 8'b0;
  assign EMIOENET0RXWEOP = 1'b0;
  assign EMIOENET0RXWERR = 1'b0;
  assign EMIOENET0RXWFLUSH = 1'b0;
  assign EMIOENET0RXWSOP = 1'b0;
  assign EMIOENET0RXWSTATUS = 45'b0;
  assign EMIOENET0RXWWR = 1'b0;
  assign EMIOENET0SPEEDMODE = 3'b0;
  assign EMIOENET0TXRRD = 1'b0;
  assign EMIOENET0TXRSTATUS = 4'b0;
  assign EMIOENET1DMABUSWIDTH = 2'b0;
  assign EMIOENET1DMATXENDTOG = 1'b0;
  assign EMIOENET1GMIITXD = 8'b0;
  assign EMIOENET1GMIITXEN = 1'b0;
  assign EMIOENET1GMIITXER = 1'b0;
  assign EMIOENET1MDIOMDC = 1'b0;
  assign EMIOENET1MDIOO = 1'b0;
  assign EMIOENET1MDIOTN = 1'b0;
  assign EMIOENET1RXWDATA = 8'b0;
  assign EMIOENET1RXWEOP = 1'b0;
  assign EMIOENET1RXWERR = 1'b0;
  assign EMIOENET1RXWFLUSH = 1'b0;
  assign EMIOENET1RXWSOP = 1'b0;
  assign EMIOENET1RXWSTATUS = 45'b0;
  assign EMIOENET1RXWWR = 1'b0;
  assign EMIOENET1SPEEDMODE = 3'b0;
  assign EMIOENET1TXRRD = 1'b0;
  assign EMIOENET1TXRSTATUS = 4'b0;
  assign EMIOENET2DMABUSWIDTH = 2'b0;
  assign EMIOENET2DMATXENDTOG = 1'b0;
  assign EMIOENET2GMIITXD = 8'b0;
  assign EMIOENET2GMIITXEN = 1'b0;
  assign EMIOENET2GMIITXER = 1'b0;
  assign EMIOENET2MDIOMDC = 1'b0;
  assign EMIOENET2MDIOO = 1'b0;
  assign EMIOENET2MDIOTN = 1'b0;
  assign EMIOENET2RXWDATA = 8'b0;
  assign EMIOENET2RXWEOP = 1'b0;
  assign EMIOENET2RXWERR = 1'b0;
  assign EMIOENET2RXWFLUSH = 1'b0;
  assign EMIOENET2RXWSOP = 1'b0;
  assign EMIOENET2RXWSTATUS = 45'b0;
  assign EMIOENET2RXWWR = 1'b0;
  assign EMIOENET2SPEEDMODE = 3'b0;
  assign EMIOENET2TXRRD = 1'b0;
  assign EMIOENET2TXRSTATUS = 4'b0;
  assign EMIOENET3DMABUSWIDTH = 2'b0;
  assign EMIOENET3DMATXENDTOG = 1'b0;
  assign EMIOENET3GMIITXD = 8'b0;
  assign EMIOENET3GMIITXEN = 1'b0;
  assign EMIOENET3GMIITXER = 1'b0;
  assign EMIOENET3MDIOMDC = 1'b0;
  assign EMIOENET3MDIOO = 1'b0;
  assign EMIOENET3MDIOTN = 1'b0;
  assign EMIOENET3RXWDATA = 8'b0;
  assign EMIOENET3RXWEOP = 1'b0;
  assign EMIOENET3RXWERR = 1'b0;
  assign EMIOENET3RXWFLUSH = 1'b0;
  assign EMIOENET3RXWSOP = 1'b0;
  assign EMIOENET3RXWSTATUS = 45'b0;
  assign EMIOENET3RXWWR = 1'b0;
  assign EMIOENET3SPEEDMODE = 3'b0;
  assign EMIOENET3TXRRD = 1'b0;
  assign EMIOENET3TXRSTATUS = 4'b0;
  assign EMIOGEM0DELAYREQRX = 1'b0;
  assign EMIOGEM0DELAYREQTX = 1'b0;
  assign EMIOGEM0PDELAYREQRX = 1'b0;
  assign EMIOGEM0PDELAYREQTX = 1'b0;
  assign EMIOGEM0PDELAYRESPRX = 1'b0;
  assign EMIOGEM0PDELAYRESPTX = 1'b0;
  assign EMIOGEM0RXSOF = 1'b0;
  assign EMIOGEM0SYNCFRAMERX = 1'b0;
  assign EMIOGEM0SYNCFRAMETX = 1'b0;
  assign EMIOGEM0TSUTIMERCMPVAL = 1'b0;
  assign EMIOGEM0TXRFIXEDLAT = 1'b0;
  assign EMIOGEM0TXSOF = 1'b0;
  assign EMIOGEM1DELAYREQRX = 1'b0;
  assign EMIOGEM1DELAYREQTX = 1'b0;
  assign EMIOGEM1PDELAYREQRX = 1'b0;
  assign EMIOGEM1PDELAYREQTX = 1'b0;
  assign EMIOGEM1PDELAYRESPRX = 1'b0;
  assign EMIOGEM1PDELAYRESPTX = 1'b0;
  assign EMIOGEM1RXSOF = 1'b0;
  assign EMIOGEM1SYNCFRAMERX = 1'b0;
  assign EMIOGEM1SYNCFRAMETX = 1'b0;
  assign EMIOGEM1TSUTIMERCMPVAL = 1'b0;
  assign EMIOGEM1TXRFIXEDLAT = 1'b0;
  assign EMIOGEM1TXSOF = 1'b0;
  assign EMIOGEM2DELAYREQRX = 1'b0;
  assign EMIOGEM2DELAYREQTX = 1'b0;
  assign EMIOGEM2PDELAYREQRX = 1'b0;
  assign EMIOGEM2PDELAYREQTX = 1'b0;
  assign EMIOGEM2PDELAYRESPRX = 1'b0;
  assign EMIOGEM2PDELAYRESPTX = 1'b0;
  assign EMIOGEM2RXSOF = 1'b0;
  assign EMIOGEM2SYNCFRAMERX = 1'b0;
  assign EMIOGEM2SYNCFRAMETX = 1'b0;
  assign EMIOGEM2TSUTIMERCMPVAL = 1'b0;
  assign EMIOGEM2TXRFIXEDLAT = 1'b0;
  assign EMIOGEM2TXSOF = 1'b0;
  assign EMIOGEM3DELAYREQRX = 1'b0;
  assign EMIOGEM3DELAYREQTX = 1'b0;
  assign EMIOGEM3PDELAYREQRX = 1'b0;
  assign EMIOGEM3PDELAYREQTX = 1'b0;
  assign EMIOGEM3PDELAYRESPRX = 1'b0;
  assign EMIOGEM3PDELAYRESPTX = 1'b0;
  assign EMIOGEM3RXSOF = 1'b0;
  assign EMIOGEM3SYNCFRAMERX = 1'b0;
  assign EMIOGEM3SYNCFRAMETX = 1'b0;
  assign EMIOGEM3TSUTIMERCMPVAL = 1'b0;
  assign EMIOGEM3TXRFIXEDLAT = 1'b0;
  assign EMIOGEM3TXSOF = 1'b0;
  assign EMIOGPIOO = 96'b0;
  assign EMIOGPIOTN = 96'b0;
  assign EMIOI2C0SCLO = 1'b0;
  assign EMIOI2C0SCLTN = 1'b0;
  assign EMIOI2C0SDAO = 1'b0;
  assign EMIOI2C0SDATN = 1'b0;
  assign EMIOI2C1SCLO = 1'b0;
  assign EMIOI2C1SCLTN = 1'b0;
  assign EMIOI2C1SDAO = 1'b0;
  assign EMIOI2C1SDATN = 1'b0;
  assign EMIOSDIO0BUSPOWER = 1'b0;
  assign EMIOSDIO0BUSVOLT = 3'b0;
  assign EMIOSDIO0CLKOUT = 1'b0;
  assign EMIOSDIO0CMDENA = 1'b0;
  assign EMIOSDIO0CMDOUT = 1'b0;
  assign EMIOSDIO0DATAENA = 8'b0;
  assign EMIOSDIO0DATAOUT = 8'b0;
  assign EMIOSDIO0LEDCONTROL = 1'b0;
  assign EMIOSDIO1BUSPOWER = 1'b0;
  assign EMIOSDIO1BUSVOLT = 3'b0;
  assign EMIOSDIO1CLKOUT = 1'b0;
  assign EMIOSDIO1CMDENA = 1'b0;
  assign EMIOSDIO1CMDOUT = 1'b0;
  assign EMIOSDIO1DATAENA = 8'b0;
  assign EMIOSDIO1DATAOUT = 8'b0;
  assign EMIOSDIO1LEDCONTROL = 1'b0;
  assign EMIOSPI0MO = 1'b0;
  assign EMIOSPI0MOTN = 1'b0;
  assign EMIOSPI0SCLKO = 1'b0;
  assign EMIOSPI0SCLKTN = 1'b0;
  assign EMIOSPI0SO = 1'b0;
  assign EMIOSPI0SSNTN = 1'b0;
  assign EMIOSPI0SSON = 3'b0;
  assign EMIOSPI0STN = 1'b0;
  assign EMIOSPI1MO = 1'b0;
  assign EMIOSPI1MOTN = 1'b0;
  assign EMIOSPI1SCLKO = 1'b0;
  assign EMIOSPI1SCLKTN = 1'b0;
  assign EMIOSPI1SO = 1'b0;
  assign EMIOSPI1SSNTN = 1'b0;
  assign EMIOSPI1SSON = 3'b0;
  assign EMIOSPI1STN = 1'b0;
  assign EMIOTTC0WAVEO = 3'b0;
  assign EMIOTTC1WAVEO = 3'b0;
  assign EMIOTTC2WAVEO = 3'b0;
  assign EMIOTTC3WAVEO = 3'b0;
  assign EMIOU2DSPORTVBUSCTRLUSB30 = 1'b0;
  assign EMIOU2DSPORTVBUSCTRLUSB31 = 1'b0;
  assign EMIOU3DSPORTVBUSCTRLUSB30 = 1'b0;
  assign EMIOU3DSPORTVBUSCTRLUSB31 = 1'b0;
  assign EMIOUART0DTRN = 1'b0;
  assign EMIOUART0RTSN = 1'b0;
  assign EMIOUART0TX = 1'b0;
  assign EMIOUART1DTRN = 1'b0;
  assign EMIOUART1RTSN = 1'b0;
  assign EMIOUART1TX = 1'b0;
  assign EMIOWDT0RSTO = 1'b0;
  assign EMIOWDT1RSTO = 1'b0;
  assign FMIOGEM0FIFORXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM0FIFOTXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM1FIFORXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM1FIFOTXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM2FIFORXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM2FIFOTXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM3FIFORXCLKTOPLBUFG = 1'b0;
  assign FMIOGEM3FIFOTXCLKTOPLBUFG = 1'b0;
  assign FMIOGEMTSUCLKTOPLBUFG = 1'b0;
  assign FTMGPO = 32'b0;
  assign GDMA2PLCACK = 8'b0;
  assign GDMA2PLTVLD = 8'b0;
  assign MAXIGP0ARADDR = 40'b0;
  assign MAXIGP0ARBURST = 2'b0;
  assign MAXIGP0ARCACHE = 4'b0;
  assign MAXIGP0ARID = 16'b0;
  assign MAXIGP0ARLEN = 8'b0;
  assign MAXIGP0ARLOCK = 1'b0;
  assign MAXIGP0ARPROT = 3'b0;
  assign MAXIGP0ARQOS = 4'b0;
  assign MAXIGP0ARSIZE = 3'b0;
  assign MAXIGP0ARUSER = 16'b0;
  assign MAXIGP0ARVALID = 1'b0;
  assign MAXIGP0AWADDR = 40'b0;
  assign MAXIGP0AWBURST = 2'b0;
  assign MAXIGP0AWCACHE = 4'b0;
  assign MAXIGP0AWID = 16'b0;
  assign MAXIGP0AWLEN = 8'b0;
  assign MAXIGP0AWLOCK = 1'b0;
  assign MAXIGP0AWPROT = 3'b0;
  assign MAXIGP0AWQOS = 4'b0;
  assign MAXIGP0AWSIZE = 3'b0;
  assign MAXIGP0AWUSER = 16'b0;
  assign MAXIGP0AWVALID = 1'b0;
  assign MAXIGP0BREADY = 1'b0;
  assign MAXIGP0RREADY = 1'b0;
  assign MAXIGP0WDATA = 128'b0;
  assign MAXIGP0WLAST = 1'b0;
  assign MAXIGP0WSTRB = 16'b0;
  assign MAXIGP0WVALID = 1'b0;
  assign MAXIGP1ARADDR = 40'b0;
  assign MAXIGP1ARBURST = 2'b0;
  assign MAXIGP1ARCACHE = 4'b0;
  assign MAXIGP1ARID = 16'b0;
  assign MAXIGP1ARLEN = 8'b0;
  assign MAXIGP1ARLOCK = 1'b0;
  assign MAXIGP1ARPROT = 3'b0;
  assign MAXIGP1ARQOS = 4'b0;
  assign MAXIGP1ARSIZE = 3'b0;
  assign MAXIGP1ARUSER = 16'b0;
  assign MAXIGP1ARVALID = 1'b0;
  assign MAXIGP1AWADDR = 40'b0;
  assign MAXIGP1AWBURST = 2'b0;
  assign MAXIGP1AWCACHE = 4'b0;
  assign MAXIGP1AWID = 16'b0;
  assign MAXIGP1AWLEN = 8'b0;
  assign MAXIGP1AWLOCK = 1'b0;
  assign MAXIGP1AWPROT = 3'b0;
  assign MAXIGP1AWQOS = 4'b0;
  assign MAXIGP1AWSIZE = 3'b0;
  assign MAXIGP1AWUSER = 16'b0;
  assign MAXIGP1AWVALID = 1'b0;
  assign MAXIGP1BREADY = 1'b0;
  assign MAXIGP1RREADY = 1'b0;
  assign MAXIGP1WDATA = 128'b0;
  assign MAXIGP1WLAST = 1'b0;
  assign MAXIGP1WSTRB = 16'b0;
  assign MAXIGP1WVALID = 1'b0;
  assign MAXIGP2ARADDR = 40'b0;
  assign MAXIGP2ARBURST = 2'b0;
  assign MAXIGP2ARCACHE = 4'b0;
  assign MAXIGP2ARID = 16'b0;
  assign MAXIGP2ARLEN = 8'b0;
  assign MAXIGP2ARLOCK = 1'b0;
  assign MAXIGP2ARPROT = 3'b0;
  assign MAXIGP2ARQOS = 4'b0;
  assign MAXIGP2ARSIZE = 3'b0;
  assign MAXIGP2ARUSER = 16'b0;
  assign MAXIGP2ARVALID = 1'b0;
  assign MAXIGP2AWADDR = 40'b0;
  assign MAXIGP2AWBURST = 2'b0;
  assign MAXIGP2AWCACHE = 4'b0;
  assign MAXIGP2AWID = 16'b0;
  assign MAXIGP2AWLEN = 8'b0;
  assign MAXIGP2AWLOCK = 1'b0;
  assign MAXIGP2AWPROT = 3'b0;
  assign MAXIGP2AWQOS = 4'b0;
  assign MAXIGP2AWSIZE = 3'b0;
  assign MAXIGP2AWUSER = 16'b0;
  assign MAXIGP2AWVALID = 1'b0;
  assign MAXIGP2BREADY = 1'b0;
  assign MAXIGP2RREADY = 1'b0;
  assign MAXIGP2WDATA = 128'b0;
  assign MAXIGP2WLAST = 1'b0;
  assign MAXIGP2WSTRB = 16'b0;
  assign MAXIGP2WVALID = 1'b0;
  assign OSCRTCCLK = 1'b0;
  assign PLCLK = 4'b0;
  assign PMUAIBAFIFMFPDREQ = 1'b0;
  assign PMUAIBAFIFMLPDREQ = 1'b0;
  assign PMUERRORTOPL = 47'b0;
  assign PMUPLGPO = 32'b0;
  assign PSPLEVENTO = 1'b0;
  assign PSPLIRQFPD = 64'b0;
  assign PSPLIRQLPD = 100'b0;
  assign PSPLSTANDBYWFE = 4'b0;
  assign PSPLSTANDBYWFI = 4'b0;
  assign PSPLTRACECTL = 1'b0;
  assign PSPLTRACEDATA = 32'b0;
  assign PSPLTRIGACK = 4'b0;
  assign PSPLTRIGGER = 4'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXN0OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXN1OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXN2OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXN3OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXP0OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXP1OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXP2OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_MGTTXP3OUT = 1'b0;
  assign PSS_ALTO_CORE_PAD_PADO = 1'b0;
  assign RPUEVENTO0 = 1'b0;
  assign RPUEVENTO1 = 1'b0;
  assign SACEFPDACADDR = 44'b0;
  assign SACEFPDACPROT = 3'b0;
  assign SACEFPDACSNOOP = 4'b0;
  assign SACEFPDACVALID = 1'b0;
  assign SACEFPDARREADY = 1'b0;
  assign SACEFPDAWREADY = 1'b0;
  assign SACEFPDBID = 6'b0;
  assign SACEFPDBRESP = 2'b0;
  assign SACEFPDBUSER = 1'b0;
  assign SACEFPDBVALID = 1'b0;
  assign SACEFPDCDREADY = 1'b0;
  assign SACEFPDCRREADY = 1'b0;
  assign SACEFPDRDATA = 128'b0;
  assign SACEFPDRID = 6'b0;
  assign SACEFPDRLAST = 1'b0;
  assign SACEFPDRRESP = 4'b0;
  assign SACEFPDRUSER = 1'b0;
  assign SACEFPDRVALID = 1'b0;
  assign SACEFPDWREADY = 1'b0;
  assign SAXIACPARREADY = 1'b0;
  assign SAXIACPAWREADY = 1'b0;
  assign SAXIACPBID = 5'b0;
  assign SAXIACPBRESP = 2'b0;
  assign SAXIACPBVALID = 1'b0;
  assign SAXIACPRDATA = 128'b0;
  assign SAXIACPRID = 5'b0;
  assign SAXIACPRLAST = 1'b0;
  assign SAXIACPRRESP = 2'b0;
  assign SAXIACPRVALID = 1'b0;
  assign SAXIACPWREADY = 1'b0;
  assign SAXIGP0ARREADY = 1'b0;
  assign SAXIGP0AWREADY = 1'b0;
  assign SAXIGP0BID = 6'b0;
  assign SAXIGP0BRESP = 2'b0;
  assign SAXIGP0BVALID = 1'b0;
  assign SAXIGP0RACOUNT = 4'b0;
  assign SAXIGP0RCOUNT = 8'b0;
  assign SAXIGP0RDATA = 128'b0;
  assign SAXIGP0RID = 6'b0;
  assign SAXIGP0RLAST = 1'b0;
  assign SAXIGP0RRESP = 2'b0;
  assign SAXIGP0RVALID = 1'b0;
  assign SAXIGP0WACOUNT = 4'b0;
  assign SAXIGP0WCOUNT = 8'b0;
  assign SAXIGP0WREADY = 1'b0;
  assign SAXIGP1ARREADY = 1'b0;
  assign SAXIGP1AWREADY = 1'b0;
  assign SAXIGP1BID = 6'b0;
  assign SAXIGP1BRESP = 2'b0;
  assign SAXIGP1BVALID = 1'b0;
  assign SAXIGP1RACOUNT = 4'b0;
  assign SAXIGP1RCOUNT = 8'b0;
  assign SAXIGP1RDATA = 128'b0;
  assign SAXIGP1RID = 6'b0;
  assign SAXIGP1RLAST = 1'b0;
  assign SAXIGP1RRESP = 2'b0;
  assign SAXIGP1RVALID = 1'b0;
  assign SAXIGP1WACOUNT = 4'b0;
  assign SAXIGP1WCOUNT = 8'b0;
  assign SAXIGP1WREADY = 1'b0;
  assign SAXIGP2ARREADY = 1'b0;
  assign SAXIGP2AWREADY = 1'b0;
  assign SAXIGP2BID = 6'b0;
  assign SAXIGP2BRESP = 2'b0;
  assign SAXIGP2BVALID = 1'b0;
  assign SAXIGP2RACOUNT = 4'b0;
  assign SAXIGP2RCOUNT = 8'b0;
  assign SAXIGP2RDATA = 128'b0;
  assign SAXIGP2RID = 6'b0;
  assign SAXIGP2RLAST = 1'b0;
  assign SAXIGP2RRESP = 2'b0;
  assign SAXIGP2RVALID = 1'b0;
  assign SAXIGP2WACOUNT = 4'b0;
  assign SAXIGP2WCOUNT = 8'b0;
  assign SAXIGP2WREADY = 1'b0;
  assign SAXIGP3ARREADY = 1'b0;
  assign SAXIGP3AWREADY = 1'b0;
  assign SAXIGP3BID = 6'b0;
  assign SAXIGP3BRESP = 2'b0;
  assign SAXIGP3BVALID = 1'b0;
  assign SAXIGP3RACOUNT = 4'b0;
  assign SAXIGP3RCOUNT = 8'b0;
  assign SAXIGP3RDATA = 128'b0;
  assign SAXIGP3RID = 6'b0;
  assign SAXIGP3RLAST = 1'b0;
  assign SAXIGP3RRESP = 2'b0;
  assign SAXIGP3RVALID = 1'b0;
  assign SAXIGP3WACOUNT = 4'b0;
  assign SAXIGP3WCOUNT = 8'b0;
  assign SAXIGP3WREADY = 1'b0;
  assign SAXIGP4ARREADY = 1'b0;
  assign SAXIGP4AWREADY = 1'b0;
  assign SAXIGP4BID = 6'b0;
  assign SAXIGP4BRESP = 2'b0;
  assign SAXIGP4BVALID = 1'b0;
  assign SAXIGP4RACOUNT = 4'b0;
  assign SAXIGP4RCOUNT = 8'b0;
  assign SAXIGP4RDATA = 128'b0;
  assign SAXIGP4RID = 6'b0;
  assign SAXIGP4RLAST = 1'b0;
  assign SAXIGP4RRESP = 2'b0;
  assign SAXIGP4RVALID = 1'b0;
  assign SAXIGP4WACOUNT = 4'b0;
  assign SAXIGP4WCOUNT = 8'b0;
  assign SAXIGP4WREADY = 1'b0;
  assign SAXIGP5ARREADY = 1'b0;
  assign SAXIGP5AWREADY = 1'b0;
  assign SAXIGP5BID = 6'b0;
  assign SAXIGP5BRESP = 2'b0;
  assign SAXIGP5BVALID = 1'b0;
  assign SAXIGP5RACOUNT = 4'b0;
  assign SAXIGP5RCOUNT = 8'b0;
  assign SAXIGP5RDATA = 128'b0;
  assign SAXIGP5RID = 6'b0;
  assign SAXIGP5RLAST = 1'b0;
  assign SAXIGP5RRESP = 2'b0;
  assign SAXIGP5RVALID = 1'b0;
  assign SAXIGP5WACOUNT = 4'b0;
  assign SAXIGP5WCOUNT = 8'b0;
  assign SAXIGP5WREADY = 1'b0;
  assign SAXIGP6ARREADY = 1'b0;
  assign SAXIGP6AWREADY = 1'b0;
  assign SAXIGP6BID = 6'b0;
  assign SAXIGP6BRESP = 2'b0;
  assign SAXIGP6BVALID = 1'b0;
  assign SAXIGP6RACOUNT = 4'b0;
  assign SAXIGP6RCOUNT = 8'b0;
  assign SAXIGP6RDATA = 128'b0;
  assign SAXIGP6RID = 6'b0;
  assign SAXIGP6RLAST = 1'b0;
  assign SAXIGP6RRESP = 2'b0;
  assign SAXIGP6RVALID = 1'b0;
  assign SAXIGP6WACOUNT = 4'b0;
  assign SAXIGP6WCOUNT = 8'b0;
  assign SAXIGP6WREADY = 1'b0;

  // Every input, read once, so that lint has nothing to say about any of
  // them.
  /* verilator lint_off UNUSEDSIGNAL */
  logic unused;
  assign unused = ^{1'b0,
                     ADMAFCICLK, AIBPMUAFIFMFPDACK, AIBPMUAFIFMLPDACK,
                     DDRCEXTREFRESHRANK0REQ, DDRCEXTREFRESHRANK1REQ,
                     DDRCREFRESHPLCLK, DPAUXDATAIN, DPEXTERNALCUSTOMEVENT1,
                     DPEXTERNALCUSTOMEVENT2, DPEXTERNALVSYNCEVENT,
                     DPHOTPLUGDETECT, DPLIVEGFXALPHAIN, DPLIVEGFXPIXEL1IN,
                     DPLIVEVIDEOINDE, DPLIVEVIDEOINHSYNC, DPLIVEVIDEOINPIXEL1,
                     DPLIVEVIDEOINVSYNC, DPMAXISMIXEDAUDIOTREADY,
                     DPSAXISAUDIOCLK, DPSAXISAUDIOTDATA, DPSAXISAUDIOTID,
                     DPSAXISAUDIOTVALID, DPVIDEOINCLK, EMIOCAN0PHYRX,
                     EMIOCAN1PHYRX, EMIOENET0DMATXSTATUSTOG,
                     EMIOENET0EXTINTIN, EMIOENET0GMIICOL, EMIOENET0GMIICRS,
                     EMIOENET0GMIIRXCLK, EMIOENET0GMIIRXD, EMIOENET0GMIIRXDV,
                     EMIOENET0GMIIRXER, EMIOENET0GMIITXCLK, EMIOENET0MDIOI,
                     EMIOENET0RXWOVERFLOW, EMIOENET0TXRCONTROL,
                     EMIOENET0TXRDATA, EMIOENET0TXRDATARDY, EMIOENET0TXREOP,
                     EMIOENET0TXRERR, EMIOENET0TXRFLUSHED, EMIOENET0TXRSOP,
                     EMIOENET0TXRUNDERFLOW, EMIOENET0TXRVALID,
                     EMIOENET1DMATXSTATUSTOG, EMIOENET1EXTINTIN,
                     EMIOENET1GMIICOL, EMIOENET1GMIICRS, EMIOENET1GMIIRXCLK,
                     EMIOENET1GMIIRXD, EMIOENET1GMIIRXDV, EMIOENET1GMIIRXER,
                     EMIOENET1GMIITXCLK, EMIOENET1MDIOI, EMIOENET1RXWOVERFLOW,
                     EMIOENET1TXRCONTROL, EMIOENET1TXRDATA,
                     EMIOENET1TXRDATARDY, EMIOENET1TXREOP, EMIOENET1TXRERR,
                     EMIOENET1TXRFLUSHED, EMIOENET1TXRSOP,
                     EMIOENET1TXRUNDERFLOW, EMIOENET1TXRVALID,
                     EMIOENET2DMATXSTATUSTOG, EMIOENET2EXTINTIN,
                     EMIOENET2GMIICOL, EMIOENET2GMIICRS, EMIOENET2GMIIRXCLK,
                     EMIOENET2GMIIRXD, EMIOENET2GMIIRXDV, EMIOENET2GMIIRXER,
                     EMIOENET2GMIITXCLK, EMIOENET2MDIOI, EMIOENET2RXWOVERFLOW,
                     EMIOENET2TXRCONTROL, EMIOENET2TXRDATA,
                     EMIOENET2TXRDATARDY, EMIOENET2TXREOP, EMIOENET2TXRERR,
                     EMIOENET2TXRFLUSHED, EMIOENET2TXRSOP,
                     EMIOENET2TXRUNDERFLOW, EMIOENET2TXRVALID,
                     EMIOENET3DMATXSTATUSTOG, EMIOENET3EXTINTIN,
                     EMIOENET3GMIICOL, EMIOENET3GMIICRS, EMIOENET3GMIIRXCLK,
                     EMIOENET3GMIIRXD, EMIOENET3GMIIRXDV, EMIOENET3GMIIRXER,
                     EMIOENET3GMIITXCLK, EMIOENET3MDIOI, EMIOENET3RXWOVERFLOW,
                     EMIOENET3TXRCONTROL, EMIOENET3TXRDATA,
                     EMIOENET3TXRDATARDY, EMIOENET3TXREOP, EMIOENET3TXRERR,
                     EMIOENET3TXRFLUSHED, EMIOENET3TXRSOP,
                     EMIOENET3TXRUNDERFLOW, EMIOENET3TXRVALID, EMIOENETTSUCLK,
                     EMIOGEM0TSUINCCTRL, EMIOGEM1TSUINCCTRL,
                     EMIOGEM2TSUINCCTRL, EMIOGEM3TSUINCCTRL, EMIOGPIOI,
                     EMIOHUBPORTOVERCRNTUSB20, EMIOHUBPORTOVERCRNTUSB21,
                     EMIOHUBPORTOVERCRNTUSB30, EMIOHUBPORTOVERCRNTUSB31,
                     EMIOI2C0SCLI, EMIOI2C0SDAI, EMIOI2C1SCLI, EMIOI2C1SDAI,
                     EMIOSDIO0CDN, EMIOSDIO0CMDIN, EMIOSDIO0DATAIN,
                     EMIOSDIO0FBCLKIN, EMIOSDIO0WP, EMIOSDIO1CDN,
                     EMIOSDIO1CMDIN, EMIOSDIO1DATAIN, EMIOSDIO1FBCLKIN,
                     EMIOSDIO1WP, EMIOSPI0MI, EMIOSPI0SCLKI, EMIOSPI0SI,
                     EMIOSPI0SSIN, EMIOSPI1MI, EMIOSPI1SCLKI, EMIOSPI1SI,
                     EMIOSPI1SSIN, EMIOTTC0CLKI, EMIOTTC1CLKI, EMIOTTC2CLKI,
                     EMIOTTC3CLKI, EMIOUART0CTSN, EMIOUART0DCDN,
                     EMIOUART0DSRN, EMIOUART0RIN, EMIOUART0RX, EMIOUART1CTSN,
                     EMIOUART1DCDN, EMIOUART1DSRN, EMIOUART1RIN, EMIOUART1RX,
                     EMIOWDT0CLKI, EMIOWDT1CLKI, FMIOGEM0FIFORXCLKFROMPL,
                     FMIOGEM0FIFOTXCLKFROMPL, FMIOGEM0SIGNALDETECT,
                     FMIOGEM1FIFORXCLKFROMPL, FMIOGEM1FIFOTXCLKFROMPL,
                     FMIOGEM1SIGNALDETECT, FMIOGEM2FIFORXCLKFROMPL,
                     FMIOGEM2FIFOTXCLKFROMPL, FMIOGEM2SIGNALDETECT,
                     FMIOGEM3FIFORXCLKFROMPL, FMIOGEM3FIFOTXCLKFROMPL,
                     FMIOGEM3SIGNALDETECT, FMIOGEMTSUCLKFROMPL, FTMGPI,
                     GDMAFCICLK, MAXIGP0ACLK, MAXIGP0ARREADY, MAXIGP0AWREADY,
                     MAXIGP0BID, MAXIGP0BRESP, MAXIGP0BVALID, MAXIGP0RDATA,
                     MAXIGP0RID, MAXIGP0RLAST, MAXIGP0RRESP, MAXIGP0RVALID,
                     MAXIGP0WREADY, MAXIGP1ACLK, MAXIGP1ARREADY,
                     MAXIGP1AWREADY, MAXIGP1BID, MAXIGP1BRESP, MAXIGP1BVALID,
                     MAXIGP1RDATA, MAXIGP1RID, MAXIGP1RLAST, MAXIGP1RRESP,
                     MAXIGP1RVALID, MAXIGP1WREADY, MAXIGP2ACLK,
                     MAXIGP2ARREADY, MAXIGP2AWREADY, MAXIGP2BID, MAXIGP2BRESP,
                     MAXIGP2BVALID, MAXIGP2RDATA, MAXIGP2RID, MAXIGP2RLAST,
                     MAXIGP2RRESP, MAXIGP2RVALID, MAXIGP2WREADY, NFIQ0LPDRPU,
                     NFIQ1LPDRPU, NIRQ0LPDRPU, NIRQ1LPDRPU, PL2ADMACVLD,
                     PL2ADMATACK, PL2GDMACVLD, PL2GDMATACK, PLACECLK,
                     PLACPINACT, PLFPGASTOP, PLLAUXREFCLKFPD, PLLAUXREFCLKLPD,
                     PLPMUGPI, PLPSAPUGICFIQ, PLPSAPUGICIRQ, PLPSEVENTI,
                     PLPSIRQ0, PLPSIRQ1, PLPSTRACECLK, PLPSTRIGACK,
                     PLPSTRIGGER, PMUERRORFROMPL, PSS_ALTO_CORE_PAD_MGTRXN0IN,
                     PSS_ALTO_CORE_PAD_MGTRXN1IN, PSS_ALTO_CORE_PAD_MGTRXN2IN,
                     PSS_ALTO_CORE_PAD_MGTRXN3IN, PSS_ALTO_CORE_PAD_MGTRXP0IN,
                     PSS_ALTO_CORE_PAD_MGTRXP1IN, PSS_ALTO_CORE_PAD_MGTRXP2IN,
                     PSS_ALTO_CORE_PAD_MGTRXP3IN, PSS_ALTO_CORE_PAD_PADI,
                     PSS_ALTO_CORE_PAD_REFN0IN, PSS_ALTO_CORE_PAD_REFN1IN,
                     PSS_ALTO_CORE_PAD_REFN2IN, PSS_ALTO_CORE_PAD_REFN3IN,
                     PSS_ALTO_CORE_PAD_REFP0IN, PSS_ALTO_CORE_PAD_REFP1IN,
                     PSS_ALTO_CORE_PAD_REFP2IN, PSS_ALTO_CORE_PAD_REFP3IN,
                     RPUEVENTI0, RPUEVENTI1, SACEFPDACREADY, SACEFPDARADDR,
                     SACEFPDARBAR, SACEFPDARBURST, SACEFPDARCACHE,
                     SACEFPDARDOMAIN, SACEFPDARID, SACEFPDARLEN,
                     SACEFPDARLOCK, SACEFPDARPROT, SACEFPDARQOS,
                     SACEFPDARREGION, SACEFPDARSIZE, SACEFPDARSNOOP,
                     SACEFPDARUSER, SACEFPDARVALID, SACEFPDAWADDR,
                     SACEFPDAWBAR, SACEFPDAWBURST, SACEFPDAWCACHE,
                     SACEFPDAWDOMAIN, SACEFPDAWID, SACEFPDAWLEN,
                     SACEFPDAWLOCK, SACEFPDAWPROT, SACEFPDAWQOS,
                     SACEFPDAWREGION, SACEFPDAWSIZE, SACEFPDAWSNOOP,
                     SACEFPDAWUSER, SACEFPDAWVALID, SACEFPDBREADY,
                     SACEFPDCDDATA, SACEFPDCDLAST, SACEFPDCDVALID,
                     SACEFPDCRRESP, SACEFPDCRVALID, SACEFPDRACK,
                     SACEFPDRREADY, SACEFPDWACK, SACEFPDWDATA, SACEFPDWLAST,
                     SACEFPDWSTRB, SACEFPDWUSER, SACEFPDWVALID, SAXIACPACLK,
                     SAXIACPARADDR, SAXIACPARBURST, SAXIACPARCACHE,
                     SAXIACPARID, SAXIACPARLEN, SAXIACPARLOCK, SAXIACPARPROT,
                     SAXIACPARQOS, SAXIACPARSIZE, SAXIACPARUSER,
                     SAXIACPARVALID, SAXIACPAWADDR, SAXIACPAWBURST,
                     SAXIACPAWCACHE, SAXIACPAWID, SAXIACPAWLEN, SAXIACPAWLOCK,
                     SAXIACPAWPROT, SAXIACPAWQOS, SAXIACPAWSIZE,
                     SAXIACPAWUSER, SAXIACPAWVALID, SAXIACPBREADY,
                     SAXIACPRREADY, SAXIACPWDATA, SAXIACPWLAST, SAXIACPWSTRB,
                     SAXIACPWVALID, SAXIGP0ARADDR, SAXIGP0ARBURST,
                     SAXIGP0ARCACHE, SAXIGP0ARID, SAXIGP0ARLEN, SAXIGP0ARLOCK,
                     SAXIGP0ARPROT, SAXIGP0ARQOS, SAXIGP0ARSIZE,
                     SAXIGP0ARUSER, SAXIGP0ARVALID, SAXIGP0AWADDR,
                     SAXIGP0AWBURST, SAXIGP0AWCACHE, SAXIGP0AWID,
                     SAXIGP0AWLEN, SAXIGP0AWLOCK, SAXIGP0AWPROT, SAXIGP0AWQOS,
                     SAXIGP0AWSIZE, SAXIGP0AWUSER, SAXIGP0AWVALID,
                     SAXIGP0BREADY, SAXIGP0RCLK, SAXIGP0RREADY, SAXIGP0WCLK,
                     SAXIGP0WDATA, SAXIGP0WLAST, SAXIGP0WSTRB, SAXIGP0WVALID,
                     SAXIGP1ARADDR, SAXIGP1ARBURST, SAXIGP1ARCACHE,
                     SAXIGP1ARID, SAXIGP1ARLEN, SAXIGP1ARLOCK, SAXIGP1ARPROT,
                     SAXIGP1ARQOS, SAXIGP1ARSIZE, SAXIGP1ARUSER,
                     SAXIGP1ARVALID, SAXIGP1AWADDR, SAXIGP1AWBURST,
                     SAXIGP1AWCACHE, SAXIGP1AWID, SAXIGP1AWLEN, SAXIGP1AWLOCK,
                     SAXIGP1AWPROT, SAXIGP1AWQOS, SAXIGP1AWSIZE,
                     SAXIGP1AWUSER, SAXIGP1AWVALID, SAXIGP1BREADY,
                     SAXIGP1RCLK, SAXIGP1RREADY, SAXIGP1WCLK, SAXIGP1WDATA,
                     SAXIGP1WLAST, SAXIGP1WSTRB, SAXIGP1WVALID, SAXIGP2ARADDR,
                     SAXIGP2ARBURST, SAXIGP2ARCACHE, SAXIGP2ARID,
                     SAXIGP2ARLEN, SAXIGP2ARLOCK, SAXIGP2ARPROT, SAXIGP2ARQOS,
                     SAXIGP2ARSIZE, SAXIGP2ARUSER, SAXIGP2ARVALID,
                     SAXIGP2AWADDR, SAXIGP2AWBURST, SAXIGP2AWCACHE,
                     SAXIGP2AWID, SAXIGP2AWLEN, SAXIGP2AWLOCK, SAXIGP2AWPROT,
                     SAXIGP2AWQOS, SAXIGP2AWSIZE, SAXIGP2AWUSER,
                     SAXIGP2AWVALID, SAXIGP2BREADY, SAXIGP2RCLK,
                     SAXIGP2RREADY, SAXIGP2WCLK, SAXIGP2WDATA, SAXIGP2WLAST,
                     SAXIGP2WSTRB, SAXIGP2WVALID, SAXIGP3ARADDR,
                     SAXIGP3ARBURST, SAXIGP3ARCACHE, SAXIGP3ARID,
                     SAXIGP3ARLEN, SAXIGP3ARLOCK, SAXIGP3ARPROT, SAXIGP3ARQOS,
                     SAXIGP3ARSIZE, SAXIGP3ARUSER, SAXIGP3ARVALID,
                     SAXIGP3AWADDR, SAXIGP3AWBURST, SAXIGP3AWCACHE,
                     SAXIGP3AWID, SAXIGP3AWLEN, SAXIGP3AWLOCK, SAXIGP3AWPROT,
                     SAXIGP3AWQOS, SAXIGP3AWSIZE, SAXIGP3AWUSER,
                     SAXIGP3AWVALID, SAXIGP3BREADY, SAXIGP3RCLK,
                     SAXIGP3RREADY, SAXIGP3WCLK, SAXIGP3WDATA, SAXIGP3WLAST,
                     SAXIGP3WSTRB, SAXIGP3WVALID, SAXIGP4ARADDR,
                     SAXIGP4ARBURST, SAXIGP4ARCACHE, SAXIGP4ARID,
                     SAXIGP4ARLEN, SAXIGP4ARLOCK, SAXIGP4ARPROT, SAXIGP4ARQOS,
                     SAXIGP4ARSIZE, SAXIGP4ARUSER, SAXIGP4ARVALID,
                     SAXIGP4AWADDR, SAXIGP4AWBURST, SAXIGP4AWCACHE,
                     SAXIGP4AWID, SAXIGP4AWLEN, SAXIGP4AWLOCK, SAXIGP4AWPROT,
                     SAXIGP4AWQOS, SAXIGP4AWSIZE, SAXIGP4AWUSER,
                     SAXIGP4AWVALID, SAXIGP4BREADY, SAXIGP4RCLK,
                     SAXIGP4RREADY, SAXIGP4WCLK, SAXIGP4WDATA, SAXIGP4WLAST,
                     SAXIGP4WSTRB, SAXIGP4WVALID, SAXIGP5ARADDR,
                     SAXIGP5ARBURST, SAXIGP5ARCACHE, SAXIGP5ARID,
                     SAXIGP5ARLEN, SAXIGP5ARLOCK, SAXIGP5ARPROT, SAXIGP5ARQOS,
                     SAXIGP5ARSIZE, SAXIGP5ARUSER, SAXIGP5ARVALID,
                     SAXIGP5AWADDR, SAXIGP5AWBURST, SAXIGP5AWCACHE,
                     SAXIGP5AWID, SAXIGP5AWLEN, SAXIGP5AWLOCK, SAXIGP5AWPROT,
                     SAXIGP5AWQOS, SAXIGP5AWSIZE, SAXIGP5AWUSER,
                     SAXIGP5AWVALID, SAXIGP5BREADY, SAXIGP5RCLK,
                     SAXIGP5RREADY, SAXIGP5WCLK, SAXIGP5WDATA, SAXIGP5WLAST,
                     SAXIGP5WSTRB, SAXIGP5WVALID, SAXIGP6ARADDR,
                     SAXIGP6ARBURST, SAXIGP6ARCACHE, SAXIGP6ARID,
                     SAXIGP6ARLEN, SAXIGP6ARLOCK, SAXIGP6ARPROT, SAXIGP6ARQOS,
                     SAXIGP6ARSIZE, SAXIGP6ARUSER, SAXIGP6ARVALID,
                     SAXIGP6AWADDR, SAXIGP6AWBURST, SAXIGP6AWCACHE,
                     SAXIGP6AWID, SAXIGP6AWLEN, SAXIGP6AWLOCK, SAXIGP6AWPROT,
                     SAXIGP6AWQOS, SAXIGP6AWSIZE, SAXIGP6AWUSER,
                     SAXIGP6AWVALID, SAXIGP6BREADY, SAXIGP6RCLK,
                     SAXIGP6RREADY, SAXIGP6WCLK, SAXIGP6WDATA, SAXIGP6WLAST,
                     SAXIGP6WSTRB, SAXIGP6WVALID, STMEVENT};
  /* verilator lint_on UNUSEDSIGNAL */

endmodule

/* verilator lint_on DECLFILENAME */

`default_nettype wire
