// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The two Altera IP cores the DE25-Nano's top level instantiates, as shells,
// so that `boards/de25-nano/cadr_de25.sv` can be elaborated and linted.
//
//   `cadr_de25_pll`   the I/O PLL that `boards/de25-nano/quartus/build.sh`
//                     generates from Altera's IP at every build.  The port
//                     list is the one the generator writes for the parameters
//                     that flow gives it: one reference clock, one reset, one
//                     output clock and the lock.
//   `cadr_de25_reset_release`
//                     the Reset Release, generated by the same flow from
//                     Altera's IP of that name, whose one port is
//                     `nINIT_DONE`.
//
// **NOTHING HERE MODELS ANYTHING, AND THIS FILE MUST NEVER MOVE TO `rtl/`.**
// The PLL below multiplies nothing, so a model built on it would run the
// machine at the board's 50 MHz, a different machine that still lights LEDs.
// `build/de25.pass` is the only rule that reads this file, and it only lints.
// Both Vivado flows read `[glob rtl/*/*.sv rtl/*/*/*.sv]`, and nothing globs
// `tb/`, which is the reason `tb/cadr_arty_stubs.sv` lives here too.

`default_nettype none

/* verilator lint_off DECLFILENAME */

module cadr_de25_pll (
    input  var logic refclk,
    input  var logic rst,
    output var logic outclk_0,
    output var logic locked
);
  // Not a multiplier: see the header.
  assign outclk_0 = refclk;
  assign locked   = !rst;
endmodule

module cadr_de25_reset_release (
    output var logic ninit_done
);
  // A device that finished initializing long ago.
  assign ninit_done = 1'b0;
endmodule

/* verilator lint_on DECLFILENAME */

`default_nettype wire
