// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The three Altera IP cores the DE25-Nano's top level instantiates, as shells,
// so that `boards/de25-nano/cadr_de25.sv` can be elaborated and linted.
//
//   `cadr_de25_pll`   the I/O PLL that `boards/de25-nano/quartus/build.sh`
//                     generates from Altera's IP at every build.  The port
//                     list is the one the generator writes for the parameters
//                     that flow gives it: one reference clock, one reset, one
//                     output clock and the lock.
//   `cadr_de25_reset_release`
//                     the Reset Release, generated by the same flow from
//                     Altera's IP of that name, whose one port is
//                     `nINIT_DONE`.
//   `cadr_de25_vjtag` the Virtual JTAG IP, generated by the same flow when
//                     the probe is asked for.  The port list is the one the
//                     generator writes for a one-bit virtual instruction:
//                     the node's TDI, TDO, TCK, its instruction in and out,
//                     and its eight virtual states.
//
// **NOTHING HERE MODELS ANYTHING, AND THIS FILE MUST NEVER MOVE TO `rtl/`.**
// The PLL below multiplies nothing, so a model built on it would run the
// machine at the board's 50 MHz, a different machine that still lights LEDs.
// `build/de25.pass` is the only rule that reads this file, and it only lints.
// Both Vivado flows read `[glob rtl/*/*.sv rtl/*/*/*.sv]`, and nothing globs
// `tb/`, which is the reason `tb/cadr_arty_stubs.sv` lives here too.

`default_nettype none

/* verilator lint_off DECLFILENAME */

module cadr_de25_pll (
    input  var logic refclk,
    input  var logic rst,
    output var logic outclk_0,
    output var logic locked
);
  // Not a multiplier: see the header.
  assign outclk_0 = refclk;
  assign locked   = !rst;
endmodule

module cadr_de25_reset_release (
    output var logic ninit_done
);
  // A device that finished initializing long ago.
  assign ninit_done = 1'b0;
endmodule

module cadr_de25_vjtag (
    output var logic tck,
    output var logic tdi,
    input  var logic tdo,
    output var logic ir_in,
    input  var logic ir_out,
    output var logic virtual_state_cdr,
    output var logic virtual_state_sdr,
    output var logic virtual_state_e1dr,
    output var logic virtual_state_pdr,
    output var logic virtual_state_e2dr,
    output var logic virtual_state_udr,
    output var logic virtual_state_cir,
    output var logic virtual_state_uir
);
  // No hub and no cable: every state low and nothing selected.  What a node
  // does with a real hub is `tb/cadr_probe_tb.cpp`'s question.
  assign tck = 1'b0;
  assign tdi = 1'b0;
  assign ir_in = 1'b0;
  assign {virtual_state_cdr, virtual_state_sdr, virtual_state_e1dr,
          virtual_state_pdr, virtual_state_e2dr, virtual_state_udr,
          virtual_state_cir, virtual_state_uir} = '0;
  /* verilator lint_off UNUSEDSIGNAL */
  logic unused;
  assign unused = &{1'b0, tdo, ir_out};
  /* verilator lint_on UNUSEDSIGNAL */
endmodule

/* verilator lint_on DECLFILENAME */

`default_nettype wire
