// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by vivado/gen_ps7.py from $XILINX_VIVADO's own PS7.v.
// Do not edit; run `make ps7`.
//
// `PS7` as an empty shell, so that Verilator can elaborate `rtl/cadr_ps7.sv`
// and lint the top level that instantiates it.
//
// **THIS FILE MUST NEVER MOVE TO `rtl/`.**  `vivado/fit.tcl` and
// `vivado/bitstream.tcl` both read `[glob rtl/*.sv]`, so a stub here would be
// handed to synthesis in place of the real primitive --- and a board whose
// processing system is a bundle of constants is a machine with no memory that
// still lights LEDs.  Nothing globs `tb/`, which is why this is here.
//
// **AND IT MODELS NOTHING.**  Every output is zero, which means
// `hp0_aresetn` is zero, which means the fabric's own gate on it holds the
// memory path in reset for ever.  That is correct for lint and useless for
// anything else.  The one thing it does carry is the PORT LIST, all 620 of
// them, off the same parse as the wrapper in the same pass --- so a pin the
// wrapper names and the primitive does not cannot exist here either.

`default_nettype none

/* verilator lint_off DECLFILENAME */

module PS7 (
    output var logic [1:0]   DMA0DATYPE,
    output var logic         DMA0DAVALID,
    output var logic         DMA0DRREADY,
    output var logic         DMA0RSTN,
    output var logic [1:0]   DMA1DATYPE,
    output var logic         DMA1DAVALID,
    output var logic         DMA1DRREADY,
    output var logic         DMA1RSTN,
    output var logic [1:0]   DMA2DATYPE,
    output var logic         DMA2DAVALID,
    output var logic         DMA2DRREADY,
    output var logic         DMA2RSTN,
    output var logic [1:0]   DMA3DATYPE,
    output var logic         DMA3DAVALID,
    output var logic         DMA3DRREADY,
    output var logic         DMA3RSTN,
    output var logic         EMIOCAN0PHYTX,
    output var logic         EMIOCAN1PHYTX,
    output var logic [7:0]   EMIOENET0GMIITXD,
    output var logic         EMIOENET0GMIITXEN,
    output var logic         EMIOENET0GMIITXER,
    output var logic         EMIOENET0MDIOMDC,
    output var logic         EMIOENET0MDIOO,
    output var logic         EMIOENET0MDIOTN,
    output var logic         EMIOENET0PTPDELAYREQRX,
    output var logic         EMIOENET0PTPDELAYREQTX,
    output var logic         EMIOENET0PTPPDELAYREQRX,
    output var logic         EMIOENET0PTPPDELAYREQTX,
    output var logic         EMIOENET0PTPPDELAYRESPRX,
    output var logic         EMIOENET0PTPPDELAYRESPTX,
    output var logic         EMIOENET0PTPSYNCFRAMERX,
    output var logic         EMIOENET0PTPSYNCFRAMETX,
    output var logic         EMIOENET0SOFRX,
    output var logic         EMIOENET0SOFTX,
    output var logic [7:0]   EMIOENET1GMIITXD,
    output var logic         EMIOENET1GMIITXEN,
    output var logic         EMIOENET1GMIITXER,
    output var logic         EMIOENET1MDIOMDC,
    output var logic         EMIOENET1MDIOO,
    output var logic         EMIOENET1MDIOTN,
    output var logic         EMIOENET1PTPDELAYREQRX,
    output var logic         EMIOENET1PTPDELAYREQTX,
    output var logic         EMIOENET1PTPPDELAYREQRX,
    output var logic         EMIOENET1PTPPDELAYREQTX,
    output var logic         EMIOENET1PTPPDELAYRESPRX,
    output var logic         EMIOENET1PTPPDELAYRESPTX,
    output var logic         EMIOENET1PTPSYNCFRAMERX,
    output var logic         EMIOENET1PTPSYNCFRAMETX,
    output var logic         EMIOENET1SOFRX,
    output var logic         EMIOENET1SOFTX,
    output var logic [63:0]  EMIOGPIOO,
    output var logic [63:0]  EMIOGPIOTN,
    output var logic         EMIOI2C0SCLO,
    output var logic         EMIOI2C0SCLTN,
    output var logic         EMIOI2C0SDAO,
    output var logic         EMIOI2C0SDATN,
    output var logic         EMIOI2C1SCLO,
    output var logic         EMIOI2C1SCLTN,
    output var logic         EMIOI2C1SDAO,
    output var logic         EMIOI2C1SDATN,
    output var logic         EMIOPJTAGTDO,
    output var logic         EMIOPJTAGTDTN,
    output var logic         EMIOSDIO0BUSPOW,
    output var logic [2:0]   EMIOSDIO0BUSVOLT,
    output var logic         EMIOSDIO0CLK,
    output var logic         EMIOSDIO0CMDO,
    output var logic         EMIOSDIO0CMDTN,
    output var logic [3:0]   EMIOSDIO0DATAO,
    output var logic [3:0]   EMIOSDIO0DATATN,
    output var logic         EMIOSDIO0LED,
    output var logic         EMIOSDIO1BUSPOW,
    output var logic [2:0]   EMIOSDIO1BUSVOLT,
    output var logic         EMIOSDIO1CLK,
    output var logic         EMIOSDIO1CMDO,
    output var logic         EMIOSDIO1CMDTN,
    output var logic [3:0]   EMIOSDIO1DATAO,
    output var logic [3:0]   EMIOSDIO1DATATN,
    output var logic         EMIOSDIO1LED,
    output var logic         EMIOSPI0MO,
    output var logic         EMIOSPI0MOTN,
    output var logic         EMIOSPI0SCLKO,
    output var logic         EMIOSPI0SCLKTN,
    output var logic         EMIOSPI0SO,
    output var logic         EMIOSPI0SSNTN,
    output var logic [2:0]   EMIOSPI0SSON,
    output var logic         EMIOSPI0STN,
    output var logic         EMIOSPI1MO,
    output var logic         EMIOSPI1MOTN,
    output var logic         EMIOSPI1SCLKO,
    output var logic         EMIOSPI1SCLKTN,
    output var logic         EMIOSPI1SO,
    output var logic         EMIOSPI1SSNTN,
    output var logic [2:0]   EMIOSPI1SSON,
    output var logic         EMIOSPI1STN,
    output var logic         EMIOTRACECTL,
    output var logic [31:0]  EMIOTRACEDATA,
    output var logic [2:0]   EMIOTTC0WAVEO,
    output var logic [2:0]   EMIOTTC1WAVEO,
    output var logic         EMIOUART0DTRN,
    output var logic         EMIOUART0RTSN,
    output var logic         EMIOUART0TX,
    output var logic         EMIOUART1DTRN,
    output var logic         EMIOUART1RTSN,
    output var logic         EMIOUART1TX,
    output var logic [1:0]   EMIOUSB0PORTINDCTL,
    output var logic         EMIOUSB0VBUSPWRSELECT,
    output var logic [1:0]   EMIOUSB1PORTINDCTL,
    output var logic         EMIOUSB1VBUSPWRSELECT,
    output var logic         EMIOWDTRSTO,
    output var logic         EVENTEVENTO,
    output var logic [1:0]   EVENTSTANDBYWFE,
    output var logic [1:0]   EVENTSTANDBYWFI,
    output var logic [3:0]   FCLKCLK,
    output var logic [3:0]   FCLKRESETN,
    output var logic [3:0]   FTMTF2PTRIGACK,
    output var logic [31:0]  FTMTP2FDEBUG,
    output var logic [3:0]   FTMTP2FTRIG,
    output var logic [28:0]  IRQP2F,
    output var logic [31:0]  MAXIGP0ARADDR,
    output var logic [1:0]   MAXIGP0ARBURST,
    output var logic [3:0]   MAXIGP0ARCACHE,
    output var logic         MAXIGP0ARESETN,
    output var logic [11:0]  MAXIGP0ARID,
    output var logic [3:0]   MAXIGP0ARLEN,
    output var logic [1:0]   MAXIGP0ARLOCK,
    output var logic [2:0]   MAXIGP0ARPROT,
    output var logic [3:0]   MAXIGP0ARQOS,
    output var logic [1:0]   MAXIGP0ARSIZE,
    output var logic         MAXIGP0ARVALID,
    output var logic [31:0]  MAXIGP0AWADDR,
    output var logic [1:0]   MAXIGP0AWBURST,
    output var logic [3:0]   MAXIGP0AWCACHE,
    output var logic [11:0]  MAXIGP0AWID,
    output var logic [3:0]   MAXIGP0AWLEN,
    output var logic [1:0]   MAXIGP0AWLOCK,
    output var logic [2:0]   MAXIGP0AWPROT,
    output var logic [3:0]   MAXIGP0AWQOS,
    output var logic [1:0]   MAXIGP0AWSIZE,
    output var logic         MAXIGP0AWVALID,
    output var logic         MAXIGP0BREADY,
    output var logic         MAXIGP0RREADY,
    output var logic [31:0]  MAXIGP0WDATA,
    output var logic [11:0]  MAXIGP0WID,
    output var logic         MAXIGP0WLAST,
    output var logic [3:0]   MAXIGP0WSTRB,
    output var logic         MAXIGP0WVALID,
    output var logic [31:0]  MAXIGP1ARADDR,
    output var logic [1:0]   MAXIGP1ARBURST,
    output var logic [3:0]   MAXIGP1ARCACHE,
    output var logic         MAXIGP1ARESETN,
    output var logic [11:0]  MAXIGP1ARID,
    output var logic [3:0]   MAXIGP1ARLEN,
    output var logic [1:0]   MAXIGP1ARLOCK,
    output var logic [2:0]   MAXIGP1ARPROT,
    output var logic [3:0]   MAXIGP1ARQOS,
    output var logic [1:0]   MAXIGP1ARSIZE,
    output var logic         MAXIGP1ARVALID,
    output var logic [31:0]  MAXIGP1AWADDR,
    output var logic [1:0]   MAXIGP1AWBURST,
    output var logic [3:0]   MAXIGP1AWCACHE,
    output var logic [11:0]  MAXIGP1AWID,
    output var logic [3:0]   MAXIGP1AWLEN,
    output var logic [1:0]   MAXIGP1AWLOCK,
    output var logic [2:0]   MAXIGP1AWPROT,
    output var logic [3:0]   MAXIGP1AWQOS,
    output var logic [1:0]   MAXIGP1AWSIZE,
    output var logic         MAXIGP1AWVALID,
    output var logic         MAXIGP1BREADY,
    output var logic         MAXIGP1RREADY,
    output var logic [31:0]  MAXIGP1WDATA,
    output var logic [11:0]  MAXIGP1WID,
    output var logic         MAXIGP1WLAST,
    output var logic [3:0]   MAXIGP1WSTRB,
    output var logic         MAXIGP1WVALID,
    output var logic         SAXIACPARESETN,
    output var logic         SAXIACPARREADY,
    output var logic         SAXIACPAWREADY,
    output var logic [2:0]   SAXIACPBID,
    output var logic [1:0]   SAXIACPBRESP,
    output var logic         SAXIACPBVALID,
    output var logic [63:0]  SAXIACPRDATA,
    output var logic [2:0]   SAXIACPRID,
    output var logic         SAXIACPRLAST,
    output var logic [1:0]   SAXIACPRRESP,
    output var logic         SAXIACPRVALID,
    output var logic         SAXIACPWREADY,
    output var logic         SAXIGP0ARESETN,
    output var logic         SAXIGP0ARREADY,
    output var logic         SAXIGP0AWREADY,
    output var logic [5:0]   SAXIGP0BID,
    output var logic [1:0]   SAXIGP0BRESP,
    output var logic         SAXIGP0BVALID,
    output var logic [31:0]  SAXIGP0RDATA,
    output var logic [5:0]   SAXIGP0RID,
    output var logic         SAXIGP0RLAST,
    output var logic [1:0]   SAXIGP0RRESP,
    output var logic         SAXIGP0RVALID,
    output var logic         SAXIGP0WREADY,
    output var logic         SAXIGP1ARESETN,
    output var logic         SAXIGP1ARREADY,
    output var logic         SAXIGP1AWREADY,
    output var logic [5:0]   SAXIGP1BID,
    output var logic [1:0]   SAXIGP1BRESP,
    output var logic         SAXIGP1BVALID,
    output var logic [31:0]  SAXIGP1RDATA,
    output var logic [5:0]   SAXIGP1RID,
    output var logic         SAXIGP1RLAST,
    output var logic [1:0]   SAXIGP1RRESP,
    output var logic         SAXIGP1RVALID,
    output var logic         SAXIGP1WREADY,
    output var logic         SAXIHP0ARESETN,
    output var logic         SAXIHP0ARREADY,
    output var logic         SAXIHP0AWREADY,
    output var logic [5:0]   SAXIHP0BID,
    output var logic [1:0]   SAXIHP0BRESP,
    output var logic         SAXIHP0BVALID,
    output var logic [2:0]   SAXIHP0RACOUNT,
    output var logic [7:0]   SAXIHP0RCOUNT,
    output var logic [63:0]  SAXIHP0RDATA,
    output var logic [5:0]   SAXIHP0RID,
    output var logic         SAXIHP0RLAST,
    output var logic [1:0]   SAXIHP0RRESP,
    output var logic         SAXIHP0RVALID,
    output var logic [5:0]   SAXIHP0WACOUNT,
    output var logic [7:0]   SAXIHP0WCOUNT,
    output var logic         SAXIHP0WREADY,
    output var logic         SAXIHP1ARESETN,
    output var logic         SAXIHP1ARREADY,
    output var logic         SAXIHP1AWREADY,
    output var logic [5:0]   SAXIHP1BID,
    output var logic [1:0]   SAXIHP1BRESP,
    output var logic         SAXIHP1BVALID,
    output var logic [2:0]   SAXIHP1RACOUNT,
    output var logic [7:0]   SAXIHP1RCOUNT,
    output var logic [63:0]  SAXIHP1RDATA,
    output var logic [5:0]   SAXIHP1RID,
    output var logic         SAXIHP1RLAST,
    output var logic [1:0]   SAXIHP1RRESP,
    output var logic         SAXIHP1RVALID,
    output var logic [5:0]   SAXIHP1WACOUNT,
    output var logic [7:0]   SAXIHP1WCOUNT,
    output var logic         SAXIHP1WREADY,
    output var logic         SAXIHP2ARESETN,
    output var logic         SAXIHP2ARREADY,
    output var logic         SAXIHP2AWREADY,
    output var logic [5:0]   SAXIHP2BID,
    output var logic [1:0]   SAXIHP2BRESP,
    output var logic         SAXIHP2BVALID,
    output var logic [2:0]   SAXIHP2RACOUNT,
    output var logic [7:0]   SAXIHP2RCOUNT,
    output var logic [63:0]  SAXIHP2RDATA,
    output var logic [5:0]   SAXIHP2RID,
    output var logic         SAXIHP2RLAST,
    output var logic [1:0]   SAXIHP2RRESP,
    output var logic         SAXIHP2RVALID,
    output var logic [5:0]   SAXIHP2WACOUNT,
    output var logic [7:0]   SAXIHP2WCOUNT,
    output var logic         SAXIHP2WREADY,
    output var logic         SAXIHP3ARESETN,
    output var logic         SAXIHP3ARREADY,
    output var logic         SAXIHP3AWREADY,
    output var logic [5:0]   SAXIHP3BID,
    output var logic [1:0]   SAXIHP3BRESP,
    output var logic         SAXIHP3BVALID,
    output var logic [2:0]   SAXIHP3RACOUNT,
    output var logic [7:0]   SAXIHP3RCOUNT,
    output var logic [63:0]  SAXIHP3RDATA,
    output var logic [5:0]   SAXIHP3RID,
    output var logic         SAXIHP3RLAST,
    output var logic [1:0]   SAXIHP3RRESP,
    output var logic         SAXIHP3RVALID,
    output var logic [5:0]   SAXIHP3WACOUNT,
    output var logic [7:0]   SAXIHP3WCOUNT,
    output var logic         SAXIHP3WREADY,
    inout  wire       [14:0]  DDRA,
    inout  wire       [2:0]   DDRBA,
    inout  wire               DDRCASB,
    inout  wire               DDRCKE,
    inout  wire               DDRCKN,
    inout  wire               DDRCKP,
    inout  wire               DDRCSB,
    inout  wire       [3:0]   DDRDM,
    inout  wire       [31:0]  DDRDQ,
    inout  wire       [3:0]   DDRDQSN,
    inout  wire       [3:0]   DDRDQSP,
    inout  wire               DDRDRSTB,
    inout  wire               DDRODT,
    inout  wire               DDRRASB,
    inout  wire               DDRVRN,
    inout  wire               DDRVRP,
    inout  wire               DDRWEB,
    inout  wire       [53:0]  MIO,
    inout  wire               PSCLK,
    inout  wire               PSPORB,
    inout  wire               PSSRSTB,
    input  var logic [3:0]   DDRARB,
    input  var logic         DMA0ACLK,
    input  var logic         DMA0DAREADY,
    input  var logic         DMA0DRLAST,
    input  var logic [1:0]   DMA0DRTYPE,
    input  var logic         DMA0DRVALID,
    input  var logic         DMA1ACLK,
    input  var logic         DMA1DAREADY,
    input  var logic         DMA1DRLAST,
    input  var logic [1:0]   DMA1DRTYPE,
    input  var logic         DMA1DRVALID,
    input  var logic         DMA2ACLK,
    input  var logic         DMA2DAREADY,
    input  var logic         DMA2DRLAST,
    input  var logic [1:0]   DMA2DRTYPE,
    input  var logic         DMA2DRVALID,
    input  var logic         DMA3ACLK,
    input  var logic         DMA3DAREADY,
    input  var logic         DMA3DRLAST,
    input  var logic [1:0]   DMA3DRTYPE,
    input  var logic         DMA3DRVALID,
    input  var logic         EMIOCAN0PHYRX,
    input  var logic         EMIOCAN1PHYRX,
    input  var logic         EMIOENET0EXTINTIN,
    input  var logic         EMIOENET0GMIICOL,
    input  var logic         EMIOENET0GMIICRS,
    input  var logic         EMIOENET0GMIIRXCLK,
    input  var logic [7:0]   EMIOENET0GMIIRXD,
    input  var logic         EMIOENET0GMIIRXDV,
    input  var logic         EMIOENET0GMIIRXER,
    input  var logic         EMIOENET0GMIITXCLK,
    input  var logic         EMIOENET0MDIOI,
    input  var logic         EMIOENET1EXTINTIN,
    input  var logic         EMIOENET1GMIICOL,
    input  var logic         EMIOENET1GMIICRS,
    input  var logic         EMIOENET1GMIIRXCLK,
    input  var logic [7:0]   EMIOENET1GMIIRXD,
    input  var logic         EMIOENET1GMIIRXDV,
    input  var logic         EMIOENET1GMIIRXER,
    input  var logic         EMIOENET1GMIITXCLK,
    input  var logic         EMIOENET1MDIOI,
    input  var logic [63:0]  EMIOGPIOI,
    input  var logic         EMIOI2C0SCLI,
    input  var logic         EMIOI2C0SDAI,
    input  var logic         EMIOI2C1SCLI,
    input  var logic         EMIOI2C1SDAI,
    input  var logic         EMIOPJTAGTCK,
    input  var logic         EMIOPJTAGTDI,
    input  var logic         EMIOPJTAGTMS,
    input  var logic         EMIOSDIO0CDN,
    input  var logic         EMIOSDIO0CLKFB,
    input  var logic         EMIOSDIO0CMDI,
    input  var logic [3:0]   EMIOSDIO0DATAI,
    input  var logic         EMIOSDIO0WP,
    input  var logic         EMIOSDIO1CDN,
    input  var logic         EMIOSDIO1CLKFB,
    input  var logic         EMIOSDIO1CMDI,
    input  var logic [3:0]   EMIOSDIO1DATAI,
    input  var logic         EMIOSDIO1WP,
    input  var logic         EMIOSPI0MI,
    input  var logic         EMIOSPI0SCLKI,
    input  var logic         EMIOSPI0SI,
    input  var logic         EMIOSPI0SSIN,
    input  var logic         EMIOSPI1MI,
    input  var logic         EMIOSPI1SCLKI,
    input  var logic         EMIOSPI1SI,
    input  var logic         EMIOSPI1SSIN,
    input  var logic         EMIOSRAMINTIN,
    input  var logic         EMIOTRACECLK,
    input  var logic [2:0]   EMIOTTC0CLKI,
    input  var logic [2:0]   EMIOTTC1CLKI,
    input  var logic         EMIOUART0CTSN,
    input  var logic         EMIOUART0DCDN,
    input  var logic         EMIOUART0DSRN,
    input  var logic         EMIOUART0RIN,
    input  var logic         EMIOUART0RX,
    input  var logic         EMIOUART1CTSN,
    input  var logic         EMIOUART1DCDN,
    input  var logic         EMIOUART1DSRN,
    input  var logic         EMIOUART1RIN,
    input  var logic         EMIOUART1RX,
    input  var logic         EMIOUSB0VBUSPWRFAULT,
    input  var logic         EMIOUSB1VBUSPWRFAULT,
    input  var logic         EMIOWDTCLKI,
    input  var logic         EVENTEVENTI,
    input  var logic [3:0]   FCLKCLKTRIGN,
    input  var logic         FPGAIDLEN,
    input  var logic [3:0]   FTMDTRACEINATID,
    input  var logic         FTMDTRACEINCLOCK,
    input  var logic [31:0]  FTMDTRACEINDATA,
    input  var logic         FTMDTRACEINVALID,
    input  var logic [31:0]  FTMTF2PDEBUG,
    input  var logic [3:0]   FTMTF2PTRIG,
    input  var logic [3:0]   FTMTP2FTRIGACK,
    input  var logic [19:0]  IRQF2P,
    input  var logic         MAXIGP0ACLK,
    input  var logic         MAXIGP0ARREADY,
    input  var logic         MAXIGP0AWREADY,
    input  var logic [11:0]  MAXIGP0BID,
    input  var logic [1:0]   MAXIGP0BRESP,
    input  var logic         MAXIGP0BVALID,
    input  var logic [31:0]  MAXIGP0RDATA,
    input  var logic [11:0]  MAXIGP0RID,
    input  var logic         MAXIGP0RLAST,
    input  var logic [1:0]   MAXIGP0RRESP,
    input  var logic         MAXIGP0RVALID,
    input  var logic         MAXIGP0WREADY,
    input  var logic         MAXIGP1ACLK,
    input  var logic         MAXIGP1ARREADY,
    input  var logic         MAXIGP1AWREADY,
    input  var logic [11:0]  MAXIGP1BID,
    input  var logic [1:0]   MAXIGP1BRESP,
    input  var logic         MAXIGP1BVALID,
    input  var logic [31:0]  MAXIGP1RDATA,
    input  var logic [11:0]  MAXIGP1RID,
    input  var logic         MAXIGP1RLAST,
    input  var logic [1:0]   MAXIGP1RRESP,
    input  var logic         MAXIGP1RVALID,
    input  var logic         MAXIGP1WREADY,
    input  var logic         SAXIACPACLK,
    input  var logic [31:0]  SAXIACPARADDR,
    input  var logic [1:0]   SAXIACPARBURST,
    input  var logic [3:0]   SAXIACPARCACHE,
    input  var logic [2:0]   SAXIACPARID,
    input  var logic [3:0]   SAXIACPARLEN,
    input  var logic [1:0]   SAXIACPARLOCK,
    input  var logic [2:0]   SAXIACPARPROT,
    input  var logic [3:0]   SAXIACPARQOS,
    input  var logic [1:0]   SAXIACPARSIZE,
    input  var logic [4:0]   SAXIACPARUSER,
    input  var logic         SAXIACPARVALID,
    input  var logic [31:0]  SAXIACPAWADDR,
    input  var logic [1:0]   SAXIACPAWBURST,
    input  var logic [3:0]   SAXIACPAWCACHE,
    input  var logic [2:0]   SAXIACPAWID,
    input  var logic [3:0]   SAXIACPAWLEN,
    input  var logic [1:0]   SAXIACPAWLOCK,
    input  var logic [2:0]   SAXIACPAWPROT,
    input  var logic [3:0]   SAXIACPAWQOS,
    input  var logic [1:0]   SAXIACPAWSIZE,
    input  var logic [4:0]   SAXIACPAWUSER,
    input  var logic         SAXIACPAWVALID,
    input  var logic         SAXIACPBREADY,
    input  var logic         SAXIACPRREADY,
    input  var logic [63:0]  SAXIACPWDATA,
    input  var logic [2:0]   SAXIACPWID,
    input  var logic         SAXIACPWLAST,
    input  var logic [7:0]   SAXIACPWSTRB,
    input  var logic         SAXIACPWVALID,
    input  var logic         SAXIGP0ACLK,
    input  var logic [31:0]  SAXIGP0ARADDR,
    input  var logic [1:0]   SAXIGP0ARBURST,
    input  var logic [3:0]   SAXIGP0ARCACHE,
    input  var logic [5:0]   SAXIGP0ARID,
    input  var logic [3:0]   SAXIGP0ARLEN,
    input  var logic [1:0]   SAXIGP0ARLOCK,
    input  var logic [2:0]   SAXIGP0ARPROT,
    input  var logic [3:0]   SAXIGP0ARQOS,
    input  var logic [1:0]   SAXIGP0ARSIZE,
    input  var logic         SAXIGP0ARVALID,
    input  var logic [31:0]  SAXIGP0AWADDR,
    input  var logic [1:0]   SAXIGP0AWBURST,
    input  var logic [3:0]   SAXIGP0AWCACHE,
    input  var logic [5:0]   SAXIGP0AWID,
    input  var logic [3:0]   SAXIGP0AWLEN,
    input  var logic [1:0]   SAXIGP0AWLOCK,
    input  var logic [2:0]   SAXIGP0AWPROT,
    input  var logic [3:0]   SAXIGP0AWQOS,
    input  var logic [1:0]   SAXIGP0AWSIZE,
    input  var logic         SAXIGP0AWVALID,
    input  var logic         SAXIGP0BREADY,
    input  var logic         SAXIGP0RREADY,
    input  var logic [31:0]  SAXIGP0WDATA,
    input  var logic [5:0]   SAXIGP0WID,
    input  var logic         SAXIGP0WLAST,
    input  var logic [3:0]   SAXIGP0WSTRB,
    input  var logic         SAXIGP0WVALID,
    input  var logic         SAXIGP1ACLK,
    input  var logic [31:0]  SAXIGP1ARADDR,
    input  var logic [1:0]   SAXIGP1ARBURST,
    input  var logic [3:0]   SAXIGP1ARCACHE,
    input  var logic [5:0]   SAXIGP1ARID,
    input  var logic [3:0]   SAXIGP1ARLEN,
    input  var logic [1:0]   SAXIGP1ARLOCK,
    input  var logic [2:0]   SAXIGP1ARPROT,
    input  var logic [3:0]   SAXIGP1ARQOS,
    input  var logic [1:0]   SAXIGP1ARSIZE,
    input  var logic         SAXIGP1ARVALID,
    input  var logic [31:0]  SAXIGP1AWADDR,
    input  var logic [1:0]   SAXIGP1AWBURST,
    input  var logic [3:0]   SAXIGP1AWCACHE,
    input  var logic [5:0]   SAXIGP1AWID,
    input  var logic [3:0]   SAXIGP1AWLEN,
    input  var logic [1:0]   SAXIGP1AWLOCK,
    input  var logic [2:0]   SAXIGP1AWPROT,
    input  var logic [3:0]   SAXIGP1AWQOS,
    input  var logic [1:0]   SAXIGP1AWSIZE,
    input  var logic         SAXIGP1AWVALID,
    input  var logic         SAXIGP1BREADY,
    input  var logic         SAXIGP1RREADY,
    input  var logic [31:0]  SAXIGP1WDATA,
    input  var logic [5:0]   SAXIGP1WID,
    input  var logic         SAXIGP1WLAST,
    input  var logic [3:0]   SAXIGP1WSTRB,
    input  var logic         SAXIGP1WVALID,
    input  var logic         SAXIHP0ACLK,
    input  var logic [31:0]  SAXIHP0ARADDR,
    input  var logic [1:0]   SAXIHP0ARBURST,
    input  var logic [3:0]   SAXIHP0ARCACHE,
    input  var logic [5:0]   SAXIHP0ARID,
    input  var logic [3:0]   SAXIHP0ARLEN,
    input  var logic [1:0]   SAXIHP0ARLOCK,
    input  var logic [2:0]   SAXIHP0ARPROT,
    input  var logic [3:0]   SAXIHP0ARQOS,
    input  var logic [1:0]   SAXIHP0ARSIZE,
    input  var logic         SAXIHP0ARVALID,
    input  var logic [31:0]  SAXIHP0AWADDR,
    input  var logic [1:0]   SAXIHP0AWBURST,
    input  var logic [3:0]   SAXIHP0AWCACHE,
    input  var logic [5:0]   SAXIHP0AWID,
    input  var logic [3:0]   SAXIHP0AWLEN,
    input  var logic [1:0]   SAXIHP0AWLOCK,
    input  var logic [2:0]   SAXIHP0AWPROT,
    input  var logic [3:0]   SAXIHP0AWQOS,
    input  var logic [1:0]   SAXIHP0AWSIZE,
    input  var logic         SAXIHP0AWVALID,
    input  var logic         SAXIHP0BREADY,
    input  var logic         SAXIHP0RDISSUECAP1EN,
    input  var logic         SAXIHP0RREADY,
    input  var logic [63:0]  SAXIHP0WDATA,
    input  var logic [5:0]   SAXIHP0WID,
    input  var logic         SAXIHP0WLAST,
    input  var logic         SAXIHP0WRISSUECAP1EN,
    input  var logic [7:0]   SAXIHP0WSTRB,
    input  var logic         SAXIHP0WVALID,
    input  var logic         SAXIHP1ACLK,
    input  var logic [31:0]  SAXIHP1ARADDR,
    input  var logic [1:0]   SAXIHP1ARBURST,
    input  var logic [3:0]   SAXIHP1ARCACHE,
    input  var logic [5:0]   SAXIHP1ARID,
    input  var logic [3:0]   SAXIHP1ARLEN,
    input  var logic [1:0]   SAXIHP1ARLOCK,
    input  var logic [2:0]   SAXIHP1ARPROT,
    input  var logic [3:0]   SAXIHP1ARQOS,
    input  var logic [1:0]   SAXIHP1ARSIZE,
    input  var logic         SAXIHP1ARVALID,
    input  var logic [31:0]  SAXIHP1AWADDR,
    input  var logic [1:0]   SAXIHP1AWBURST,
    input  var logic [3:0]   SAXIHP1AWCACHE,
    input  var logic [5:0]   SAXIHP1AWID,
    input  var logic [3:0]   SAXIHP1AWLEN,
    input  var logic [1:0]   SAXIHP1AWLOCK,
    input  var logic [2:0]   SAXIHP1AWPROT,
    input  var logic [3:0]   SAXIHP1AWQOS,
    input  var logic [1:0]   SAXIHP1AWSIZE,
    input  var logic         SAXIHP1AWVALID,
    input  var logic         SAXIHP1BREADY,
    input  var logic         SAXIHP1RDISSUECAP1EN,
    input  var logic         SAXIHP1RREADY,
    input  var logic [63:0]  SAXIHP1WDATA,
    input  var logic [5:0]   SAXIHP1WID,
    input  var logic         SAXIHP1WLAST,
    input  var logic         SAXIHP1WRISSUECAP1EN,
    input  var logic [7:0]   SAXIHP1WSTRB,
    input  var logic         SAXIHP1WVALID,
    input  var logic         SAXIHP2ACLK,
    input  var logic [31:0]  SAXIHP2ARADDR,
    input  var logic [1:0]   SAXIHP2ARBURST,
    input  var logic [3:0]   SAXIHP2ARCACHE,
    input  var logic [5:0]   SAXIHP2ARID,
    input  var logic [3:0]   SAXIHP2ARLEN,
    input  var logic [1:0]   SAXIHP2ARLOCK,
    input  var logic [2:0]   SAXIHP2ARPROT,
    input  var logic [3:0]   SAXIHP2ARQOS,
    input  var logic [1:0]   SAXIHP2ARSIZE,
    input  var logic         SAXIHP2ARVALID,
    input  var logic [31:0]  SAXIHP2AWADDR,
    input  var logic [1:0]   SAXIHP2AWBURST,
    input  var logic [3:0]   SAXIHP2AWCACHE,
    input  var logic [5:0]   SAXIHP2AWID,
    input  var logic [3:0]   SAXIHP2AWLEN,
    input  var logic [1:0]   SAXIHP2AWLOCK,
    input  var logic [2:0]   SAXIHP2AWPROT,
    input  var logic [3:0]   SAXIHP2AWQOS,
    input  var logic [1:0]   SAXIHP2AWSIZE,
    input  var logic         SAXIHP2AWVALID,
    input  var logic         SAXIHP2BREADY,
    input  var logic         SAXIHP2RDISSUECAP1EN,
    input  var logic         SAXIHP2RREADY,
    input  var logic [63:0]  SAXIHP2WDATA,
    input  var logic [5:0]   SAXIHP2WID,
    input  var logic         SAXIHP2WLAST,
    input  var logic         SAXIHP2WRISSUECAP1EN,
    input  var logic [7:0]   SAXIHP2WSTRB,
    input  var logic         SAXIHP2WVALID,
    input  var logic         SAXIHP3ACLK,
    input  var logic [31:0]  SAXIHP3ARADDR,
    input  var logic [1:0]   SAXIHP3ARBURST,
    input  var logic [3:0]   SAXIHP3ARCACHE,
    input  var logic [5:0]   SAXIHP3ARID,
    input  var logic [3:0]   SAXIHP3ARLEN,
    input  var logic [1:0]   SAXIHP3ARLOCK,
    input  var logic [2:0]   SAXIHP3ARPROT,
    input  var logic [3:0]   SAXIHP3ARQOS,
    input  var logic [1:0]   SAXIHP3ARSIZE,
    input  var logic         SAXIHP3ARVALID,
    input  var logic [31:0]  SAXIHP3AWADDR,
    input  var logic [1:0]   SAXIHP3AWBURST,
    input  var logic [3:0]   SAXIHP3AWCACHE,
    input  var logic [5:0]   SAXIHP3AWID,
    input  var logic [3:0]   SAXIHP3AWLEN,
    input  var logic [1:0]   SAXIHP3AWLOCK,
    input  var logic [2:0]   SAXIHP3AWPROT,
    input  var logic [3:0]   SAXIHP3AWQOS,
    input  var logic [1:0]   SAXIHP3AWSIZE,
    input  var logic         SAXIHP3AWVALID,
    input  var logic         SAXIHP3BREADY,
    input  var logic         SAXIHP3RDISSUECAP1EN,
    input  var logic         SAXIHP3RREADY,
    input  var logic [63:0]  SAXIHP3WDATA,
    input  var logic [5:0]   SAXIHP3WID,
    input  var logic         SAXIHP3WLAST,
    input  var logic         SAXIHP3WRISSUECAP1EN,
    input  var logic [7:0]   SAXIHP3WSTRB,
    input  var logic         SAXIHP3WVALID
);

  assign DMA0DATYPE = 2'b0;
  assign DMA0DAVALID = 1'b0;
  assign DMA0DRREADY = 1'b0;
  assign DMA0RSTN = 1'b0;
  assign DMA1DATYPE = 2'b0;
  assign DMA1DAVALID = 1'b0;
  assign DMA1DRREADY = 1'b0;
  assign DMA1RSTN = 1'b0;
  assign DMA2DATYPE = 2'b0;
  assign DMA2DAVALID = 1'b0;
  assign DMA2DRREADY = 1'b0;
  assign DMA2RSTN = 1'b0;
  assign DMA3DATYPE = 2'b0;
  assign DMA3DAVALID = 1'b0;
  assign DMA3DRREADY = 1'b0;
  assign DMA3RSTN = 1'b0;
  assign EMIOCAN0PHYTX = 1'b0;
  assign EMIOCAN1PHYTX = 1'b0;
  assign EMIOENET0GMIITXD = 8'b0;
  assign EMIOENET0GMIITXEN = 1'b0;
  assign EMIOENET0GMIITXER = 1'b0;
  assign EMIOENET0MDIOMDC = 1'b0;
  assign EMIOENET0MDIOO = 1'b0;
  assign EMIOENET0MDIOTN = 1'b0;
  assign EMIOENET0PTPDELAYREQRX = 1'b0;
  assign EMIOENET0PTPDELAYREQTX = 1'b0;
  assign EMIOENET0PTPPDELAYREQRX = 1'b0;
  assign EMIOENET0PTPPDELAYREQTX = 1'b0;
  assign EMIOENET0PTPPDELAYRESPRX = 1'b0;
  assign EMIOENET0PTPPDELAYRESPTX = 1'b0;
  assign EMIOENET0PTPSYNCFRAMERX = 1'b0;
  assign EMIOENET0PTPSYNCFRAMETX = 1'b0;
  assign EMIOENET0SOFRX = 1'b0;
  assign EMIOENET0SOFTX = 1'b0;
  assign EMIOENET1GMIITXD = 8'b0;
  assign EMIOENET1GMIITXEN = 1'b0;
  assign EMIOENET1GMIITXER = 1'b0;
  assign EMIOENET1MDIOMDC = 1'b0;
  assign EMIOENET1MDIOO = 1'b0;
  assign EMIOENET1MDIOTN = 1'b0;
  assign EMIOENET1PTPDELAYREQRX = 1'b0;
  assign EMIOENET1PTPDELAYREQTX = 1'b0;
  assign EMIOENET1PTPPDELAYREQRX = 1'b0;
  assign EMIOENET1PTPPDELAYREQTX = 1'b0;
  assign EMIOENET1PTPPDELAYRESPRX = 1'b0;
  assign EMIOENET1PTPPDELAYRESPTX = 1'b0;
  assign EMIOENET1PTPSYNCFRAMERX = 1'b0;
  assign EMIOENET1PTPSYNCFRAMETX = 1'b0;
  assign EMIOENET1SOFRX = 1'b0;
  assign EMIOENET1SOFTX = 1'b0;
  assign EMIOGPIOO = 64'b0;
  assign EMIOGPIOTN = 64'b0;
  assign EMIOI2C0SCLO = 1'b0;
  assign EMIOI2C0SCLTN = 1'b0;
  assign EMIOI2C0SDAO = 1'b0;
  assign EMIOI2C0SDATN = 1'b0;
  assign EMIOI2C1SCLO = 1'b0;
  assign EMIOI2C1SCLTN = 1'b0;
  assign EMIOI2C1SDAO = 1'b0;
  assign EMIOI2C1SDATN = 1'b0;
  assign EMIOPJTAGTDO = 1'b0;
  assign EMIOPJTAGTDTN = 1'b0;
  assign EMIOSDIO0BUSPOW = 1'b0;
  assign EMIOSDIO0BUSVOLT = 3'b0;
  assign EMIOSDIO0CLK = 1'b0;
  assign EMIOSDIO0CMDO = 1'b0;
  assign EMIOSDIO0CMDTN = 1'b0;
  assign EMIOSDIO0DATAO = 4'b0;
  assign EMIOSDIO0DATATN = 4'b0;
  assign EMIOSDIO0LED = 1'b0;
  assign EMIOSDIO1BUSPOW = 1'b0;
  assign EMIOSDIO1BUSVOLT = 3'b0;
  assign EMIOSDIO1CLK = 1'b0;
  assign EMIOSDIO1CMDO = 1'b0;
  assign EMIOSDIO1CMDTN = 1'b0;
  assign EMIOSDIO1DATAO = 4'b0;
  assign EMIOSDIO1DATATN = 4'b0;
  assign EMIOSDIO1LED = 1'b0;
  assign EMIOSPI0MO = 1'b0;
  assign EMIOSPI0MOTN = 1'b0;
  assign EMIOSPI0SCLKO = 1'b0;
  assign EMIOSPI0SCLKTN = 1'b0;
  assign EMIOSPI0SO = 1'b0;
  assign EMIOSPI0SSNTN = 1'b0;
  assign EMIOSPI0SSON = 3'b0;
  assign EMIOSPI0STN = 1'b0;
  assign EMIOSPI1MO = 1'b0;
  assign EMIOSPI1MOTN = 1'b0;
  assign EMIOSPI1SCLKO = 1'b0;
  assign EMIOSPI1SCLKTN = 1'b0;
  assign EMIOSPI1SO = 1'b0;
  assign EMIOSPI1SSNTN = 1'b0;
  assign EMIOSPI1SSON = 3'b0;
  assign EMIOSPI1STN = 1'b0;
  assign EMIOTRACECTL = 1'b0;
  assign EMIOTRACEDATA = 32'b0;
  assign EMIOTTC0WAVEO = 3'b0;
  assign EMIOTTC1WAVEO = 3'b0;
  assign EMIOUART0DTRN = 1'b0;
  assign EMIOUART0RTSN = 1'b0;
  assign EMIOUART0TX = 1'b0;
  assign EMIOUART1DTRN = 1'b0;
  assign EMIOUART1RTSN = 1'b0;
  assign EMIOUART1TX = 1'b0;
  assign EMIOUSB0PORTINDCTL = 2'b0;
  assign EMIOUSB0VBUSPWRSELECT = 1'b0;
  assign EMIOUSB1PORTINDCTL = 2'b0;
  assign EMIOUSB1VBUSPWRSELECT = 1'b0;
  assign EMIOWDTRSTO = 1'b0;
  assign EVENTEVENTO = 1'b0;
  assign EVENTSTANDBYWFE = 2'b0;
  assign EVENTSTANDBYWFI = 2'b0;
  assign FCLKCLK = 4'b0;
  assign FCLKRESETN = 4'b0;
  assign FTMTF2PTRIGACK = 4'b0;
  assign FTMTP2FDEBUG = 32'b0;
  assign FTMTP2FTRIG = 4'b0;
  assign IRQP2F = 29'b0;
  assign MAXIGP0ARADDR = 32'b0;
  assign MAXIGP0ARBURST = 2'b0;
  assign MAXIGP0ARCACHE = 4'b0;
  assign MAXIGP0ARESETN = 1'b0;
  assign MAXIGP0ARID = 12'b0;
  assign MAXIGP0ARLEN = 4'b0;
  assign MAXIGP0ARLOCK = 2'b0;
  assign MAXIGP0ARPROT = 3'b0;
  assign MAXIGP0ARQOS = 4'b0;
  assign MAXIGP0ARSIZE = 2'b0;
  assign MAXIGP0ARVALID = 1'b0;
  assign MAXIGP0AWADDR = 32'b0;
  assign MAXIGP0AWBURST = 2'b0;
  assign MAXIGP0AWCACHE = 4'b0;
  assign MAXIGP0AWID = 12'b0;
  assign MAXIGP0AWLEN = 4'b0;
  assign MAXIGP0AWLOCK = 2'b0;
  assign MAXIGP0AWPROT = 3'b0;
  assign MAXIGP0AWQOS = 4'b0;
  assign MAXIGP0AWSIZE = 2'b0;
  assign MAXIGP0AWVALID = 1'b0;
  assign MAXIGP0BREADY = 1'b0;
  assign MAXIGP0RREADY = 1'b0;
  assign MAXIGP0WDATA = 32'b0;
  assign MAXIGP0WID = 12'b0;
  assign MAXIGP0WLAST = 1'b0;
  assign MAXIGP0WSTRB = 4'b0;
  assign MAXIGP0WVALID = 1'b0;
  assign MAXIGP1ARADDR = 32'b0;
  assign MAXIGP1ARBURST = 2'b0;
  assign MAXIGP1ARCACHE = 4'b0;
  assign MAXIGP1ARESETN = 1'b0;
  assign MAXIGP1ARID = 12'b0;
  assign MAXIGP1ARLEN = 4'b0;
  assign MAXIGP1ARLOCK = 2'b0;
  assign MAXIGP1ARPROT = 3'b0;
  assign MAXIGP1ARQOS = 4'b0;
  assign MAXIGP1ARSIZE = 2'b0;
  assign MAXIGP1ARVALID = 1'b0;
  assign MAXIGP1AWADDR = 32'b0;
  assign MAXIGP1AWBURST = 2'b0;
  assign MAXIGP1AWCACHE = 4'b0;
  assign MAXIGP1AWID = 12'b0;
  assign MAXIGP1AWLEN = 4'b0;
  assign MAXIGP1AWLOCK = 2'b0;
  assign MAXIGP1AWPROT = 3'b0;
  assign MAXIGP1AWQOS = 4'b0;
  assign MAXIGP1AWSIZE = 2'b0;
  assign MAXIGP1AWVALID = 1'b0;
  assign MAXIGP1BREADY = 1'b0;
  assign MAXIGP1RREADY = 1'b0;
  assign MAXIGP1WDATA = 32'b0;
  assign MAXIGP1WID = 12'b0;
  assign MAXIGP1WLAST = 1'b0;
  assign MAXIGP1WSTRB = 4'b0;
  assign MAXIGP1WVALID = 1'b0;
  assign SAXIACPARESETN = 1'b0;
  assign SAXIACPARREADY = 1'b0;
  assign SAXIACPAWREADY = 1'b0;
  assign SAXIACPBID = 3'b0;
  assign SAXIACPBRESP = 2'b0;
  assign SAXIACPBVALID = 1'b0;
  assign SAXIACPRDATA = 64'b0;
  assign SAXIACPRID = 3'b0;
  assign SAXIACPRLAST = 1'b0;
  assign SAXIACPRRESP = 2'b0;
  assign SAXIACPRVALID = 1'b0;
  assign SAXIACPWREADY = 1'b0;
  assign SAXIGP0ARESETN = 1'b0;
  assign SAXIGP0ARREADY = 1'b0;
  assign SAXIGP0AWREADY = 1'b0;
  assign SAXIGP0BID = 6'b0;
  assign SAXIGP0BRESP = 2'b0;
  assign SAXIGP0BVALID = 1'b0;
  assign SAXIGP0RDATA = 32'b0;
  assign SAXIGP0RID = 6'b0;
  assign SAXIGP0RLAST = 1'b0;
  assign SAXIGP0RRESP = 2'b0;
  assign SAXIGP0RVALID = 1'b0;
  assign SAXIGP0WREADY = 1'b0;
  assign SAXIGP1ARESETN = 1'b0;
  assign SAXIGP1ARREADY = 1'b0;
  assign SAXIGP1AWREADY = 1'b0;
  assign SAXIGP1BID = 6'b0;
  assign SAXIGP1BRESP = 2'b0;
  assign SAXIGP1BVALID = 1'b0;
  assign SAXIGP1RDATA = 32'b0;
  assign SAXIGP1RID = 6'b0;
  assign SAXIGP1RLAST = 1'b0;
  assign SAXIGP1RRESP = 2'b0;
  assign SAXIGP1RVALID = 1'b0;
  assign SAXIGP1WREADY = 1'b0;
  assign SAXIHP0ARESETN = 1'b0;
  assign SAXIHP0ARREADY = 1'b0;
  assign SAXIHP0AWREADY = 1'b0;
  assign SAXIHP0BID = 6'b0;
  assign SAXIHP0BRESP = 2'b0;
  assign SAXIHP0BVALID = 1'b0;
  assign SAXIHP0RACOUNT = 3'b0;
  assign SAXIHP0RCOUNT = 8'b0;
  assign SAXIHP0RDATA = 64'b0;
  assign SAXIHP0RID = 6'b0;
  assign SAXIHP0RLAST = 1'b0;
  assign SAXIHP0RRESP = 2'b0;
  assign SAXIHP0RVALID = 1'b0;
  assign SAXIHP0WACOUNT = 6'b0;
  assign SAXIHP0WCOUNT = 8'b0;
  assign SAXIHP0WREADY = 1'b0;
  assign SAXIHP1ARESETN = 1'b0;
  assign SAXIHP1ARREADY = 1'b0;
  assign SAXIHP1AWREADY = 1'b0;
  assign SAXIHP1BID = 6'b0;
  assign SAXIHP1BRESP = 2'b0;
  assign SAXIHP1BVALID = 1'b0;
  assign SAXIHP1RACOUNT = 3'b0;
  assign SAXIHP1RCOUNT = 8'b0;
  assign SAXIHP1RDATA = 64'b0;
  assign SAXIHP1RID = 6'b0;
  assign SAXIHP1RLAST = 1'b0;
  assign SAXIHP1RRESP = 2'b0;
  assign SAXIHP1RVALID = 1'b0;
  assign SAXIHP1WACOUNT = 6'b0;
  assign SAXIHP1WCOUNT = 8'b0;
  assign SAXIHP1WREADY = 1'b0;
  assign SAXIHP2ARESETN = 1'b0;
  assign SAXIHP2ARREADY = 1'b0;
  assign SAXIHP2AWREADY = 1'b0;
  assign SAXIHP2BID = 6'b0;
  assign SAXIHP2BRESP = 2'b0;
  assign SAXIHP2BVALID = 1'b0;
  assign SAXIHP2RACOUNT = 3'b0;
  assign SAXIHP2RCOUNT = 8'b0;
  assign SAXIHP2RDATA = 64'b0;
  assign SAXIHP2RID = 6'b0;
  assign SAXIHP2RLAST = 1'b0;
  assign SAXIHP2RRESP = 2'b0;
  assign SAXIHP2RVALID = 1'b0;
  assign SAXIHP2WACOUNT = 6'b0;
  assign SAXIHP2WCOUNT = 8'b0;
  assign SAXIHP2WREADY = 1'b0;
  assign SAXIHP3ARESETN = 1'b0;
  assign SAXIHP3ARREADY = 1'b0;
  assign SAXIHP3AWREADY = 1'b0;
  assign SAXIHP3BID = 6'b0;
  assign SAXIHP3BRESP = 2'b0;
  assign SAXIHP3BVALID = 1'b0;
  assign SAXIHP3RACOUNT = 3'b0;
  assign SAXIHP3RCOUNT = 8'b0;
  assign SAXIHP3RDATA = 64'b0;
  assign SAXIHP3RID = 6'b0;
  assign SAXIHP3RLAST = 1'b0;
  assign SAXIHP3RRESP = 2'b0;
  assign SAXIHP3RVALID = 1'b0;
  assign SAXIHP3WACOUNT = 6'b0;
  assign SAXIHP3WCOUNT = 8'b0;
  assign SAXIHP3WREADY = 1'b0;

  // Every input, read once, so that lint has nothing to say about any of
  // them. The wrapper ties most of these to constants and a fold of
  // constants is still a fold: what it is for is the ones that are not.
  /* verilator lint_off UNUSEDSIGNAL */
  logic unused;
  assign unused = ^{1'b0,
                     DDRARB, DMA0ACLK, DMA0DAREADY, DMA0DRLAST, DMA0DRTYPE,
                     DMA0DRVALID, DMA1ACLK, DMA1DAREADY, DMA1DRLAST,
                     DMA1DRTYPE, DMA1DRVALID, DMA2ACLK, DMA2DAREADY,
                     DMA2DRLAST, DMA2DRTYPE, DMA2DRVALID, DMA3ACLK,
                     DMA3DAREADY, DMA3DRLAST, DMA3DRTYPE, DMA3DRVALID,
                     EMIOCAN0PHYRX, EMIOCAN1PHYRX, EMIOENET0EXTINTIN,
                     EMIOENET0GMIICOL, EMIOENET0GMIICRS, EMIOENET0GMIIRXCLK,
                     EMIOENET0GMIIRXD, EMIOENET0GMIIRXDV, EMIOENET0GMIIRXER,
                     EMIOENET0GMIITXCLK, EMIOENET0MDIOI, EMIOENET1EXTINTIN,
                     EMIOENET1GMIICOL, EMIOENET1GMIICRS, EMIOENET1GMIIRXCLK,
                     EMIOENET1GMIIRXD, EMIOENET1GMIIRXDV, EMIOENET1GMIIRXER,
                     EMIOENET1GMIITXCLK, EMIOENET1MDIOI, EMIOGPIOI,
                     EMIOI2C0SCLI, EMIOI2C0SDAI, EMIOI2C1SCLI, EMIOI2C1SDAI,
                     EMIOPJTAGTCK, EMIOPJTAGTDI, EMIOPJTAGTMS, EMIOSDIO0CDN,
                     EMIOSDIO0CLKFB, EMIOSDIO0CMDI, EMIOSDIO0DATAI,
                     EMIOSDIO0WP, EMIOSDIO1CDN, EMIOSDIO1CLKFB, EMIOSDIO1CMDI,
                     EMIOSDIO1DATAI, EMIOSDIO1WP, EMIOSPI0MI, EMIOSPI0SCLKI,
                     EMIOSPI0SI, EMIOSPI0SSIN, EMIOSPI1MI, EMIOSPI1SCLKI,
                     EMIOSPI1SI, EMIOSPI1SSIN, EMIOSRAMINTIN, EMIOTRACECLK,
                     EMIOTTC0CLKI, EMIOTTC1CLKI, EMIOUART0CTSN, EMIOUART0DCDN,
                     EMIOUART0DSRN, EMIOUART0RIN, EMIOUART0RX, EMIOUART1CTSN,
                     EMIOUART1DCDN, EMIOUART1DSRN, EMIOUART1RIN, EMIOUART1RX,
                     EMIOUSB0VBUSPWRFAULT, EMIOUSB1VBUSPWRFAULT, EMIOWDTCLKI,
                     EVENTEVENTI, FCLKCLKTRIGN, FPGAIDLEN, FTMDTRACEINATID,
                     FTMDTRACEINCLOCK, FTMDTRACEINDATA, FTMDTRACEINVALID,
                     FTMTF2PDEBUG, FTMTF2PTRIG, FTMTP2FTRIGACK, IRQF2P,
                     MAXIGP0ACLK, MAXIGP0ARREADY, MAXIGP0AWREADY, MAXIGP0BID,
                     MAXIGP0BRESP, MAXIGP0BVALID, MAXIGP0RDATA, MAXIGP0RID,
                     MAXIGP0RLAST, MAXIGP0RRESP, MAXIGP0RVALID, MAXIGP0WREADY,
                     MAXIGP1ACLK, MAXIGP1ARREADY, MAXIGP1AWREADY, MAXIGP1BID,
                     MAXIGP1BRESP, MAXIGP1BVALID, MAXIGP1RDATA, MAXIGP1RID,
                     MAXIGP1RLAST, MAXIGP1RRESP, MAXIGP1RVALID, MAXIGP1WREADY,
                     SAXIACPACLK, SAXIACPARADDR, SAXIACPARBURST,
                     SAXIACPARCACHE, SAXIACPARID, SAXIACPARLEN, SAXIACPARLOCK,
                     SAXIACPARPROT, SAXIACPARQOS, SAXIACPARSIZE,
                     SAXIACPARUSER, SAXIACPARVALID, SAXIACPAWADDR,
                     SAXIACPAWBURST, SAXIACPAWCACHE, SAXIACPAWID,
                     SAXIACPAWLEN, SAXIACPAWLOCK, SAXIACPAWPROT, SAXIACPAWQOS,
                     SAXIACPAWSIZE, SAXIACPAWUSER, SAXIACPAWVALID,
                     SAXIACPBREADY, SAXIACPRREADY, SAXIACPWDATA, SAXIACPWID,
                     SAXIACPWLAST, SAXIACPWSTRB, SAXIACPWVALID, SAXIGP0ACLK,
                     SAXIGP0ARADDR, SAXIGP0ARBURST, SAXIGP0ARCACHE,
                     SAXIGP0ARID, SAXIGP0ARLEN, SAXIGP0ARLOCK, SAXIGP0ARPROT,
                     SAXIGP0ARQOS, SAXIGP0ARSIZE, SAXIGP0ARVALID,
                     SAXIGP0AWADDR, SAXIGP0AWBURST, SAXIGP0AWCACHE,
                     SAXIGP0AWID, SAXIGP0AWLEN, SAXIGP0AWLOCK, SAXIGP0AWPROT,
                     SAXIGP0AWQOS, SAXIGP0AWSIZE, SAXIGP0AWVALID,
                     SAXIGP0BREADY, SAXIGP0RREADY, SAXIGP0WDATA, SAXIGP0WID,
                     SAXIGP0WLAST, SAXIGP0WSTRB, SAXIGP0WVALID, SAXIGP1ACLK,
                     SAXIGP1ARADDR, SAXIGP1ARBURST, SAXIGP1ARCACHE,
                     SAXIGP1ARID, SAXIGP1ARLEN, SAXIGP1ARLOCK, SAXIGP1ARPROT,
                     SAXIGP1ARQOS, SAXIGP1ARSIZE, SAXIGP1ARVALID,
                     SAXIGP1AWADDR, SAXIGP1AWBURST, SAXIGP1AWCACHE,
                     SAXIGP1AWID, SAXIGP1AWLEN, SAXIGP1AWLOCK, SAXIGP1AWPROT,
                     SAXIGP1AWQOS, SAXIGP1AWSIZE, SAXIGP1AWVALID,
                     SAXIGP1BREADY, SAXIGP1RREADY, SAXIGP1WDATA, SAXIGP1WID,
                     SAXIGP1WLAST, SAXIGP1WSTRB, SAXIGP1WVALID, SAXIHP0ACLK,
                     SAXIHP0ARADDR, SAXIHP0ARBURST, SAXIHP0ARCACHE,
                     SAXIHP0ARID, SAXIHP0ARLEN, SAXIHP0ARLOCK, SAXIHP0ARPROT,
                     SAXIHP0ARQOS, SAXIHP0ARSIZE, SAXIHP0ARVALID,
                     SAXIHP0AWADDR, SAXIHP0AWBURST, SAXIHP0AWCACHE,
                     SAXIHP0AWID, SAXIHP0AWLEN, SAXIHP0AWLOCK, SAXIHP0AWPROT,
                     SAXIHP0AWQOS, SAXIHP0AWSIZE, SAXIHP0AWVALID,
                     SAXIHP0BREADY, SAXIHP0RDISSUECAP1EN, SAXIHP0RREADY,
                     SAXIHP0WDATA, SAXIHP0WID, SAXIHP0WLAST,
                     SAXIHP0WRISSUECAP1EN, SAXIHP0WSTRB, SAXIHP0WVALID,
                     SAXIHP1ACLK, SAXIHP1ARADDR, SAXIHP1ARBURST,
                     SAXIHP1ARCACHE, SAXIHP1ARID, SAXIHP1ARLEN, SAXIHP1ARLOCK,
                     SAXIHP1ARPROT, SAXIHP1ARQOS, SAXIHP1ARSIZE,
                     SAXIHP1ARVALID, SAXIHP1AWADDR, SAXIHP1AWBURST,
                     SAXIHP1AWCACHE, SAXIHP1AWID, SAXIHP1AWLEN, SAXIHP1AWLOCK,
                     SAXIHP1AWPROT, SAXIHP1AWQOS, SAXIHP1AWSIZE,
                     SAXIHP1AWVALID, SAXIHP1BREADY, SAXIHP1RDISSUECAP1EN,
                     SAXIHP1RREADY, SAXIHP1WDATA, SAXIHP1WID, SAXIHP1WLAST,
                     SAXIHP1WRISSUECAP1EN, SAXIHP1WSTRB, SAXIHP1WVALID,
                     SAXIHP2ACLK, SAXIHP2ARADDR, SAXIHP2ARBURST,
                     SAXIHP2ARCACHE, SAXIHP2ARID, SAXIHP2ARLEN, SAXIHP2ARLOCK,
                     SAXIHP2ARPROT, SAXIHP2ARQOS, SAXIHP2ARSIZE,
                     SAXIHP2ARVALID, SAXIHP2AWADDR, SAXIHP2AWBURST,
                     SAXIHP2AWCACHE, SAXIHP2AWID, SAXIHP2AWLEN, SAXIHP2AWLOCK,
                     SAXIHP2AWPROT, SAXIHP2AWQOS, SAXIHP2AWSIZE,
                     SAXIHP2AWVALID, SAXIHP2BREADY, SAXIHP2RDISSUECAP1EN,
                     SAXIHP2RREADY, SAXIHP2WDATA, SAXIHP2WID, SAXIHP2WLAST,
                     SAXIHP2WRISSUECAP1EN, SAXIHP2WSTRB, SAXIHP2WVALID,
                     SAXIHP3ACLK, SAXIHP3ARADDR, SAXIHP3ARBURST,
                     SAXIHP3ARCACHE, SAXIHP3ARID, SAXIHP3ARLEN, SAXIHP3ARLOCK,
                     SAXIHP3ARPROT, SAXIHP3ARQOS, SAXIHP3ARSIZE,
                     SAXIHP3ARVALID, SAXIHP3AWADDR, SAXIHP3AWBURST,
                     SAXIHP3AWCACHE, SAXIHP3AWID, SAXIHP3AWLEN, SAXIHP3AWLOCK,
                     SAXIHP3AWPROT, SAXIHP3AWQOS, SAXIHP3AWSIZE,
                     SAXIHP3AWVALID, SAXIHP3BREADY, SAXIHP3RDISSUECAP1EN,
                     SAXIHP3RREADY, SAXIHP3WDATA, SAXIHP3WID, SAXIHP3WLAST,
                     SAXIHP3WRISSUECAP1EN, SAXIHP3WSTRB, SAXIHP3WVALID};
  /* verilator lint_on UNUSEDSIGNAL */

endmodule

/* verilator lint_on DECLFILENAME */

`default_nettype wire
