// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The Altera IP cores the DE25-Nano's top level instantiates, as shells, so
// that `boards/de25-nano/cadr_de25.sv` can be elaborated and linted.
//
//   `cadr_de25_pll`   the I/O PLL that `boards/de25-nano/quartus/build.sh`
//                     generates from Altera's IP at every build.  The port
//                     list is the one the generator writes for the parameters
//                     that flow gives it: one reference clock, one reset, one
//                     output clock and the lock.
//   `cadr_de25_pixel_pll`
//                     the second I/O PLL, generated by the same flow when the
//                     display output is asked for: the mode's pixel clock off
//                     the same 50 MHz reference.  Its port list is the first
//                     PLL's, because the flow asks the same generator for the
//                     same shape at another frequency.
//   `cadr_de25_reset_release`
//                     the Reset Release, generated by the same flow from
//                     Altera's IP of that name, whose one port is
//                     `nINIT_DONE`.
//   `cadr_de25_vjtag` the Virtual JTAG IP, generated by the same flow when
//                     the probe is asked for.  The port list is the one the
//                     generator writes for a one-bit virtual instruction:
//                     the node's TDI, TDO, TCK, its instruction in and out,
//                     and its eight virtual states.
//
// **NOTHING HERE MODELS ANYTHING, AND THIS FILE MUST NEVER MOVE TO `rtl/`.**
// The PLL below multiplies nothing, so a model built on it would run the
// machine at the board's 50 MHz, a different machine that still lights LEDs.
// `build/de25.pass` is the only rule that reads this file, and it only lints.
// Both Vivado flows read `[glob rtl/*/*.sv rtl/*/*/*.sv]`, and nothing globs
// `tb/`, which is the reason `tb/cadr_arty_stubs.sv` lives here too.

`default_nettype none

/* verilator lint_off DECLFILENAME */

module cadr_de25_pll (
    input  var logic refclk,
    input  var logic rst,
    output var logic outclk_0,
    output var logic locked
);
  // Not a multiplier: see the header.
  assign outclk_0 = refclk;
  assign locked   = !rst;
endmodule

module cadr_de25_pixel_pll (
    input  var logic refclk,
    input  var logic rst,
    output var logic outclk_0,
    output var logic locked
);
  // Not a multiplier either: see the header.  A model built on this would
  // draw its raster at the board's 50 MHz, which is a different mode.
  assign outclk_0 = refclk;
  assign locked   = !rst;
endmodule

module cadr_de25_reset_release (
    output var logic ninit_done
);
  // A device that finished initializing long ago.
  assign ninit_done = 1'b0;
endmodule

module cadr_de25_vjtag (
    output var logic tck,
    output var logic tdi,
    input  var logic tdo,
    output var logic ir_in,
    input  var logic ir_out,
    output var logic virtual_state_cdr,
    output var logic virtual_state_sdr,
    output var logic virtual_state_e1dr,
    output var logic virtual_state_pdr,
    output var logic virtual_state_e2dr,
    output var logic virtual_state_udr,
    output var logic virtual_state_cir,
    output var logic virtual_state_uir
);
  // No hub and no cable: every state low and nothing selected.  What a node
  // does with a real hub is `tb/cadr_probe_tb.cpp`'s question.
  assign tck = 1'b0;
  assign tdi = 1'b0;
  assign ir_in = 1'b0;
  assign {virtual_state_cdr, virtual_state_sdr, virtual_state_e1dr,
          virtual_state_pdr, virtual_state_e2dr, virtual_state_udr,
          virtual_state_cir, virtual_state_uir} = '0;
  /* verilator lint_off UNUSEDSIGNAL */
  logic unused;
  assign unused = &{1'b0, tdo, ir_out};
  /* verilator lint_on UNUSEDSIGNAL */
endmodule

// `tb/cadr_board_reset_tb.cpp` builds the top level with a processor that
// drives its bridges, `tb/cadr_de25_hps_sim.sv`, and defines
// `CADR_DE25_HPS_SIM` to leave this one out.
`ifndef CADR_DE25_HPS_SIM
// `cadr_de25_hps`   the processor system that `boards/de25-nano/quartus/hps.tcl`
//                   describes and `build.sh` generates for the memory board:
//                   the Agilex 5 processor, its LPDDR4 controller, and the
//                   three bridges.  The port list is the one Platform
//                   Designer writes for that script, measured.  Every output
//                   is zero and every inout undriven: a processor out of
//                   reset whose software never opened anything, so the
//                   memory port's gate stays shut.  Lint is all it is for.
module cadr_de25_hps (
    output var logic [0:0] emif_mem_0_mem_cs,
    output var logic [5:0] emif_mem_0_mem_ca,
    output var logic [0:0] emif_mem_0_mem_cke,
    inout  wire  logic [31:0] emif_mem_0_mem_dq,
    inout  wire  logic [3:0] emif_mem_0_mem_dqs_t,
    inout  wire  logic [3:0] emif_mem_0_mem_dqs_c,
    inout  wire  logic [3:0] emif_mem_0_mem_dmi,
    output var logic [0:0] emif_mem_ck_0_mem_ck_t,
    output var logic [0:0] emif_mem_ck_0_mem_ck_c,
    output var logic emif_mem_reset_n_mem_reset_n,
    input  var logic emif_oct_0_oct_rzqin,
    input  var logic emif_ref_clk_clk,
    output var logic hps_h2f_reset_reset,
    input  var logic [31:0] hps_hps_gp_gp_in,
    output var logic [31:0] hps_hps_gp_gp_out,
    input  var logic hps_hps2fpga_axi_clock_clk,
    input  var logic hps_hps2fpga_axi_reset_reset,
    output var logic [3:0] hps_hps2fpga_awid,
    output var logic [29:0] hps_hps2fpga_awaddr,
    output var logic [7:0] hps_hps2fpga_awlen,
    output var logic [2:0] hps_hps2fpga_awsize,
    output var logic [1:0] hps_hps2fpga_awburst,
    output var logic hps_hps2fpga_awlock,
    output var logic [3:0] hps_hps2fpga_awcache,
    output var logic [2:0] hps_hps2fpga_awprot,
    output var logic hps_hps2fpga_awvalid,
    input  var logic hps_hps2fpga_awready,
    output var logic [31:0] hps_hps2fpga_wdata,
    output var logic [3:0] hps_hps2fpga_wstrb,
    output var logic hps_hps2fpga_wlast,
    output var logic hps_hps2fpga_wvalid,
    input  var logic hps_hps2fpga_wready,
    input  var logic [3:0] hps_hps2fpga_bid,
    input  var logic [1:0] hps_hps2fpga_bresp,
    input  var logic hps_hps2fpga_bvalid,
    output var logic hps_hps2fpga_bready,
    output var logic [3:0] hps_hps2fpga_arid,
    output var logic [29:0] hps_hps2fpga_araddr,
    output var logic [7:0] hps_hps2fpga_arlen,
    output var logic [2:0] hps_hps2fpga_arsize,
    output var logic [1:0] hps_hps2fpga_arburst,
    output var logic hps_hps2fpga_arlock,
    output var logic [3:0] hps_hps2fpga_arcache,
    output var logic [2:0] hps_hps2fpga_arprot,
    output var logic hps_hps2fpga_arvalid,
    input  var logic hps_hps2fpga_arready,
    input  var logic [3:0] hps_hps2fpga_rid,
    input  var logic [31:0] hps_hps2fpga_rdata,
    input  var logic [1:0] hps_hps2fpga_rresp,
    input  var logic hps_hps2fpga_rlast,
    input  var logic hps_hps2fpga_rvalid,
    output var logic hps_hps2fpga_rready,
    input  var logic hps_lwhps2fpga_axi_clock_clk,
    input  var logic hps_lwhps2fpga_axi_reset_reset,
    output var logic [3:0] hps_lwhps2fpga_awid,
    output var logic [28:0] hps_lwhps2fpga_awaddr,
    output var logic [7:0] hps_lwhps2fpga_awlen,
    output var logic [2:0] hps_lwhps2fpga_awsize,
    output var logic [1:0] hps_lwhps2fpga_awburst,
    output var logic hps_lwhps2fpga_awlock,
    output var logic [3:0] hps_lwhps2fpga_awcache,
    output var logic [2:0] hps_lwhps2fpga_awprot,
    output var logic hps_lwhps2fpga_awvalid,
    input  var logic hps_lwhps2fpga_awready,
    output var logic [31:0] hps_lwhps2fpga_wdata,
    output var logic [3:0] hps_lwhps2fpga_wstrb,
    output var logic hps_lwhps2fpga_wlast,
    output var logic hps_lwhps2fpga_wvalid,
    input  var logic hps_lwhps2fpga_wready,
    input  var logic [3:0] hps_lwhps2fpga_bid,
    input  var logic [1:0] hps_lwhps2fpga_bresp,
    input  var logic hps_lwhps2fpga_bvalid,
    output var logic hps_lwhps2fpga_bready,
    output var logic [3:0] hps_lwhps2fpga_arid,
    output var logic [28:0] hps_lwhps2fpga_araddr,
    output var logic [7:0] hps_lwhps2fpga_arlen,
    output var logic [2:0] hps_lwhps2fpga_arsize,
    output var logic [1:0] hps_lwhps2fpga_arburst,
    output var logic hps_lwhps2fpga_arlock,
    output var logic [3:0] hps_lwhps2fpga_arcache,
    output var logic [2:0] hps_lwhps2fpga_arprot,
    output var logic hps_lwhps2fpga_arvalid,
    input  var logic hps_lwhps2fpga_arready,
    input  var logic [3:0] hps_lwhps2fpga_rid,
    input  var logic [31:0] hps_lwhps2fpga_rdata,
    input  var logic [1:0] hps_lwhps2fpga_rresp,
    input  var logic hps_lwhps2fpga_rlast,
    input  var logic hps_lwhps2fpga_rvalid,
    output var logic hps_lwhps2fpga_rready,
    output var logic hps_h2f_warm_reset_handshake_reset_req,
    input  var logic hps_h2f_warm_reset_handshake_reset_ack,
    input  var logic hps_hps_io_hps_osc_clk,
    inout  wire  logic hps_hps_io_sdmmc_data0,
    inout  wire  logic hps_hps_io_sdmmc_data1,
    output var logic hps_hps_io_sdmmc_cclk,
    inout  wire  logic hps_hps_io_sdmmc_data2,
    inout  wire  logic hps_hps_io_sdmmc_data3,
    inout  wire  logic hps_hps_io_sdmmc_cmd,
    input  var logic hps_hps_io_usb0_clk,
    output var logic hps_hps_io_usb0_stp,
    input  var logic hps_hps_io_usb0_dir,
    inout  wire  logic hps_hps_io_usb0_data0,
    inout  wire  logic hps_hps_io_usb0_data1,
    input  var logic hps_hps_io_usb0_nxt,
    inout  wire  logic hps_hps_io_usb0_data2,
    inout  wire  logic hps_hps_io_usb0_data3,
    inout  wire  logic hps_hps_io_usb0_data4,
    inout  wire  logic hps_hps_io_usb0_data5,
    inout  wire  logic hps_hps_io_usb0_data6,
    inout  wire  logic hps_hps_io_usb0_data7,
    output var logic hps_hps_io_emac0_tx_clk,
    output var logic hps_hps_io_emac0_tx_ctl,
    input  var logic hps_hps_io_emac0_rx_clk,
    input  var logic hps_hps_io_emac0_rx_ctl,
    output var logic hps_hps_io_emac0_txd0,
    output var logic hps_hps_io_emac0_txd1,
    input  var logic hps_hps_io_emac0_rxd0,
    input  var logic hps_hps_io_emac0_rxd1,
    output var logic hps_hps_io_emac0_txd2,
    output var logic hps_hps_io_emac0_txd3,
    input  var logic hps_hps_io_emac0_rxd2,
    input  var logic hps_hps_io_emac0_rxd3,
    inout  wire  logic hps_hps_io_mdio0_mdio,
    output var logic hps_hps_io_mdio0_mdc,
    output var logic hps_hps_io_uart1_tx,
    input  var logic hps_hps_io_uart1_rx,
    inout  wire  logic hps_hps_io_i2c1_sda,
    inout  wire  logic hps_hps_io_i2c1_scl,
    inout  wire  logic hps_hps_io_gpio28,
    inout  wire  logic hps_hps_io_gpio40,
    inout  wire  logic hps_hps_io_gpio41,
    input  var logic hps_f2sdram_axi_clock_clk,
    input  var logic hps_f2sdram_axi_reset_reset,
    input  var logic [31:0] hps_f2sdram_araddr,
    input  var logic [1:0] hps_f2sdram_arburst,
    input  var logic [3:0] hps_f2sdram_arcache,
    input  var logic [4:0] hps_f2sdram_arid,
    input  var logic [7:0] hps_f2sdram_arlen,
    input  var logic hps_f2sdram_arlock,
    input  var logic [2:0] hps_f2sdram_arprot,
    input  var logic [3:0] hps_f2sdram_arqos,
    output var logic hps_f2sdram_arready,
    input  var logic [2:0] hps_f2sdram_arsize,
    input  var logic hps_f2sdram_arvalid,
    input  var logic [31:0] hps_f2sdram_awaddr,
    input  var logic [1:0] hps_f2sdram_awburst,
    input  var logic [3:0] hps_f2sdram_awcache,
    input  var logic [4:0] hps_f2sdram_awid,
    input  var logic [7:0] hps_f2sdram_awlen,
    input  var logic hps_f2sdram_awlock,
    input  var logic [2:0] hps_f2sdram_awprot,
    input  var logic [3:0] hps_f2sdram_awqos,
    output var logic hps_f2sdram_awready,
    input  var logic [2:0] hps_f2sdram_awsize,
    input  var logic hps_f2sdram_awvalid,
    output var logic [4:0] hps_f2sdram_bid,
    input  var logic hps_f2sdram_bready,
    output var logic [1:0] hps_f2sdram_bresp,
    output var logic hps_f2sdram_bvalid,
    output var logic [63:0] hps_f2sdram_rdata,
    output var logic [4:0] hps_f2sdram_rid,
    output var logic hps_f2sdram_rlast,
    input  var logic hps_f2sdram_rready,
    output var logic [1:0] hps_f2sdram_rresp,
    output var logic hps_f2sdram_rvalid,
    input  var logic [63:0] hps_f2sdram_wdata,
    input  var logic hps_f2sdram_wlast,
    output var logic hps_f2sdram_wready,
    input  var logic [7:0] hps_f2sdram_wstrb,
    input  var logic hps_f2sdram_wvalid,
    input  var logic [7:0] hps_f2sdram_aruser,
    input  var logic [7:0] hps_f2sdram_awuser,
    input  var logic [7:0] hps_f2sdram_wuser,
    output var logic [7:0] hps_f2sdram_buser,
    input  var logic [3:0] hps_f2sdram_arregion,
    output var logic [7:0] hps_f2sdram_ruser,
    input  var logic [3:0] hps_f2sdram_awregion
);
  assign {emif_mem_0_mem_cs,
          emif_mem_0_mem_ca,
          emif_mem_0_mem_cke,
          emif_mem_ck_0_mem_ck_t,
          emif_mem_ck_0_mem_ck_c,
          emif_mem_reset_n_mem_reset_n,
          hps_h2f_reset_reset,
          hps_hps_gp_gp_out,
          hps_hps2fpga_awid,
          hps_hps2fpga_awaddr,
          hps_hps2fpga_awlen,
          hps_hps2fpga_awsize,
          hps_hps2fpga_awburst,
          hps_hps2fpga_awlock,
          hps_hps2fpga_awcache,
          hps_hps2fpga_awprot,
          hps_hps2fpga_awvalid,
          hps_hps2fpga_wdata,
          hps_hps2fpga_wstrb,
          hps_hps2fpga_wlast,
          hps_hps2fpga_wvalid,
          hps_hps2fpga_bready,
          hps_hps2fpga_arid,
          hps_hps2fpga_araddr,
          hps_hps2fpga_arlen,
          hps_hps2fpga_arsize,
          hps_hps2fpga_arburst,
          hps_hps2fpga_arlock,
          hps_hps2fpga_arcache,
          hps_hps2fpga_arprot,
          hps_hps2fpga_arvalid,
          hps_hps2fpga_rready,
          hps_lwhps2fpga_awid,
          hps_lwhps2fpga_awaddr,
          hps_lwhps2fpga_awlen,
          hps_lwhps2fpga_awsize,
          hps_lwhps2fpga_awburst,
          hps_lwhps2fpga_awlock,
          hps_lwhps2fpga_awcache,
          hps_lwhps2fpga_awprot,
          hps_lwhps2fpga_awvalid,
          hps_lwhps2fpga_wdata,
          hps_lwhps2fpga_wstrb,
          hps_lwhps2fpga_wlast,
          hps_lwhps2fpga_wvalid,
          hps_lwhps2fpga_bready,
          hps_lwhps2fpga_arid,
          hps_lwhps2fpga_araddr,
          hps_lwhps2fpga_arlen,
          hps_lwhps2fpga_arsize,
          hps_lwhps2fpga_arburst,
          hps_lwhps2fpga_arlock,
          hps_lwhps2fpga_arcache,
          hps_lwhps2fpga_arprot,
          hps_lwhps2fpga_arvalid,
          hps_lwhps2fpga_rready,
          hps_h2f_warm_reset_handshake_reset_req,
          hps_hps_io_sdmmc_cclk,
          hps_hps_io_usb0_stp,
          hps_hps_io_emac0_tx_clk,
          hps_hps_io_emac0_tx_ctl,
          hps_hps_io_emac0_txd0,
          hps_hps_io_emac0_txd1,
          hps_hps_io_emac0_txd2,
          hps_hps_io_emac0_txd3,
          hps_hps_io_mdio0_mdc,
          hps_hps_io_uart1_tx,
          hps_f2sdram_arready,
          hps_f2sdram_awready,
          hps_f2sdram_bid,
          hps_f2sdram_bresp,
          hps_f2sdram_bvalid,
          hps_f2sdram_rdata,
          hps_f2sdram_rid,
          hps_f2sdram_rlast,
          hps_f2sdram_rresp,
          hps_f2sdram_rvalid,
          hps_f2sdram_wready,
          hps_f2sdram_buser,
          hps_f2sdram_ruser} = '0;
  /* verilator lint_off UNUSEDSIGNAL */
  logic unused;
  assign unused = ^{emif_oct_0_oct_rzqin,
                    emif_ref_clk_clk,
                    hps_hps_gp_gp_in,
                    hps_hps2fpga_axi_clock_clk,
                    hps_hps2fpga_axi_reset_reset,
                    hps_hps2fpga_awready,
                    hps_hps2fpga_wready,
                    hps_hps2fpga_bid,
                    hps_hps2fpga_bresp,
                    hps_hps2fpga_bvalid,
                    hps_hps2fpga_arready,
                    hps_hps2fpga_rid,
                    hps_hps2fpga_rdata,
                    hps_hps2fpga_rresp,
                    hps_hps2fpga_rlast,
                    hps_hps2fpga_rvalid,
                    hps_lwhps2fpga_axi_clock_clk,
                    hps_lwhps2fpga_axi_reset_reset,
                    hps_lwhps2fpga_awready,
                    hps_lwhps2fpga_wready,
                    hps_lwhps2fpga_bid,
                    hps_lwhps2fpga_bresp,
                    hps_lwhps2fpga_bvalid,
                    hps_lwhps2fpga_arready,
                    hps_lwhps2fpga_rid,
                    hps_lwhps2fpga_rdata,
                    hps_lwhps2fpga_rresp,
                    hps_lwhps2fpga_rlast,
                    hps_lwhps2fpga_rvalid,
                    hps_h2f_warm_reset_handshake_reset_ack,
                    hps_hps_io_hps_osc_clk,
                    hps_hps_io_usb0_clk,
                    hps_hps_io_usb0_dir,
                    hps_hps_io_usb0_nxt,
                    hps_hps_io_emac0_rx_clk,
                    hps_hps_io_emac0_rx_ctl,
                    hps_hps_io_emac0_rxd0,
                    hps_hps_io_emac0_rxd1,
                    hps_hps_io_emac0_rxd2,
                    hps_hps_io_emac0_rxd3,
                    hps_hps_io_uart1_rx,
                    hps_f2sdram_axi_clock_clk,
                    hps_f2sdram_axi_reset_reset,
                    hps_f2sdram_araddr,
                    hps_f2sdram_arburst,
                    hps_f2sdram_arcache,
                    hps_f2sdram_arid,
                    hps_f2sdram_arlen,
                    hps_f2sdram_arlock,
                    hps_f2sdram_arprot,
                    hps_f2sdram_arqos,
                    hps_f2sdram_arsize,
                    hps_f2sdram_arvalid,
                    hps_f2sdram_awaddr,
                    hps_f2sdram_awburst,
                    hps_f2sdram_awcache,
                    hps_f2sdram_awid,
                    hps_f2sdram_awlen,
                    hps_f2sdram_awlock,
                    hps_f2sdram_awprot,
                    hps_f2sdram_awqos,
                    hps_f2sdram_awsize,
                    hps_f2sdram_awvalid,
                    hps_f2sdram_bready,
                    hps_f2sdram_rready,
                    hps_f2sdram_wdata,
                    hps_f2sdram_wlast,
                    hps_f2sdram_wstrb,
                    hps_f2sdram_wvalid,
                    hps_f2sdram_aruser,
                    hps_f2sdram_awuser,
                    hps_f2sdram_wuser,
                    hps_f2sdram_arregion,
                    hps_f2sdram_awregion};
  /* verilator lint_on UNUSEDSIGNAL */
endmodule
`endif

/* verilator lint_on DECLFILENAME */

`default_nettype wire
