// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by golden/src/cables.rs.  Do not edit; run `make cables`.
//
// Nothing but cadr_cables.svh, so that lint reads the port list.

`default_nettype none

/* verilator lint_off UNUSEDSIGNAL */
module cadr_cables_lint (
    input  var logic clk,
    input  var logic rst,
`include "cadr_cables.svh"
);
  assign MEM31_o = 1'b0;
  assign MEM31_oe = 1'b0;
  assign MEM30_o = 1'b0;
  assign MEM30_oe = 1'b0;
  assign MEM29_o = 1'b0;
  assign MEM29_oe = 1'b0;
  assign MEM28_o = 1'b0;
  assign MEM28_oe = 1'b0;
  assign MEM27_o = 1'b0;
  assign MEM27_oe = 1'b0;
  assign MEM26_o = 1'b0;
  assign MEM26_oe = 1'b0;
  assign MEM25_o = 1'b0;
  assign MEM25_oe = 1'b0;
  assign MEM24_o = 1'b0;
  assign MEM24_oe = 1'b0;
  assign MEM23_o = 1'b0;
  assign MEM23_oe = 1'b0;
  assign MEM22_o = 1'b0;
  assign MEM22_oe = 1'b0;
  assign MEM21_o = 1'b0;
  assign MEM21_oe = 1'b0;
  assign MEM20_o = 1'b0;
  assign MEM20_oe = 1'b0;
  assign MEM19_o = 1'b0;
  assign MEM19_oe = 1'b0;
  assign MEM18_o = 1'b0;
  assign MEM18_oe = 1'b0;
  assign MEM17_o = 1'b0;
  assign MEM17_oe = 1'b0;
  assign MEM16_o = 1'b0;
  assign MEM16_oe = 1'b0;
  assign MEM15_o = 1'b0;
  assign MEM15_oe = 1'b0;
  assign MEM14_o = 1'b0;
  assign MEM14_oe = 1'b0;
  assign MEM13_o = 1'b0;
  assign MEM13_oe = 1'b0;
  assign MEM12_o = 1'b0;
  assign MEM12_oe = 1'b0;
  assign MEM11_o = 1'b0;
  assign MEM11_oe = 1'b0;
  assign MEM10_o = 1'b0;
  assign MEM10_oe = 1'b0;
  assign MEM9_o = 1'b0;
  assign MEM9_oe = 1'b0;
  assign MEM8_o = 1'b0;
  assign MEM8_oe = 1'b0;
  assign MEM7_o = 1'b0;
  assign MEM7_oe = 1'b0;
  assign MEM6_o = 1'b0;
  assign MEM6_oe = 1'b0;
  assign MEM5_o = 1'b0;
  assign MEM5_oe = 1'b0;
  assign MEM4_o = 1'b0;
  assign MEM4_oe = 1'b0;
  assign MEM3_o = 1'b0;
  assign MEM3_oe = 1'b0;
  assign MEM2_o = 1'b0;
  assign MEM2_oe = 1'b0;
  assign MEM1_o = 1'b0;
  assign MEM1_oe = 1'b0;
  assign MEM0_o = 1'b0;
  assign MEM0_oe = 1'b0;
  assign n_ADRPAR = 1'b0;
  assign n_PMA21 = 1'b0;
  assign n_PMA20 = 1'b0;
  assign n_PMA19 = 1'b0;
  assign n_PMA18 = 1'b0;
  assign n_PMA17 = 1'b0;
  assign n_PMA16 = 1'b0;
  assign n_PMA15 = 1'b0;
  assign n_PMA14 = 1'b0;
  assign n_PMA13 = 1'b0;
  assign n_PMA12 = 1'b0;
  assign n_PMA11 = 1'b0;
  assign n_PMA10 = 1'b0;
  assign n_PMA9 = 1'b0;
  assign n_PMA8 = 1'b0;
  assign n_VMA7 = 1'b0;
  assign n_VMA6 = 1'b0;
  assign n_VMA5 = 1'b0;
  assign n_VMA4 = 1'b0;
  assign n_VMA3 = 1'b0;
  assign n_VMA2 = 1'b0;
  assign n_VMA1 = 1'b0;
  assign n_VMA0 = 1'b0;
  assign n_MEMRQ = 1'b0;
  assign SPY0_o = 1'b0;
  assign SPY0_oe = 1'b0;
  assign SPY1_o = 1'b0;
  assign SPY1_oe = 1'b0;
  assign SPY2_o = 1'b0;
  assign SPY2_oe = 1'b0;
  assign SPY3_o = 1'b0;
  assign SPY3_oe = 1'b0;
  assign SPY4_o = 1'b0;
  assign SPY4_oe = 1'b0;
  assign SPY5_o = 1'b0;
  assign SPY5_oe = 1'b0;
  assign SPY6_o = 1'b0;
  assign SPY6_oe = 1'b0;
  assign SPY7_o = 1'b0;
  assign SPY7_oe = 1'b0;
  assign SPY8_o = 1'b0;
  assign SPY8_oe = 1'b0;
  assign SPY9_o = 1'b0;
  assign SPY9_oe = 1'b0;
  assign SPY10_o = 1'b0;
  assign SPY10_oe = 1'b0;
  assign SPY11_o = 1'b0;
  assign SPY11_oe = 1'b0;
  assign SPY12_o = 1'b0;
  assign SPY12_oe = 1'b0;
  assign SPY13_o = 1'b0;
  assign SPY13_oe = 1'b0;
  assign SPY14_o = 1'b0;
  assign SPY14_oe = 1'b0;
  assign SPY15_o = 1'b0;
  assign SPY15_oe = 1'b0;
  assign WRCYC = 1'b0;
  assign MEMPAR_OUT = 1'b0;
  assign MCLK7 = 1'b0;
  assign n_BUS_RESET = 1'b0;
  assign n_BUS_POWER_RESET = 1'b0;
endmodule
/* verilator lint_on UNUSEDSIGNAL */

`default_nettype wire
