// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! The reference trace for `rtl/cadr_busint_xbus.sv`: the processor's Xbus
//! memory cycle, out of muir's own `busint::Busint`.
//!
//! The cycle, from `cadr1/xspec.text.3` by way of `busint.rs`:
//!
//! 1. the cpu drops `-MEMRQ` with `WRCYC` and the address already up;
//! 2. "the bus interface only looks at it towards the end of the cycle" ---
//!    the priority logic samples `-MEMRQ` at the master clock edge, which is
//!    the microcycle boundary, and grants: `-MEMGRANT` goes low;
//! 3. `-XBUS.RQ` follows `SETUP_NS` --- 80 ns --- after the grant, and the
//!    slave gives or takes the word when it answers;
//! 4. a write is acknowledged at once, a read `XBUS_ACK_NS` --- 60 ns ---
//!    later, which is the 60 ns tap of the TD100 at REQLM 0C09 deskewing the
//!    word into `MD`;
//! 5. `-MEMACK` stays low until the cpu lifts `-MEMRQ`, which it does
//!    `MFINISHD_NS` --- 30 ns --- after the acknowledgement.
//!
//! The responder here is `Responder::Device` and not `Responder::Memory`.
//! That is the target's shape and not a simplification: `MemoryBoard` models
//! a board of 4116s refreshing itself, and on the Arty Z7 main memory is PS
//! DDR3 behind an Xbus bridge, which answers in its own time and refreshes on
//! its own account. A device that answers `device_ns` after `-XBUS.RQ` is
//! exactly what the bridge is.
//!
//! The NXM timeout is not exercised here; it is its own slice.

use muir::busint::{self, Busint, Responder};

/// Five nanoseconds, as in the phase generator: one master-clock tick.
const TICK_NS: u64 = 5;

/// A microcycle at normal speed with no ILONG, which is when `mclk_edge`
/// falls --- `rtl.rs` calls it once a microcycle, at the boundary, because
/// "the bus interface only looks at it towards the end of the cycle".
const MICROCYCLE_TICKS: u64 = 29;

const TICKS: u64 = 6_000;

/// How long the device takes to answer, from `-XBUS.RQ`. Varied so the
/// trace covers a device faster than the setup, one slower than a
/// microcycle, and the ordinary case.
fn device_ns(cycle: u64) -> u64 {
    match cycle % 6 {
        0 => 0,   // answers the instant -XBUS.RQ goes out
        1 => 25,
        2 => 60,
        3 => 115, // longer than the 80 ns of setup
        4 => 200, // longer than a microcycle: the machine hangs over an edge
        _ => 355,
    }
}

/// Read or write, which decides whether the acknowledgement is deskewed.
fn writing(cycle: u64) -> bool {
    cycle % 3 == 2
}

/// When the cpu asks for its next cycle, in ticks after the last one ended.
///
/// Never zero: `-MEMRQ` has to rise between cycles or the interface never
/// sees the first one end, and on the board it does --- `MEMRQ` off the 9S42
/// at VCTL1 1E25 is `MEMSTART AND VMAOK OR MBUSY`, and `MBUSY` clears
/// `MFINISHD_NS` after the acknowledgement, before any new `MEMSTART`. The
/// gaps then put the next request at every offset against the master clock
/// edge, which is the only place the priority logic looks at it.
fn gap_ticks(cycle: u64) -> u64 {
    [1, 2, 3, 7, 13, 29, 31][(cycle % 7) as usize]
}

fn main() {
    // One board is enough: nothing here addresses memory boards.
    let mut bi = Busint::new(1);
    let responder = Responder::Device;

    let mut cycle: u64 = 0;
    let mut next_request_at: u64 = 10 * TICK_NS;
    let mut memrq = false;
    let mut wrcyc = false;
    let mut release_at: Option<u64> = None;

    println!("# tick n_memrq wrcyc device_ns mclk | n_memgrant n_memack n_loadmd");
    println!("# generated by golden/src/busint_xbus.rs from muir's busint::Busint");

    for tick in 0..TICKS {
        let now = tick * TICK_NS;
        let mclk = tick % MICROCYCLE_TICKS == 0;

        // The cpu lifts -MEMRQ MFINISHD_NS after the acknowledgement, and
        // the interface lifts -XBUS RQ with it. `rtl.rs` does exactly this.
        if let Some(at) = release_at
            && now >= at
        {
            bi.released(at);
            bi.finish();
            release_at = None;
            memrq = false;
            next_request_at = now + gap_ticks(cycle) * TICK_NS;
            cycle += 1;
        }

        // A new cycle. -MEMRQ is a level the cpu holds up until the ack.
        if !memrq && release_at.is_none() && now >= next_request_at {
            wrcyc = writing(cycle);
            bi.device_ns = device_ns(cycle);
            bi.request(wrcyc);
            memrq = true;
        }

        // The master clock edge: the priority logic samples -MEMRQ here.
        if mclk {
            bi.mclk_edge(now, responder);
        }

        // -MEMACK is asynchronous to the clock, so the cpu sees it whenever
        // it looks. Polling every tick is looking as often as it can.
        if let Some(ack) = bi.poll(now, responder)
            && release_at.is_none()
        {
            release_at = Some(ack.at + busint::MFINISHD_NS);
        }

        let granted = bi.granted();
        let acked = bi.ack_at().is_some_and(|at| now >= at);
        let loadmd = bi.loadmd_at().is_some_and(|at| now >= at);

        let b = |v: bool| u8::from(v);
        println!(
            "{tick} {} {} {} {} {} {} {}",
            b(!memrq), // -MEMRQ, active low
            b(wrcyc),
            bi.device_ns,
            b(mclk),
            b(!granted),  // -MEMGRANT
            b(!acked),    // -MEMACK
            b(!loadmd),   // -LOADMD
        );
    }

    eprintln!("busint_xbus: {cycle} cycles over {TICKS} ticks");
}
