// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! QUUX's `MUL` and `DIV` over many operands, out of muir's own
//! `muldiv::run`: the reference `tb/quux_muldiv_tb.cpp` holds
//! `rtl/machine/quux_muldiv.sv` to, row for row.
//!
//! One row an operand triple: `m a q` and what each operation leaves, the
//! output bus and `Q`, all hexadecimal.  The triples are every combination of
//! a set of edge values --- zero, one, the two extremes of each sign, a lone
//! high bit, alternating bits --- and then random words from a fixed
//! generator, so the file is the same every run.  muir computes each by
//! running the CADR's own steps (`ttl::alu_control` and `ttl::alu`), so this
//! holds the fabric's closed-form multiply and its 32-step divide to the step
//! sequence, not to a transcription of it.

use muir::muldiv::{Op, run};

const EDGES: [u32; 10] = [
    0, 1, 2, 0x7fff_ffff, 0x8000_0000, 0x8000_0001, 0xffff_ffff, 0xffff_fffe, 0x5555_5555, 0xaaaa_aaaa,
];

/// Random rows after the edges.
const RANDOM: usize = 20_000;

fn main() {
    println!("# m a q mul_ob mul_q div_ob div_q");
    println!("# generated by golden/src/muldiv.rs from muir's muldiv::run; hexadecimal");
    let mut rows = 0;
    let mut emit = |m: u32, a: u32, q: u32| {
        let (mo, mq) = run(Op::Mul, m, a, q);
        let (dob, dq) = run(Op::Div, m, a, q);
        println!("{m:x} {a:x} {q:x} {mo:x} {mq:x} {dob:x} {dq:x}");
        rows += 1;
    };
    for &m in &EDGES {
        for &a in &EDGES {
            for &q in &EDGES {
                emit(m, a, q);
            }
        }
    }
    // A 64-bit linear congruential generator, Knuth's MMIX constants.
    let mut x: u64 = 0x5155_0044_c0ff_ee00;
    let mut next = || {
        x = x.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
        (x >> 32) as u32
    };
    for _ in 0..RANDOM {
        let (m, a, q) = (next(), next(), next());
        emit(m, a, q);
    }
    eprintln!("muldiv: {rows} operand triples");
}
