// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! The reference trace for `rtl/machine/cadr_phase_gen.sv`, taken from muir's own
//! `clock::Behavioural` --- the model the `chip` engine runs.
//!
//! One line per five-nanosecond tick: the inputs the tick was driven with,
//! then the six signals the generator puts on the board.  The testbench reads
//! the same file, drives the DUT with the inputs and compares the outputs, so
//! the stimulus has exactly one definition and it is this one.
//!
//! The generator is driven the way `Chip::tick` drives it: ask what the board
//! looks like, take every event due, put the outputs back.  `pass` carries
//! time across a tick with no event in it, `held` when nothing is due because
//! `-HANG` or `RESET` is holding the generator rather than because the next
//! transition has not come round yet.

use muir::clock::{self, Behavioural, Clock, Inputs, Outputs, Speed};

/// Five nanoseconds, the master clock's period. Every instant the generator
/// names is a multiple of it.
const TICK_NS: u64 = 5;

/// How many ticks the trace runs for. At normal speed a microcycle is 29
/// ticks, so this is some hundreds of cycles.
const TICKS: u64 = 12_000;

/// The inputs at one tick.
#[derive(Clone, Copy)]
struct Drive {
    reset: bool,
    hang: bool,
    ilong: bool,
    speed: Speed,
}

/// A deterministic stimulus, so the trace is the same on every machine and
/// the file can be regenerated and diffed.
///
/// It is not random noise: each segment is meant to reach something. Reset
/// first, then each speed and each ILONG on its own, then `-HANG`, then
/// everything moving at once.
///
/// Reset is held only before the first cycle, but that does not avoid the
/// `-TPR60` artefact: `apply_clock` derives it from `phase_ns`, which is
/// `time - cycle_start`, and reset moves neither `cycle_start` nor the clock.
/// Time runs on, so even a reset held from power-on sweeps `phase_ns` through
/// 60..100 and emits a read tap --- here at ticks 11 to 18. The testbench
/// therefore does not compare `-TPR60` while `RESET` is high.
fn drive(tick: u64) -> Drive {
    // A small LCG, so this file needs no dependency either.
    let mut s = tick.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    let mut next = || {
        s = s.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
        (s >> 33) as u32
    };

    // Ticks 0..20: reset held, then released. Nothing else is exercised
    // while it is down.
    if tick < 20 {
        return Drive { reset: true, hang: false, ilong: false, speed: Speed::Normal };
    }

    let t = tick - 20;

    // Each speed and each ILONG in turn, a few cycles at a time, so every one
    // of the seven taps is reached with no other input moving. 220 ticks is
    // long enough for several cycles at the slowest.
    if t < 8 * 220 {
        let seg = (t / 220) as u32;
        let speed = match seg / 2 {
            0 => Speed::Fast,
            1 => Speed::Normal,
            2 => Speed::Slow,
            _ => Speed::ExtraSlow,
        };
        return Drive { reset: false, hang: false, ilong: seg % 2 == 1, speed };
    }

    let t = t - 8 * 220;

    // -HANG, on and off in runs of a few ticks to a few cycles, so the park
    // at the boundary is entered from every phase and left again.
    if t < 3_000 {
        let hang = (t / 7) % 5 == 0 || (t / 61) % 9 == 0;
        return Drive { reset: false, hang, ilong: (t / 313) % 2 == 1, speed: Speed::Normal };
    }

    // Everything moving at once, including speed and ILONG changing inside a
    // cycle --- which is what SELECT_NS at 65 ns is there to settle.
    let v = next();
    let speed = match v & 3 {
        0 => Speed::ExtraSlow,
        1 => Speed::Slow,
        2 => Speed::Normal,
        _ => Speed::Fast,
    };
    Drive { reset: false, hang: v & 0x30 == 0, ilong: v & 0x40 != 0, speed }
}

impl Drive {
    fn inputs(self) -> Inputs {
        Inputs {
            // MACHRUN gates -CLK0 on the board at CLOCK2 1D10, not in the
            // generator: `advance` never reads it, and the RTL has no port
            // for it.
            machrun: true,
            hang: self.hang,
            ilong: self.ilong,
            speed: self.speed,
            reset: self.reset,
        }
    }
}

fn main() {
    let mut clk = Behavioural::new();
    let mut out = Outputs::default();

    println!("# tick rst hang ilong speed | tpclk n_tpclk tptse n_tpwp n_tpwpiram n_tpr60");
    println!("# generated by golden/src/phase_gen.rs from muir's clock::Behavioural");

    for tick in 0..TICKS {
        let now = tick * TICK_NS;
        let d = drive(tick);
        let inputs = d.inputs();

        // Every event due at or before now.
        while let Some(at) = clk.next_at(inputs) {
            if at > now {
                break;
            }
            out = clk.advance(inputs).1;
        }

        // Reset is not an event: `advance` under it clears the outputs and
        // leaves a CycleStart pending at the current time, and `next_at`
        // answers None for as long as it is held. So it is taken here.
        let held = if inputs.reset {
            out = clk.advance(inputs).1;
            true
        } else {
            clk.next_at(inputs).is_none()
        };

        // A held generator is held for the *whole* of this tick, so what it
        // has pending belongs to the next one. Passing only to `now` would
        // anchor the restarted cycle at the tick reset or `-HANG` was last
        // seen, and `start_cycle` schedules the rest of the cycle from there
        // --- putting every later event five nanoseconds off the tick grid.
        clk.pass(if held { now + TICK_NS } else { now }, held);

        // -TPR60 as chip.rs puts it on the board, from the phase.
        let phase_ns = clk.phase_ns();
        let tpr60 = (60..60 + clock::TPR_PULSE_NS).contains(&phase_ns);

        let b = |v: bool| u8::from(v);
        println!(
            "{tick} {} {} {} {} {} {} {} {} {} {}",
            b(d.reset),
            b(d.hang),
            b(d.ilong),
            d.speed as u8,
            // The board's own names and senses: the two write-pulse latches
            // and -TPR60 are active low.
            b(out.tpclk),
            b(!out.tpclk),
            b(out.tptse),
            b(!out.tpwp),
            b(!out.tpwpiram),
            b(!tpr60),
        );
    }
}
