// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! Where every free-running clock of the whole machine starts, out of muir,
//! under the fabric's timing model.
//!
//! **muir counts every oscillator from its t = 0.**  The I/O board's
//! microsecond clock has its first edge at `ioboard::FIRST_USEC_EDGE_NS` and a
//! microsecond after each, its half-microsecond clock at
//! `busint::IOB_HALF_USEC_PHASE_NS` and every `IOB_HALF_USEC_NS`, `FCLK^` at
//! multiples of `IOB_FCLK_NS`, `KB CLK^` at multiples of `KB_CLK_NS` and the
//! mains at multiples of `SIXTY_CYCLE_NS`; the display's program from
//! power-on runs from zero until the software restarts it.  Under
//! `TimingModel::Fpga` each edge is taken at the first tick at or after its
//! exact instant, which is what `free_running` answers.
//!
//! **The fabric's t = 0 is the processor's, and this trace carries it.**  The
//! first microcycles of muir's `rtl` engine running MIT's boot PROM end at
//! instants the composed machine's `clock_edge` reproduces tick for tick
//! (`machine.pass`), so the check finds the origin from those and from nothing
//! the clocks themselves decide.  A clock started at the wrong edge in the
//! whole machine and at the right one in its own module's check agrees with
//! that check and not with this one, which is issue #21's lesson: a check whose
//! origin is set by its own reset can share a wrong origin with the module it
//! checks.
//!
//! Every value decimal, every instant in muir's nanoseconds.

// The engine and the row as `rtl.golden` makes them; not its column names.
#[allow(dead_code)]
mod trace;

use muir::busint::{IOB_FCLK_NS, IOB_HALF_USEC_NS, IOB_HALF_USEC_PHASE_NS};
use muir::clock::{GRID_NS, TimingModel};
use muir::engine::Engine;
use muir::ioboard::{FIRST_USEC_EDGE_NS, KB_CLK_NS, SIXTY_CYCLE_NS};
use muir::machine::Machine;
use muir::tv::Tv;

const TICK_NS: u64 = 10;

/// The processor's first microcycles, which fix the origin.
const BOUNDARIES: u64 = 8;

fn edges(first: u64, period: u64, n: u64) -> Vec<u64> {
    (0..n).map(|k| trace::TIMING.free_running(first + k * period)).collect()
}

fn line(name: &str, values: &[u64]) {
    let v: Vec<String> = values.iter().map(|x| x.to_string()).collect();
    println!("{name} {}", v.join(" "));
}

fn main() {
    assert_eq!(TICK_NS, GRID_NS, "the fabric's grid is muir's fpga grid");
    assert_eq!(trace::TIMING, TimingModel::Fpga);

    println!("# generated by golden/src/power_on.rs from muir under --timing-model fpga");
    println!("# every instant in muir's nanoseconds; the first tick at or after each edge");
    println!("tick_ns {TICK_NS}");

    // The origin: muir's rtl engine on the boot PROM, as `rtl.golden` dates
    // its rows.
    let mut m = Machine::new();
    m.load_prom(&muir::prom::boot_prom());
    let mut e = trace::engine(m);
    e.boot();
    let mut t = trace::Trace::new(&e);
    let mut ends = Vec::new();
    for cycle in 0..BOUNDARIES {
        if let Err(h) = t.row(&mut e, cycle) {
            eprintln!("power_on: stopped at microcycle {cycle}: {h:?}");
            std::process::exit(1);
        }
        ends.push(e.ns());
    }
    line("microcycle_ends", &ends);

    // The I/O board, from power-on.
    line("usec", &edges(FIRST_USEC_EDGE_NS, 1_000, 3));
    line("half_usec", &edges(IOB_HALF_USEC_PHASE_NS, IOB_HALF_USEC_NS, 4));
    line("fclk", &edges(IOB_FCLK_NS, IOB_FCLK_NS, 8));
    line("kb_clk", &edges(KB_CLK_NS, KB_CLK_NS, 3));
    line("sixty_cycle", &edges(SIXTY_CYCLE_NS, SIXTY_CYCLE_NS, 2));

    // The display's program from power-on: `-TVMA CLR` twice, and the first
    // four changes of the sync bits, which land at instructions' boundaries
    // in the program's first two lines.
    let tv = Tv::default();
    let tl = tv.timeline().expect("cpt.prom makes a frame");
    let first = tv.origin() + tl.next_tvma_clr_after(0);
    let second = tv.origin() + tl.next_tvma_clr_after(first - tv.origin());
    line("tvma_clr", &[first, second]);
    let mut changes = Vec::new();
    let mut before = tv.sync_at(0);
    let mut ns = TICK_NS;
    while changes.len() < 4 && ns <= 32_000 {
        let now = tv.sync_at(ns);
        if now != before {
            changes.push(ns);
            before = now;
        }
        ns += TICK_NS;
    }
    assert_eq!(changes.len(), 4, "the program changes the sync bits four times in its first two lines");
    line("sync_changes", &changes);
}
