// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! QUUX's keyboard and mouse (contract Q3) as muir's `quux_input::QuuxInput`
//! answers a script: key words pressed, motion and buttons, reads and writes
//! of words 120-123, and whether the keyboard's boot word came in.  Each line
//! is one operation and what muir gives for it, with the interrupt status's
//! two bits after it:
//!
//! ```text
//! p WORD IRQ          a key word pressed on the cable
//! m X Y IRQ           the mouse's counts are now X and Y (twelve bits)
//! b MASK IRQ          the buttons are now MASK
//! r K VALUE IRQ       a read of word K, and what it gave
//! w K VALUE IRQ       a write of VALUE to word K
//! t BOOT              whether the boot word came in since the last `t`
//! ```
//!
//! **THE MOTION IS GIVEN AS THE COUNTS IT LEAVES**, not as the host's deltas:
//! in the fabric the counts are the I/O board's, which the host moves through
//! the mouse's lines, and `tb/quux_input_tb.cpp` drives `quux_input.sv` with
//! them as the board would.  The deltas are the stimulus and their sum,
//! wrapping at twelve bits, is what the board's counters would hold; what
//! word 122 reads back is muir's own, so a sum here that disagreed with
//! muir's would fail on the next read.
//!
//! Every value is hexadecimal.  `quux_input.sv` is held to it row for row.

use muir::quux_input::{KeyboardMouse, QuuxInput};

fn main() {
    let mut q = QuuxInput::new();
    // A small generator of our own, deterministic, so the script is the same
    // every time it is made.
    let mut seed: u64 = 0x5155_0006_0003_1234;
    let mut next = move || {
        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;
        seed
    };
    println!("# generated by golden/src/quux_input.rs from muir's quux_input::QuuxInput");
    let irq = |q: &QuuxInput| q.interrupts() >> 3;
    // The counts, as the host's motion leaves them: the deltas are the
    // stimulus, and word 122's reads are muir's.
    let (mut x, mut y) = (0i32, 0i32);
    let mut ops = 0;
    let mut buttons = 0u8;
    // Directed: the enables, three words, the FIFO drained past empty.
    for (k, v) in [(0o120u32, 1u32 << 8), (0o123, 1 << 8)] {
        q.write(k, v);
        println!("w {k:x} {v:x} {:x}", irq(&q));
    }
    for w in [0o123456u32, 0o7654321, 0o40] {
        q.press(w);
        println!("p {w:x} {:x}", irq(&q));
    }
    for k in [0o120u32, 0o121, 0o121, 0o121, 0o121, 0o120] {
        let v = q.read(k).unwrap();
        println!("r {k:x} {v:x} {:x}", irq(&q));
    }
    // Sixty-six words, two past the FIFO, and the overflow.
    for k in 0..66u32 {
        let w = 0o100000 + k;
        q.press(w);
        println!("p {w:x} {:x}", irq(&q));
    }
    for (k, v) in [(0o120u32, 0u32)] {
        let r = q.read(k).unwrap();
        println!("r {k:x} {r:x} {:x}", irq(&q));
        q.write(k, v);
        println!("w {k:x} {v:x} {:x}", irq(&q));
    }
    // The boot word, `ioboard::boot_word`: bits 13:6 = 0o360.
    println!("t {}", q.take_boot() as u8);
    let boot = 0o360u32 << 6;
    q.press(boot);
    println!("p {boot:x} {:x}", irq(&q));
    println!("t {}", q.take_boot() as u8);
    println!("t {}", q.take_boot() as u8);
    // Random: presses, reads, writes, motion and buttons.
    while ops < 4000 {
        ops += 1;
        let r = next();
        match r % 9 {
            0 => {
                let w = (next() & 0o77777777) as u32;
                q.press(w);
                println!("p {w:x} {:x}", irq(&q));
            }
            1 | 2 => {
                let k = [0o120u32, 0o121, 0o122, 0o123][(next() % 4) as usize];
                let v = q.read(k).unwrap();
                println!("r {k:x} {v:x} {:x}", irq(&q));
            }
            3 => {
                let k = [0o120u32, 0o121, 0o122, 0o123][(next() % 4) as usize];
                let v = (next() as u32) & if next() % 2 == 0 { 0o400 } else { 0xffff_ffff };
                q.write(k, v);
                println!("w {k:x} {v:x} {:x}", irq(&q));
            }
            4 | 5 => {
                let dx = (next() % 41) as i32 - 20;
                let dy = if next() % 3 == 0 { 0 } else { (next() % 5001) as i32 - 2500 };
                q.mouse_move(dx, dy);
                x = (x + dx).rem_euclid(4096);
                y = (y + dy).rem_euclid(4096);
                println!("m {x:x} {y:x} {:x}", irq(&q));
            }
            6 => {
                if next() % 2 == 0 {
                    buttons = (next() % 8) as u8;
                }
                q.mouse_buttons(buttons);
                println!("b {buttons:x} {:x}", irq(&q));
            }
            7 => {
                // A burst, to reach the full FIFO again now and then.
                for _ in 0..(next() % 30) {
                    let w = (next() & 0o77777777) as u32 & !(0o377 << 6);
                    q.press(w);
                    println!("p {w:x} {:x}", irq(&q));
                }
            }
            _ => {
                println!("t {}", q.take_boot() as u8);
            }
        }
    }
    eprintln!("quux_input: {ops} operations");
}
