// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! QUUX's block-disk as muir's `block_disk::BlockDisk` answers a script of
//! register reads and writes at given instants, over a pack and a main
//! memory whose first contents are a rule both sides know.  Each line:
//!
//! ```text
//! geometry BLOCKS MEMWORDS    the pack's blocks and main memory's words
//! pack LBA                    block LBA holds `pack_word(LBA, w)`; every
//!                             other block of the pack is zero
//! mem ADDR WORD               main memory's word ADDR, over `mem_word`
//! w REG VALUE NS              a write of register REG at NS
//! r REG VALUE NS              a read of register REG at NS, and its word
//! i LEVEL NS                  the done interrupt at NS
//! page PAGE HASH              at the end, main memory's page PAGE
//! block LBA HASH              at the end, block LBA of the pack
//! ```
//!
//! **THE READS ARE TAKEN WHERE THE FABRIC CAN ANSWER THEM.**  muir moves the
//! words at START and knows the disk address, the last memory address and
//! the errors then; the fabric walks the command list over the blocks' time
//! (`rtl/machine/quux_block_disk.sv` says why), so a register is read here
//! once the walk has had the time it needs --- `WALK_NS` after a START ---
//! and the status's not-active bit on either side of muir's instant.  What
//! is compared at the end is every page of memory and every block the
//! script names, whole.  Every value is hexadecimal and every instant in
//! nanoseconds.

use muir::block_disk::{self, BlockDisk};
use muir::disk_unit::{BLOCK_WORDS, Geometry, Unit};

/// The pack's first contents: a word that is a function of the block and the
/// word, so no wrong block and no wrong offset reads right.
fn pack_word(lba: u32, w: u32) -> u32 {
    (lba << 12) ^ (w << 1) ^ 0x5a00_0001 ^ lba.rotate_left(23)
}

/// Main memory's first contents, the same way.
fn mem_word(a: u32) -> u32 {
    a.wrapping_mul(0x9e37_79b9) ^ 0x0c0f_fee0
}

fn hash(words: &[u32]) -> u32 {
    let mut h = 0x811c_9dc5u32;
    for &w in words {
        for b in w.to_le_bytes() {
            h ^= b as u32;
            h = h.wrapping_mul(0x0100_0193);
        }
    }
    h
}

/// What a walk of `blocks` blocks is given before its registers are read:
/// time enough for the fabric's walk with the testbench's pack side and
/// memory, well inside muir's `BLOCK_NS` a block.
const WALK_NS: u64 = 60_000;

const READ: u32 = 0;
const WRITE: u32 = 0o11;
const DONE: u32 = 1 << 11;

struct Script {
    d: BlockDisk,
    main: Vec<u32>,
    now: u64,
    blocks: Vec<u32>,
}

impl Script {
    fn at(&mut self, ns: u64) {
        assert!(ns >= self.now && ns % 10 == 0);
        self.now = ns;
        self.d.advance(ns);
    }
    fn w(&mut self, reg: u32, v: u32, ns: u64) {
        self.at(ns);
        self.d.write(reg, v, &mut self.main);
        println!("w {reg:x} {v:x} {ns:x}");
    }
    fn r(&mut self, reg: u32, ns: u64) -> u32 {
        self.at(ns);
        let v = self.d.read(reg);
        println!("r {reg:x} {v:x} {ns:x}");
        v
    }
    fn i(&mut self, ns: u64) -> bool {
        self.at(ns);
        let v = self.d.interrupt();
        println!("i {} {ns:x}", v as u8);
        v
    }
    fn mem(&mut self, a: u32, v: u32) {
        self.main[a as usize] = v;
        println!("mem {a:x} {v:x}");
    }
    /// A transfer: the list at `clp`, from block `da`, of `cmd`; then the
    /// registers read once the walk is done, and not-active and the
    /// interrupt on either side of muir's instant.
    fn transfer(&mut self, clp: u32, da: u32, cmd: u32, moved: u64) -> u32 {
        let t = self.now + 1_000;
        self.w(block_disk::CLP, clp, t);
        self.w(block_disk::DA, da, t + 1_000);
        self.w(block_disk::COMMAND, cmd, t + 2_000);
        let start = t + 3_000;
        self.w(block_disk::START, 0, start);
        let seen = start + WALK_NS * moved.max(1);
        let s = self.r(block_disk::STATUS, seen);
        self.r(block_disk::CLP, seen + 20);
        self.r(block_disk::DA, seen + 40);
        let done = start + moved * block_disk::BLOCK_NS;
        if done > seen + 60 {
            self.r(block_disk::STATUS, done - 20);
            self.i(done - 10);
        }
        self.r(block_disk::STATUS, done.max(seen + 60));
        self.i(done.max(seen + 60) + 10);
        s
    }
}

fn main() {
    let g = Geometry::T80;
    let blocks = g.blocks();
    let mem_words: u32 = 0o400000;
    println!("# generated by golden/src/quux_block_disk.rs from muir's block_disk::BlockDisk");
    println!("geometry {blocks:x} {mem_words:x}");
    let mut u = Unit::blank(g);
    let mut named: Vec<u32> = Vec::new();
    let preload = |u: &mut Unit, lba: u32| {
        let b: [u32; BLOCK_WORDS] = std::array::from_fn(|w| pack_word(lba, w as u32));
        assert!(u.write_lba(lba, &b));
        println!("pack {lba:x}");
    };
    for lba in (0..64).chain([blocks - 2, blocks - 1]).chain(1000..1003) {
        preload(&mut u, lba);
        named.push(lba);
    }
    let mut d = BlockDisk::new(block_disk::BLOCK_NS);
    d.attach(u);
    let main: Vec<u32> = (0..mem_words).map(mem_word).collect();
    let mut s = Script { d, main, now: 0, blocks: named };

    s.r(block_disk::STATUS, 1_000);
    s.i(1_010);
    // A read of two blocks, the done interrupt enabled.
    s.mem(0o100, 0o1000 | 1);
    s.mem(0o101, 0o1400);
    s.transfer(0o100, 3, READ | DONE, 2);
    // A write of those two pages to blocks 100 and 101, and a read of them
    // back into two others.
    s.transfer(0o100, 100, WRITE, 2);
    s.mem(0o102, 0o2000 | 1);
    s.mem(0o103, 0o2400);
    s.transfer(0o102, 100, READ | DONE, 2);
    // A command it does not do, then a clear by writing the command.
    let t = s.now + 1_000;
    s.w(block_disk::COMMAND, 0o03, t);
    s.w(block_disk::START, 0, t + 1_000);
    s.r(block_disk::STATUS, t + 2_000);
    s.w(block_disk::COMMAND, READ, t + 3_000);
    s.r(block_disk::STATUS, t + 4_000);
    // Past the end: the last block, then one past it.
    s.mem(0o104, 0o3000 | 1);
    s.mem(0o105, 0o3400);
    s.transfer(0o104, blocks - 1, READ, 1);
    // A write past the end.
    s.transfer(0o104, blocks, WRITE | DONE, 0);
    // A command list word main memory does not have, and a page it does
    // not have.
    s.transfer(0o500000, 5, READ, 0);
    s.mem(0o106, 0o77777400);
    s.transfer(0o106, 5, READ, 0);
    // The pointer's low sixteen bits wrap.
    s.mem(0o377777, 0o4000 | 1);
    s.mem(0o200000, 0o4400);
    s.transfer(0o377777, 7, READ, 2);
    // Forty blocks in one list: more than the store holds, so blocks are
    // written back and taken away as the walk goes.
    for k in 0..40u32 {
        let more = if k < 39 { 1 } else { 0 };
        s.mem(0o1000 + k, (0o10000 + 0o400 * k) | more);
    }
    s.transfer(0o1000, 10, READ | DONE, 40);
    s.transfer(0o1000, 20000, WRITE | DONE, 40);
    for k in 20000..20040u32 {
        s.blocks.push(k);
    }
    s.transfer(0o1000, 1000, READ, 40);
    for k in 1003..1040u32 {
        s.blocks.push(k);
    }
    s.w(block_disk::COMMAND, 0, s.now + 1_000);

    // The end: every page, and every block named.
    for p in 0..(mem_words / 256) {
        let a = (p * 256) as usize;
        println!("page {p:x} {:x}", hash(&s.main[a..a + 256]));
    }
    let now = s.now;
    let u = s.d.unit_mut().unwrap();
    for &lba in &s.blocks {
        let b = u.read_lba(lba).unwrap();
        println!("block {lba:x} {:x}", hash(&b));
    }
    eprintln!("quux_block_disk: the script ends at {now} ns");
}
