// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! The reference for `rtl/machine/cadr_xbus_decode.sv`: which side of the bus a
//! physical address is on and whether anything lives there, out of muir's own
//! `busint::decode`.
//!
//! The Xbus carries 22 address bits --- `-XADDR0` to `-XADDR21` in
//! `data/busint-connectors.txt` --- so the whole space is 4,194,304 words and
//! can be checked address by address rather than sampled. That is what this
//! is for: the decode is piecewise constant over long runs, so the runs are
//! what gets written out, and the testbench expands them and walks every
//! address.
//!
//! The four answers, and where the boundaries come from:
//!
//! - **memory**, below `0o36000` pages and below the boards fitted. A board is
//!   64K words, so `phys[21:16] < boards`;
//! - **device**, Xbus I/O with something built at the address: the display's
//!   frame buffer at `0o17000000` for `0o100000` words, its eight control
//!   registers at `0o17377760`, and the disk controller's four at
//!   `0o17377774` --- and, on a machine that has a SECOND display board, the
//!   color TV's frame buffer at `0o17200000` and its control registers at
//!   `0o17377750`;
//! - **nxm**, Xbus space with nothing there --- "the cycle times out and sets
//!   the Xbus NXM bit";
//! - **unibus**, at or above page `0o37000`. Out of this slice: the Unibus
//!   path, the interface's own registers and the debug block are their own.
//!
//! The board count is swept because it is the one thing meant to change ---
//! going from two million words to the ceiling is this constant and no extra
//! fabric.  **And the color board is swept for a sharper reason**: its two
//! ranges must answer when it is fitted and must give the NXM when it is
//! not, because that is how `COLOR-EXISTS-P` in `sys/window/color.lisp`
//! finds out whether a machine has one.  muir's `busint::decode_with` takes
//! the same fact and `busint::decode` is it with none.

mod machine_axis;

use muir::busint::{self, Responder};
use muir::machine::Machine;

/// The Xbus address space: 22 bits.
const WORDS: u32 = 1 << 22;

/// A board is 64K words.
const WORDS_PER_BOARD: u32 = 1 << 16;

/// Board counts to sweep. One and sixty are the ends of muir's own
/// `--main-memory-boards`; 32 is its default, the two million words; 2 is
/// small enough that the boundary sits well inside the space.
const BOARDS: &[u32] = &[1, 2, 32, 60];

fn kind(r: Responder) -> &'static str {
    if r.on_unibus() {
        return "unibus";
    }
    match r {
        Responder::Memory(_) => "memory",
        Responder::Device => "device",
        _ => "nxm",
    }
}

/// **QUUX's decode is muir's own question asked on QUUX**: the Unibus window
/// times out as empty Xbus space, QUUX having no Unibus (contract Q5); the
/// feature page is answered as a device ahead of the bus interface's decode
/// (`Geometry::feature_word`, as `Rtl::start_bus_cycle` does it), and the
/// main display's buffer is MONO TV's at the bitstreams' size,
/// `busint::decode_for` with `Tv::buffer_words`.  The machine is built by
/// `machine_axis.rs`, so the size is the one every other QUUX trace has.
fn decode(m: &Machine, phys: u32, words: usize, color: bool) -> Responder {
    if m.geometry.feature_word(phys).is_some() {
        return Responder::Device;
    }
    // QUUX has no Unibus (contract Q5): the window times out as Xbus, as
    // `Rtl::start_bus_cycle` answers it with `Responder::NoXbus`.
    if !m.geometry.unibus && busint::unibus_address(phys).is_some() {
        return Responder::NoXbus;
    }
    busint::decode_for(phys, words, color, m.tv.buffer_words(), m.tv.control_registers())
}

fn main() {
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    let which = machine_axis::take(&mut args);
    if let Some(a) = args.first() {
        eprintln!("xbus_decode: unknown argument `{a}`; usage: xbus_decode [--machine cadr|quux]");
        std::process::exit(2);
    }
    let quux = which == machine_axis::Which::Quux;
    let m = which.machine(&[]);
    println!("# boards color first last kind");
    if quux {
        println!("# generated by golden/src/xbus_decode.rs from muir's busint::decode_for on QUUX, with its feature page");
    } else {
        println!("# generated by golden/src/xbus_decode.rs from muir's busint::decode_with");
    }

    let mut runs = 0;
    for &boards in BOARDS {
        for color in [false, true] {
            let c = u8::from(color);
            let words = (boards * WORDS_PER_BOARD) as usize;
            let mut first = 0u32;
            let mut held = kind(if quux { decode(&m, 0, words, color) } else { busint::decode_with(0, words, color) });
            for phys in 1..WORDS {
                let k = kind(if quux { decode(&m, phys, words, color) } else { busint::decode_with(phys, words, color) });
                if k != held {
                    println!("{boards} {c} {first} {} {held}", phys - 1);
                    runs += 1;
                    first = phys;
                    held = k;
                }
            }
            println!("{boards} {c} {first} {} {held}", WORDS - 1);
            runs += 1;
        }
    }

    eprintln!("xbus_decode: {runs} runs over {} board counts and both backplanes", BOARDS.len());
}
