// SPDX-FileCopyrightText: 2026 Mete Balci
// SPDX-License-Identifier: AGPL-3.0-or-later
//
//! The reference for `rtl/machine/cadr_xbus_decode.sv`: which side of the bus a
//! physical address is on and whether anything lives there, out of muir's own
//! `busint::decode`.
//!
//! The Xbus carries 22 address bits --- `-XADDR0` to `-XADDR21` in
//! `data/busint-connectors.txt` --- so the whole space is 4,194,304 words and
//! can be checked address by address rather than sampled. That is what this
//! is for: the decode is piecewise constant over long runs, so the runs are
//! what gets written out, and the testbench expands them and walks every
//! address.
//!
//! The four answers, and where the boundaries come from:
//!
//! - **memory**, below `0o36000` pages and below the boards fitted. A board is
//!   64K words, so `phys[21:16] < boards`;
//! - **device**, Xbus I/O with something built at the address: the display's
//!   frame buffer at `0o17000000` for `0o100000` words, its eight control
//!   registers at `0o17377760`, and the disk controller's four at
//!   `0o17377774` --- and, on a machine that has a SECOND display board, the
//!   color TV's frame buffer at `0o17200000` and its control registers at
//!   `0o17377750`;
//! - **nxm**, Xbus space with nothing there --- "the cycle times out and sets
//!   the Xbus NXM bit";
//! - **unibus**, at or above page `0o37000`. Out of this slice: the Unibus
//!   path, the interface's own registers and the debug block are their own.
//!
//! The board count is swept because it is the one thing meant to change ---
//! going from two million words to the ceiling is this constant and no extra
//! fabric.  **And the color board is swept for a sharper reason**: its two
//! ranges must answer when it is fitted and must give the NXM when it is
//! not, because that is how `COLOR-EXISTS-P` in `sys/window/color.lisp`
//! finds out whether a machine has one.  muir's `busint::decode_with` takes
//! the same fact and `busint::decode` is it with none.

mod machine_axis;

use muir::busint::{self, Responder};
use muir::machine::Machine;

/// The Xbus address space: 22 bits.
const WORDS: u32 = 1 << 22;

/// A board is 64K words.
const WORDS_PER_BOARD: u32 = 1 << 16;

/// Board counts to sweep. One and sixty are the ends of muir's own
/// `--main-memory-boards`; 32 is its default, the two million words; 2 is
/// small enough that the boundary sits well inside the space.
const BOARDS: &[u32] = &[1, 2, 32, 60];

fn kind(r: Responder) -> &'static str {
    if r.on_unibus() {
        return "unibus";
    }
    match r {
        Responder::Memory(_) => "memory",
        Responder::Device => "device",
        _ => "nxm",
    }
}

/// **QUUX's decode is muir's own question asked on QUUX**, `busint::decode_quux`
/// (contracts Q5, Q7 and Q13), which `Rtl::start_bus_cycle` and
/// `Machine::bus_read` both take on QUUX: the register page,
/// `17777400`-`17777777`, a device; the video controller's frame buffer from
/// `17000000` at the bitstreams' size, `Tv::buffer_words`; main memory below
/// `17000000`; and nothing else.  The old register page at `17377000`, the
/// CADR's display and disk registers after it and the rest of the old Unibus
/// window are nothing there, and **QUUX has no color board**, so the color
/// input changes nothing on QUUX.  The machine is built by `machine_axis.rs`,
/// so the size is the one every other QUUX trace has.
///
/// **THE FRAME BUFFER IS NAMED A DEVICE HERE, AS THE FABRIC'S DECODE NAMES
/// IT**: muir answers it `Responder::Memory(0)`, the memory bus, and the
/// fabric takes it to the memory port the same way, but by the video
/// controller's own held match (`cadr_memory_path.sv`'s `video_fb`) inside
/// the decode's `device`, which is how the port tells the buffer from a
/// register.  So an address muir puts on the memory bus at or above
/// `tv::BUFFER`, which is only ever the buffer, is written `device`; every
/// boundary is still muir's, and what the buffer's cycles do is held on the
/// whole machine by `quux_tv` and `quux_port`.
fn decode(m: &Machine, phys: u32, words: usize) -> Responder {
    match busint::decode_quux(phys, words, m.tv.buffer_words()) {
        Responder::Memory(_) if phys >= muir::tv::BUFFER => Responder::Device,
        r => r,
    }
}

fn main() {
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    let which = machine_axis::take(&mut args);
    if let Some(a) = args.first() {
        eprintln!("xbus_decode: unknown argument `{a}`; usage: xbus_decode [--machine cadr|quux]");
        std::process::exit(2);
    }
    let quux = which == machine_axis::Which::Quux;
    let m = which.machine(&[]);
    println!("# boards color first last kind");
    if quux {
        println!("# generated by golden/src/xbus_decode.rs from muir's busint::decode_quux on QUUX, with its register page");
    } else {
        println!("# generated by golden/src/xbus_decode.rs from muir's busint::decode_with");
    }

    let mut runs = 0;
    for &boards in BOARDS {
        for color in [false, true] {
            let c = u8::from(color);
            let words = (boards * WORDS_PER_BOARD) as usize;
            let mut first = 0u32;
            let mut held = kind(if quux { decode(&m, 0, words) } else { busint::decode_with(0, words, color) });
            for phys in 1..WORDS {
                let k = kind(if quux { decode(&m, phys, words) } else { busint::decode_with(phys, words, color) });
                if k != held {
                    println!("{boards} {c} {first} {} {held}", phys - 1);
                    runs += 1;
                    first = phys;
                    held = k;
                }
            }
            println!("{boards} {c} {first} {} {held}", WORDS - 1);
            runs += 1;
        }
    }

    eprintln!("xbus_decode: {runs} runs over {} board counts and both backplanes", BOARDS.len());
}
